/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/common.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_a_refresh_reports_the_reading_it_was_handed(void);
extern void test_the_epoch_climbs_through_a_reading_that_wraps(void);
extern void test_now_and_the_epoch_disagree_once_the_reading_has_wrapped(void);
extern void test_many_wraps_each_raise_the_epoch_by_one_period(void);
extern void test_a_refresh_leaves_the_stamp_where_it_was(void);
extern void test_opening_a_pass_takes_the_reading_standing_now(void);
extern void test_elapsed_survives_a_wrap_between_the_stamp_and_the_reading(void);
extern void test_a_lifetime_in_seconds_scales_exactly(void);
extern void test_the_widest_lifetime_still_lands_ahead_of_a_stamp(void);
extern void test_a_split_epoch_rejoins_to_itself(void);
extern void test_the_loose_word_extension_matches_a_refresh(void);
extern void test_the_pad_is_the_stamp_plus_the_milliseconds(void);
extern void test_the_state_in_the_word_does_not_reach_the_pad(void);
extern void test_the_four_states_are_told_apart(void);
extern void test_a_single_state_moves_the_pad_not_at_all(void);
extern void test_the_same_state_twice_steps_the_pad(void);
extern void test_one_disturbed_pass_does_not_disturb_the_pad(void);
extern void test_a_met_pad_never_moves(void);
extern void test_the_pad_never_steps_outside_its_range(void);
extern void test_an_unset_pad_stays_unset(void);
extern void test_the_pad_converges_and_stays(void);
extern void test_the_widest_pad_does_not_reach_the_state_bits(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/base/test_clock\\test_clock.c");
  run_test(test_a_refresh_reports_the_reading_it_was_handed, "test_a_refresh_reports_the_reading_it_was_handed", 36);
  run_test(test_the_epoch_climbs_through_a_reading_that_wraps, "test_the_epoch_climbs_through_a_reading_that_wraps", 44);
  run_test(test_now_and_the_epoch_disagree_once_the_reading_has_wrapped, "test_now_and_the_epoch_disagree_once_the_reading_has_wrapped", 59);
  run_test(test_many_wraps_each_raise_the_epoch_by_one_period, "test_many_wraps_each_raise_the_epoch_by_one_period", 67);
  run_test(test_a_refresh_leaves_the_stamp_where_it_was, "test_a_refresh_leaves_the_stamp_where_it_was", 84);
  run_test(test_opening_a_pass_takes_the_reading_standing_now, "test_opening_a_pass_takes_the_reading_standing_now", 95);
  run_test(test_elapsed_survives_a_wrap_between_the_stamp_and_the_reading, "test_elapsed_survives_a_wrap_between_the_stamp_and_the_reading", 107);
  run_test(test_a_lifetime_in_seconds_scales_exactly, "test_a_lifetime_in_seconds_scales_exactly", 117);
  run_test(test_the_widest_lifetime_still_lands_ahead_of_a_stamp, "test_the_widest_lifetime_still_lands_ahead_of_a_stamp", 128);
  run_test(test_a_split_epoch_rejoins_to_itself, "test_a_split_epoch_rejoins_to_itself", 138);
  run_test(test_the_loose_word_extension_matches_a_refresh, "test_the_loose_word_extension_matches_a_refresh", 152);
  run_test(test_the_pad_is_the_stamp_plus_the_milliseconds, "test_the_pad_is_the_stamp_plus_the_milliseconds", 167);
  run_test(test_the_state_in_the_word_does_not_reach_the_pad, "test_the_state_in_the_word_does_not_reach_the_pad", 175);
  run_test(test_the_four_states_are_told_apart, "test_the_four_states_are_told_apart", 184);
  run_test(test_a_single_state_moves_the_pad_not_at_all, "test_a_single_state_moves_the_pad_not_at_all", 198);
  run_test(test_the_same_state_twice_steps_the_pad, "test_the_same_state_twice_steps_the_pad", 207);
  run_test(test_one_disturbed_pass_does_not_disturb_the_pad, "test_one_disturbed_pass_does_not_disturb_the_pad", 221);
  run_test(test_a_met_pad_never_moves, "test_a_met_pad_never_moves", 235);
  run_test(test_the_pad_never_steps_outside_its_range, "test_the_pad_never_steps_outside_its_range", 245);
  run_test(test_an_unset_pad_stays_unset, "test_an_unset_pad_stays_unset", 264);
  run_test(test_the_pad_converges_and_stays, "test_the_pad_converges_and_stays", 275);
  run_test(test_the_widest_pad_does_not_reach_the_state_bits, "test_the_widest_pad_does_not_reach_the_state_bits", 290);

  return UNITY_END();
}
