/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/common.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_a_refresh_reports_the_reading_it_was_handed(void);
extern void test_the_epoch_climbs_through_a_reading_that_wraps(void);
extern void test_now_and_the_epoch_disagree_once_the_reading_has_wrapped(void);
extern void test_many_wraps_each_raise_the_epoch_by_one_period(void);
extern void test_a_refresh_leaves_the_stamp_where_it_was(void);
extern void test_opening_a_pass_takes_the_reading_standing_now(void);
extern void test_elapsed_survives_a_wrap_between_the_stamp_and_the_reading(void);
extern void test_a_lifetime_in_seconds_scales_exactly(void);
extern void test_the_widest_lifetime_still_lands_ahead_of_a_stamp(void);
extern void test_a_split_epoch_rejoins_to_itself(void);
extern void test_the_loose_word_extension_matches_a_refresh(void);
extern void test_the_pad_is_the_stamp_plus_the_pad_ticks(void);
extern void test_the_state_in_the_word_does_not_reach_the_pad(void);
extern void test_the_pad_reading_and_the_epoch_are_separate(void);
extern void test_the_pad_reading_survives_its_own_wrap(void);
extern void test_the_four_states_are_told_apart(void);
extern void test_the_state_in_the_word_does_not_reach_the_state_test(void);
extern void test_a_single_state_moves_the_pad_not_at_all(void);
extern void test_the_same_state_twice_steps_the_pad(void);
extern void test_the_tune_always_records_the_state_it_saw(void);
extern void test_one_disturbed_pass_does_not_disturb_the_pad(void);
extern void test_a_met_pad_never_moves(void);
extern void test_the_pad_never_steps_outside_its_range(void);
extern void test_an_unset_pad_stays_unset(void);
extern void test_the_pad_converges_and_stays(void);
extern void test_the_widest_pad_does_not_reach_the_state_bits(void);
extern void test_the_configured_window_is_a_window(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/base/test_clock\\test_clock.c");
  run_test(test_a_refresh_reports_the_reading_it_was_handed, "test_a_refresh_reports_the_reading_it_was_handed", 36);
  run_test(test_the_epoch_climbs_through_a_reading_that_wraps, "test_the_epoch_climbs_through_a_reading_that_wraps", 44);
  run_test(test_now_and_the_epoch_disagree_once_the_reading_has_wrapped, "test_now_and_the_epoch_disagree_once_the_reading_has_wrapped", 59);
  run_test(test_many_wraps_each_raise_the_epoch_by_one_period, "test_many_wraps_each_raise_the_epoch_by_one_period", 67);
  run_test(test_a_refresh_leaves_the_stamp_where_it_was, "test_a_refresh_leaves_the_stamp_where_it_was", 84);
  run_test(test_opening_a_pass_takes_the_reading_standing_now, "test_opening_a_pass_takes_the_reading_standing_now", 95);
  run_test(test_elapsed_survives_a_wrap_between_the_stamp_and_the_reading, "test_elapsed_survives_a_wrap_between_the_stamp_and_the_reading", 107);
  run_test(test_a_lifetime_in_seconds_scales_exactly, "test_a_lifetime_in_seconds_scales_exactly", 117);
  run_test(test_the_widest_lifetime_still_lands_ahead_of_a_stamp, "test_the_widest_lifetime_still_lands_ahead_of_a_stamp", 128);
  run_test(test_a_split_epoch_rejoins_to_itself, "test_a_split_epoch_rejoins_to_itself", 138);
  run_test(test_the_loose_word_extension_matches_a_refresh, "test_the_loose_word_extension_matches_a_refresh", 152);
  run_test(test_the_pad_is_the_stamp_plus_the_pad_ticks, "test_the_pad_is_the_stamp_plus_the_pad_ticks", 178);
  run_test(test_the_state_in_the_word_does_not_reach_the_pad, "test_the_state_in_the_word_does_not_reach_the_pad", 187);
  run_test(test_the_pad_reading_and_the_epoch_are_separate, "test_the_pad_reading_and_the_epoch_are_separate", 198);
  run_test(test_the_pad_reading_survives_its_own_wrap, "test_the_pad_reading_survives_its_own_wrap", 224);
  run_test(test_the_four_states_are_told_apart, "test_the_four_states_are_told_apart", 232);
  run_test(test_the_state_in_the_word_does_not_reach_the_state_test, "test_the_state_in_the_word_does_not_reach_the_state_test", 247);
  run_test(test_a_single_state_moves_the_pad_not_at_all, "test_a_single_state_moves_the_pad_not_at_all", 257);
  run_test(test_the_same_state_twice_steps_the_pad, "test_the_same_state_twice_steps_the_pad", 267);
  run_test(test_the_tune_always_records_the_state_it_saw, "test_the_tune_always_records_the_state_it_saw", 287);
  run_test(test_one_disturbed_pass_does_not_disturb_the_pad, "test_one_disturbed_pass_does_not_disturb_the_pad", 297);
  run_test(test_a_met_pad_never_moves, "test_a_met_pad_never_moves", 311);
  run_test(test_the_pad_never_steps_outside_its_range, "test_the_pad_never_steps_outside_its_range", 321);
  run_test(test_an_unset_pad_stays_unset, "test_an_unset_pad_stays_unset", 337);
  run_test(test_the_pad_converges_and_stays, "test_the_pad_converges_and_stays", 348);
  run_test(test_the_widest_pad_does_not_reach_the_state_bits, "test_the_widest_pad_does_not_reach_the_state_bits", 367);
  run_test(test_the_configured_window_is_a_window, "test_the_configured_window_is_a_window", 376);

  return UNITY_END();
}
