/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/nd/slaac.h"
#include "src/ip/ipv6_defines.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_clear_on_one_borrow_leaves_the_other_untouched(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_every_published_offset_is_aligned(void);
extern void test_the_io_macro_reaches_the_operand_block(void);
extern void test_clear_reports_ok(void);
extern void test_clear_zeroes_the_list(void);
extern void test_clear_zeroes_the_context_apart_from_the_mark(void);
extern void test_clear_leaves_the_operand_block_alone(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_the_link_local_address_is_the_rfc_2464_example(void);
extern void test_the_link_local_address_has_infinite_lifetimes(void);
extern void test_the_link_local_address_carries_the_prefix_and_zeroes_between(void);
extern void test_link_local_refuses_a_null_identifier(void);
extern void test_link_local_refuses_an_identifier_that_is_not_whole_octets(void);
extern void test_link_local_refuses_an_identifier_the_prefix_has_no_room_for(void);
extern void test_link_local_twice_holds_one_address(void);
extern void test_a_prefix_without_the_autonomous_flag_is_ignored(void);
extern void test_the_link_local_prefix_is_ignored(void);
extern void test_a_preferred_lifetime_above_the_valid_lifetime_is_ignored(void);
extern void test_a_new_prefix_forms_the_address_from_the_prefix_and_the_identifier(void);
extern void test_the_lifetimes_are_initialized_from_the_option(void);
extern void test_a_new_prefix_with_a_zero_valid_lifetime_is_ignored(void);
extern void test_a_prefix_length_that_does_not_sum_to_128_is_ignored(void);
extern void test_a_prefix_length_past_128_is_refused(void);
extern void test_a_full_list_is_busy_and_a_removal_frees_a_slot(void);
extern void test_two_prefixes_are_two_addresses(void);
extern void test_the_same_prefix_updates_rather_than_adding(void);
extern void test_a_lifetime_past_a_32_bit_millisecond_deadline_is_kept_whole(void);
extern void test_the_preferred_lifetime_is_always_reset(void);
extern void test_rule_1_a_valid_lifetime_above_two_hours_is_taken(void);
extern void test_rule_1_a_valid_lifetime_above_the_remaining_lifetime_is_taken(void);
extern void test_rule_2_a_shorter_lifetime_is_ignored_when_under_two_hours_remain(void);
extern void test_rule_2_an_authenticated_advertisement_sets_the_shorter_lifetime(void);
extern void test_rule_3_a_short_lifetime_against_a_long_one_resets_to_two_hours(void);
extern void test_rule_3_holds_at_exactly_two_hours(void);
extern void test_the_two_hour_rule_stops_an_advertisement_expiring_an_address_early(void);
extern void test_rule_1_an_infinite_valid_lifetime_is_taken(void);
extern void test_a_short_lifetime_against_an_infinite_one_resets_to_two_hours(void);
extern void test_a_zero_valid_lifetime_on_a_held_prefix_takes_the_two_hour_rule(void);
extern void test_a_preferred_lifetime_expiry_deprecates_the_address(void);
extern void test_a_valid_lifetime_expiry_invalidates_the_address_and_frees_the_slot(void);
extern void test_a_tick_with_nothing_due_is_busy(void);
extern void test_a_tick_reports_one_event_per_call(void);
extern void test_both_lifetimes_expired_invalidates_rather_than_deprecating(void);
extern void test_find_refuses_an_address_that_is_not_in_the_list(void);
extern void test_get_walks_the_list(void);
extern void test_get_refuses_a_slot_that_holds_nothing(void);
extern void test_remove_refuses_an_address_that_is_not_in_the_list(void);
extern void test_remove_frees_the_slot(void);
extern void test_two_interfaces_form_their_own_addresses(void);
extern void test_a_prefix_option_outside_its_own_fields_is_refused(void);
extern void test_the_link_local_prefix_is_the_first_ten_bits_and_not_the_first_octet(void);
extern void test_an_identifier_this_unit_cannot_lay_into_an_address_forms_none(void);
extern void test_an_address_already_in_the_list_is_reported_rather_than_added_twice(void);
extern void test_a_full_list_is_busy_for_a_link_local_address(void);
extern void test_a_prefix_is_compared_over_the_bits_its_length_names(void);
extern void test_an_identifier_of_no_bits_forms_no_address(void);
extern void test_the_address_entries_refuse_what_names_no_address(void);
extern void test_the_address_entries_refuse_an_uncleared_borrow(void);
extern void test_an_advertisement_meeting_an_address_with_nothing_left_takes_the_two_hour_rule(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/unit/nd/test_slaac/test_slaac.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 152);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 160);
  run_test(test_clear_on_one_borrow_leaves_the_other_untouched, "test_clear_on_one_borrow_leaves_the_other_untouched", 175);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 187);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 202);
  run_test(test_every_published_offset_is_aligned, "test_every_published_offset_is_aligned", 212);
  run_test(test_the_io_macro_reaches_the_operand_block, "test_the_io_macro_reaches_the_operand_block", 218);
  run_test(test_clear_reports_ok, "test_clear_reports_ok", 226);
  run_test(test_clear_zeroes_the_list, "test_clear_zeroes_the_list", 232);
  run_test(test_clear_zeroes_the_context_apart_from_the_mark, "test_clear_zeroes_the_context_apart_from_the_mark", 242);
  run_test(test_clear_leaves_the_operand_block_alone, "test_clear_leaves_the_operand_block_alone", 257);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 268);
  run_test(test_the_link_local_address_is_the_rfc_2464_example, "test_the_link_local_address_is_the_rfc_2464_example", 284);
  run_test(test_the_link_local_address_has_infinite_lifetimes, "test_the_link_local_address_has_infinite_lifetimes", 295);
  run_test(test_the_link_local_address_carries_the_prefix_and_zeroes_between, "test_the_link_local_address_carries_the_prefix_and_zeroes_between", 312);
  run_test(test_link_local_refuses_a_null_identifier, "test_link_local_refuses_a_null_identifier", 324);
  run_test(test_link_local_refuses_an_identifier_that_is_not_whole_octets, "test_link_local_refuses_an_identifier_that_is_not_whole_octets", 333);
  run_test(test_link_local_refuses_an_identifier_the_prefix_has_no_room_for, "test_link_local_refuses_an_identifier_the_prefix_has_no_room_for", 342);
  run_test(test_link_local_twice_holds_one_address, "test_link_local_twice_holds_one_address", 350);
  run_test(test_a_prefix_without_the_autonomous_flag_is_ignored, "test_a_prefix_without_the_autonomous_flag_is_ignored", 364);
  run_test(test_the_link_local_prefix_is_ignored, "test_the_link_local_prefix_is_ignored", 375);
  run_test(test_a_preferred_lifetime_above_the_valid_lifetime_is_ignored, "test_a_preferred_lifetime_above_the_valid_lifetime_is_ignored", 386);
  run_test(test_a_new_prefix_forms_the_address_from_the_prefix_and_the_identifier, "test_a_new_prefix_forms_the_address_from_the_prefix_and_the_identifier", 399);
  run_test(test_the_lifetimes_are_initialized_from_the_option, "test_the_lifetimes_are_initialized_from_the_option", 410);
  run_test(test_a_new_prefix_with_a_zero_valid_lifetime_is_ignored, "test_a_new_prefix_with_a_zero_valid_lifetime_is_ignored", 420);
  run_test(test_a_prefix_length_that_does_not_sum_to_128_is_ignored, "test_a_prefix_length_that_does_not_sum_to_128_is_ignored", 431);
  run_test(test_a_prefix_length_past_128_is_refused, "test_a_prefix_length_past_128_is_refused", 446);
  run_test(test_a_full_list_is_busy_and_a_removal_frees_a_slot, "test_a_full_list_is_busy_and_a_removal_frees_a_slot", 455);
  run_test(test_two_prefixes_are_two_addresses, "test_two_prefixes_are_two_addresses", 485);
  run_test(test_the_same_prefix_updates_rather_than_adding, "test_the_same_prefix_updates_rather_than_adding", 499);
  run_test(test_a_lifetime_past_a_32_bit_millisecond_deadline_is_kept_whole, "test_a_lifetime_past_a_32_bit_millisecond_deadline_is_kept_whole", 515);
  run_test(test_the_preferred_lifetime_is_always_reset, "test_the_preferred_lifetime_is_always_reset", 541);
  run_test(test_rule_1_a_valid_lifetime_above_two_hours_is_taken, "test_rule_1_a_valid_lifetime_above_two_hours_is_taken", 557);
  run_test(test_rule_1_a_valid_lifetime_above_the_remaining_lifetime_is_taken, "test_rule_1_a_valid_lifetime_above_the_remaining_lifetime_is_taken", 568);
  run_test(test_rule_2_a_shorter_lifetime_is_ignored_when_under_two_hours_remain, "test_rule_2_a_shorter_lifetime_is_ignored_when_under_two_hours_remain", 580);
  run_test(test_rule_2_an_authenticated_advertisement_sets_the_shorter_lifetime, "test_rule_2_an_authenticated_advertisement_sets_the_shorter_lifetime", 593);
  run_test(test_rule_3_a_short_lifetime_against_a_long_one_resets_to_two_hours, "test_rule_3_a_short_lifetime_against_a_long_one_resets_to_two_hours", 604);
  run_test(test_rule_3_holds_at_exactly_two_hours, "test_rule_3_holds_at_exactly_two_hours", 615);
  run_test(test_the_two_hour_rule_stops_an_advertisement_expiring_an_address_early, "test_the_two_hour_rule_stops_an_advertisement_expiring_an_address_early", 627);
  run_test(test_rule_1_an_infinite_valid_lifetime_is_taken, "test_rule_1_an_infinite_valid_lifetime_is_taken", 647);
  run_test(test_a_short_lifetime_against_an_infinite_one_resets_to_two_hours, "test_a_short_lifetime_against_an_infinite_one_resets_to_two_hours", 658);
  run_test(test_a_zero_valid_lifetime_on_a_held_prefix_takes_the_two_hour_rule, "test_a_zero_valid_lifetime_on_a_held_prefix_takes_the_two_hour_rule", 672);
  run_test(test_a_preferred_lifetime_expiry_deprecates_the_address, "test_a_preferred_lifetime_expiry_deprecates_the_address", 686);
  run_test(test_a_valid_lifetime_expiry_invalidates_the_address_and_frees_the_slot, "test_a_valid_lifetime_expiry_invalidates_the_address_and_frees_the_slot", 706);
  run_test(test_a_tick_with_nothing_due_is_busy, "test_a_tick_with_nothing_due_is_busy", 722);
  run_test(test_a_tick_reports_one_event_per_call, "test_a_tick_reports_one_event_per_call", 731);
  run_test(test_both_lifetimes_expired_invalidates_rather_than_deprecating, "test_both_lifetimes_expired_invalidates_rather_than_deprecating", 750);
  run_test(test_find_refuses_an_address_that_is_not_in_the_list, "test_find_refuses_an_address_that_is_not_in_the_list", 761);
  run_test(test_get_walks_the_list, "test_get_walks_the_list", 768);
  run_test(test_get_refuses_a_slot_that_holds_nothing, "test_get_refuses_a_slot_that_holds_nothing", 785);
  run_test(test_remove_refuses_an_address_that_is_not_in_the_list, "test_remove_refuses_an_address_that_is_not_in_the_list", 797);
  run_test(test_remove_frees_the_slot, "test_remove_frees_the_slot", 806);
  run_test(test_two_interfaces_form_their_own_addresses, "test_two_interfaces_form_their_own_addresses", 821);
  run_test(test_a_prefix_option_outside_its_own_fields_is_refused, "test_a_prefix_option_outside_its_own_fields_is_refused", 849);
  run_test(test_the_link_local_prefix_is_the_first_ten_bits_and_not_the_first_octet, "test_the_link_local_prefix_is_the_first_ten_bits_and_not_the_first_octet", 864);
  run_test(test_an_identifier_this_unit_cannot_lay_into_an_address_forms_none, "test_an_identifier_this_unit_cannot_lay_into_an_address_forms_none", 881);
  run_test(test_an_address_already_in_the_list_is_reported_rather_than_added_twice, "test_an_address_already_in_the_list_is_reported_rather_than_added_twice", 911);
  run_test(test_a_full_list_is_busy_for_a_link_local_address, "test_a_full_list_is_busy_for_a_link_local_address", 944);
  run_test(test_a_prefix_is_compared_over_the_bits_its_length_names, "test_a_prefix_is_compared_over_the_bits_its_length_names", 966);
  run_test(test_an_identifier_of_no_bits_forms_no_address, "test_an_identifier_of_no_bits_forms_no_address", 1006);
  run_test(test_the_address_entries_refuse_what_names_no_address, "test_the_address_entries_refuse_what_names_no_address", 1026);
  run_test(test_the_address_entries_refuse_an_uncleared_borrow, "test_the_address_entries_refuse_an_uncleared_borrow", 1055);
  run_test(test_an_advertisement_meeting_an_address_with_nothing_left_takes_the_two_hour_rule, "test_an_advertisement_meeting_an_address_with_nothing_left_takes_the_two_hour_rule", 1073);

  return UNITY_END();
}
