/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/icmp/icmp_in.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_uncleared_borrow_refuses_work(void);
extern void test_clear_reports_ok_and_zeroes_the_block(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_echo_request_is_answered_with_an_echo_reply(void);
extern void test_echo_reply_carries_the_data_entirely(void);
extern void test_echo_reply_checksum_verifies(void);
extern void test_echo_reply_source_is_the_specific_destination(void);
extern void test_echo_to_a_broadcast_destination_is_discarded(void);
extern void test_echo_to_a_multicast_destination_is_discarded(void);
extern void test_echo_reply_is_truncated_to_the_maximum_transmission_size(void);
extern void test_an_arriving_echo_reply_goes_to_the_user(void);
extern void test_a_bad_checksum_is_discarded(void);
extern void test_an_unknown_type_is_discarded(void);
extern void test_an_information_request_is_discarded(void);
extern void test_a_timestamp_request_is_discarded(void);
extern void test_a_message_shorter_than_the_common_header_is_discarded(void);
extern void test_an_echo_shorter_than_its_header_is_discarded(void);
extern void test_recv_refuses_a_datagram_the_internet_layer_would_discard(void);
extern void test_recv_refuses_a_null_datagram_and_a_null_out(void);
extern void test_recv_refuses_an_out_buffer_below_the_echo_header(void);
extern void test_destination_unreachable_demuxes_on_the_quoted_protocol(void);
extern void test_source_quench_time_exceeded_and_parameter_problem_reach_the_transport(void);
extern void test_a_redirect_reports_the_gateway(void);
extern void test_a_redirect_naming_an_off_link_gateway_is_discarded(void);
extern void test_a_redirect_naming_a_broadcast_or_multicast_gateway_is_discarded(void);
extern void test_an_accepted_redirect_reports_the_destination_it_names(void);
extern void test_an_error_without_a_whole_quoted_header_is_discarded(void);
extern void test_a_port_unreachable_is_built(void);
extern void test_an_error_quotes_the_header_and_eight_data_octets(void);
extern void test_an_error_checksum_verifies(void);
extern void test_an_error_goes_back_to_the_datagrams_source(void);
extern void test_a_parameter_problem_carries_the_pointer(void);
extern void test_no_error_about_an_icmp_error_message(void);
extern void test_an_error_about_an_icmp_query_is_allowed(void);
extern void test_no_error_about_a_limited_broadcast_destination(void);
extern void test_no_error_about_a_subnet_directed_broadcast_destination(void);
extern void test_no_error_about_a_multicast_destination(void);
extern void test_no_error_about_a_link_layer_broadcast(void);
extern void test_no_error_about_a_non_initial_fragment(void);
extern void test_an_error_about_the_first_fragment_is_allowed(void);
extern void test_no_error_about_a_zero_source(void);
extern void test_no_error_about_a_loopback_source(void);
extern void test_no_error_about_a_broadcast_source(void);
extern void test_no_error_about_a_multicast_source(void);
extern void test_no_error_about_a_class_e_source(void);
extern void test_a_host_does_not_originate_a_redirect(void);
extern void test_error_refuses_a_query_type(void);
extern void test_error_refuses_a_buffer_short_of_the_quote(void);
extern void test_error_refuses_a_datagram_the_internet_layer_would_discard(void);
extern void test_error_refuses_a_null_datagram_and_a_null_out(void);
extern void test_a_suppressed_error_never_becomes_ok_on_a_retry(void);
extern void test_originated_errors_are_rate_limited(void);
extern void test_source_quench_is_rate_limited(void);
extern void test_the_rate_limit_is_per_borrow(void);
extern void test_an_error_quotes_a_header_with_options_whole(void);
extern void test_a_built_error_repeats(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/icmp/test_icmp_in\\test_icmp_in.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 166);
  run_test(test_uncleared_borrow_refuses_work, "test_uncleared_borrow_refuses_work", 176);
  run_test(test_clear_reports_ok_and_zeroes_the_block, "test_clear_reports_ok_and_zeroes_the_block", 191);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 203);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 226);
  run_test(test_echo_request_is_answered_with_an_echo_reply, "test_echo_request_is_answered_with_an_echo_reply", 247);
  run_test(test_echo_reply_carries_the_data_entirely, "test_echo_reply_carries_the_data_entirely", 266);
  run_test(test_echo_reply_checksum_verifies, "test_echo_reply_checksum_verifies", 279);
  run_test(test_echo_reply_source_is_the_specific_destination, "test_echo_reply_source_is_the_specific_destination", 291);
  run_test(test_echo_to_a_broadcast_destination_is_discarded, "test_echo_to_a_broadcast_destination_is_discarded", 303);
  run_test(test_echo_to_a_multicast_destination_is_discarded, "test_echo_to_a_multicast_destination_is_discarded", 315);
  run_test(test_echo_reply_is_truncated_to_the_maximum_transmission_size, "test_echo_reply_is_truncated_to_the_maximum_transmission_size", 326);
  run_test(test_an_arriving_echo_reply_goes_to_the_user, "test_an_arriving_echo_reply_goes_to_the_user", 343);
  run_test(test_a_bad_checksum_is_discarded, "test_a_bad_checksum_is_discarded", 359);
  run_test(test_an_unknown_type_is_discarded, "test_an_unknown_type_is_discarded", 376);
  run_test(test_an_information_request_is_discarded, "test_an_information_request_is_discarded", 388);
  run_test(test_a_timestamp_request_is_discarded, "test_a_timestamp_request_is_discarded", 401);
  run_test(test_a_message_shorter_than_the_common_header_is_discarded, "test_a_message_shorter_than_the_common_header_is_discarded", 415);
  run_test(test_an_echo_shorter_than_its_header_is_discarded, "test_an_echo_shorter_than_its_header_is_discarded", 426);
  run_test(test_recv_refuses_a_datagram_the_internet_layer_would_discard, "test_recv_refuses_a_datagram_the_internet_layer_would_discard", 441);
  run_test(test_recv_refuses_a_null_datagram_and_a_null_out, "test_recv_refuses_a_null_datagram_and_a_null_out", 451);
  run_test(test_recv_refuses_an_out_buffer_below_the_echo_header, "test_recv_refuses_an_out_buffer_below_the_echo_header", 466);
  run_test(test_destination_unreachable_demuxes_on_the_quoted_protocol, "test_destination_unreachable_demuxes_on_the_quoted_protocol", 480);
  run_test(test_source_quench_time_exceeded_and_parameter_problem_reach_the_transport, "test_source_quench_time_exceeded_and_parameter_problem_reach_the_transport", 496);
  run_test(test_a_redirect_reports_the_gateway, "test_a_redirect_reports_the_gateway", 515);
  run_test(test_a_redirect_naming_an_off_link_gateway_is_discarded, "test_a_redirect_naming_an_off_link_gateway_is_discarded", 531);
  run_test(test_a_redirect_naming_a_broadcast_or_multicast_gateway_is_discarded, "test_a_redirect_naming_a_broadcast_or_multicast_gateway_is_discarded", 549);
  run_test(test_an_accepted_redirect_reports_the_destination_it_names, "test_an_accepted_redirect_reports_the_destination_it_names", 569);
  run_test(test_an_error_without_a_whole_quoted_header_is_discarded, "test_an_error_without_a_whole_quoted_header_is_discarded", 585);
  run_test(test_a_port_unreachable_is_built, "test_a_port_unreachable_is_built", 601);
  run_test(test_an_error_quotes_the_header_and_eight_data_octets, "test_an_error_quotes_the_header_and_eight_data_octets", 617);
  run_test(test_an_error_checksum_verifies, "test_an_error_checksum_verifies", 631);
  run_test(test_an_error_goes_back_to_the_datagrams_source, "test_an_error_goes_back_to_the_datagrams_source", 640);
  run_test(test_a_parameter_problem_carries_the_pointer, "test_a_parameter_problem_carries_the_pointer", 651);
  run_test(test_no_error_about_an_icmp_error_message, "test_no_error_about_an_icmp_error_message", 664);
  run_test(test_an_error_about_an_icmp_query_is_allowed, "test_an_error_about_an_icmp_query_is_allowed", 676);
  run_test(test_no_error_about_a_limited_broadcast_destination, "test_no_error_about_a_limited_broadcast_destination", 686);
  run_test(test_no_error_about_a_subnet_directed_broadcast_destination, "test_no_error_about_a_subnet_directed_broadcast_destination", 696);
  run_test(test_no_error_about_a_multicast_destination, "test_no_error_about_a_multicast_destination", 705);
  run_test(test_no_error_about_a_link_layer_broadcast, "test_no_error_about_a_link_layer_broadcast", 716);
  run_test(test_no_error_about_a_non_initial_fragment, "test_no_error_about_a_non_initial_fragment", 728);
  run_test(test_an_error_about_the_first_fragment_is_allowed, "test_an_error_about_the_first_fragment_is_allowed", 736);
  run_test(test_no_error_about_a_zero_source, "test_no_error_about_a_zero_source", 745);
  run_test(test_no_error_about_a_loopback_source, "test_no_error_about_a_loopback_source", 754);
  run_test(test_no_error_about_a_broadcast_source, "test_no_error_about_a_broadcast_source", 763);
  run_test(test_no_error_about_a_multicast_source, "test_no_error_about_a_multicast_source", 772);
  run_test(test_no_error_about_a_class_e_source, "test_no_error_about_a_class_e_source", 781);
  run_test(test_a_host_does_not_originate_a_redirect, "test_a_host_does_not_originate_a_redirect", 791);
  run_test(test_error_refuses_a_query_type, "test_error_refuses_a_query_type", 802);
  run_test(test_error_refuses_a_buffer_short_of_the_quote, "test_error_refuses_a_buffer_short_of_the_quote", 813);
  run_test(test_error_refuses_a_datagram_the_internet_layer_would_discard, "test_error_refuses_a_datagram_the_internet_layer_would_discard", 823);
  run_test(test_error_refuses_a_null_datagram_and_a_null_out, "test_error_refuses_a_null_datagram_and_a_null_out", 832);
  run_test(test_a_suppressed_error_never_becomes_ok_on_a_retry, "test_a_suppressed_error_never_becomes_ok_on_a_retry", 848);
  run_test(test_originated_errors_are_rate_limited, "test_originated_errors_are_rate_limited", 868);
  run_test(test_source_quench_is_rate_limited, "test_source_quench_is_rate_limited", 911);
  run_test(test_the_rate_limit_is_per_borrow, "test_the_rate_limit_is_per_borrow", 928);
  run_test(test_an_error_quotes_a_header_with_options_whole, "test_an_error_quotes_a_header_with_options_whole", 948);
  run_test(test_a_built_error_repeats, "test_a_built_error_repeats", 978);

  return UNITY_END();
}
