/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/nd/rdnss.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_clear_on_one_borrow_leaves_the_other_untouched(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_every_published_offset_is_aligned(void);
extern void test_the_io_macro_reaches_the_operand_block(void);
extern void test_clear_reports_ok(void);
extern void test_clear_zeroes_the_list(void);
extern void test_clear_zeroes_the_context_apart_from_the_mark(void);
extern void test_clear_leaves_the_operand_block_alone(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_option_in_refuses_a_null_option(void);
extern void test_option_in_refuses_fewer_octets_than_the_header(void);
extern void test_another_option_type_is_discarded(void);
extern void test_a_length_below_three_is_discarded(void);
extern void test_an_even_length_is_discarded(void);
extern void test_an_option_longer_than_the_octets_available_is_discarded(void);
extern void test_a_multicast_address_discards_the_whole_option(void);
extern void test_the_unspecified_address_discards_the_option(void);
extern void test_the_address_count_comes_from_the_length_field(void);
extern void test_the_list_holds_at_least_three(void);
extern void test_the_expiration_is_the_lifetime_plus_the_current_time(void);
extern void test_an_infinite_lifetime_never_expires(void);
extern void test_a_repeated_address_updates_the_expiration(void);
extern void test_a_zero_lifetime_deletes_a_held_address(void);
extern void test_a_zero_lifetime_registers_nothing_for_an_address_not_held(void);
extern void test_the_option_order_is_the_list_order(void);
extern void test_a_new_address_is_inserted_at_the_head(void);
extern void test_a_full_list_evicts_the_entry_that_expires_first(void);
extern void test_eviction_prefers_a_finite_entry_over_an_infinite_one(void);
extern void test_an_expired_entry_is_deleted(void);
extern void test_an_entry_stamped_before_the_clock_wraps_still_expires(void);
extern void test_a_lifetime_past_the_thirty_two_bit_millisecond_range_still_expires(void);
extern void test_a_tick_reports_one_expiry_per_call(void);
extern void test_a_tick_with_nothing_expired_is_busy(void);
extern void test_an_expiry_closes_the_gap(void);
extern void test_get_refuses_a_slot_that_holds_nothing(void);
extern void test_find_refuses_an_address_that_is_not_held(void);
extern void test_remove_deletes_one_entry(void);
extern void test_remove_refuses_an_address_that_is_not_held(void);
extern void test_the_address_entries_refuse_what_names_no_address(void);
extern void test_the_eviction_takes_the_server_with_the_least_left_on_it(void);
extern void test_a_server_already_in_the_list_can_be_updated_to_infinity(void);
extern void test_the_place_the_next_address_goes_follows_an_eviction_in_front_of_it(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/unit/nd/test_rdnss/test_rdnss.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 149);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 157);
  run_test(test_clear_on_one_borrow_leaves_the_other_untouched, "test_clear_on_one_borrow_leaves_the_other_untouched", 173);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 185);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 201);
  run_test(test_every_published_offset_is_aligned, "test_every_published_offset_is_aligned", 211);
  run_test(test_the_io_macro_reaches_the_operand_block, "test_the_io_macro_reaches_the_operand_block", 217);
  run_test(test_clear_reports_ok, "test_clear_reports_ok", 225);
  run_test(test_clear_zeroes_the_list, "test_clear_zeroes_the_list", 231);
  run_test(test_clear_zeroes_the_context_apart_from_the_mark, "test_clear_zeroes_the_context_apart_from_the_mark", 241);
  run_test(test_clear_leaves_the_operand_block_alone, "test_clear_leaves_the_operand_block_alone", 256);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 267);
  run_test(test_option_in_refuses_a_null_option, "test_option_in_refuses_a_null_option", 282);
  run_test(test_option_in_refuses_fewer_octets_than_the_header, "test_option_in_refuses_fewer_octets_than_the_header", 292);
  run_test(test_another_option_type_is_discarded, "test_another_option_type_is_discarded", 302);
  run_test(test_a_length_below_three_is_discarded, "test_a_length_below_three_is_discarded", 315);
  run_test(test_an_even_length_is_discarded, "test_an_even_length_is_discarded", 327);
  run_test(test_an_option_longer_than_the_octets_available_is_discarded, "test_an_option_longer_than_the_octets_available_is_discarded", 339);
  run_test(test_a_multicast_address_discards_the_whole_option, "test_a_multicast_address_discards_the_whole_option", 352);
  run_test(test_the_unspecified_address_discards_the_option, "test_the_unspecified_address_discards_the_option", 362);
  run_test(test_the_address_count_comes_from_the_length_field, "test_the_address_count_comes_from_the_length_field", 372);
  run_test(test_the_list_holds_at_least_three, "test_the_list_holds_at_least_three", 383);
  run_test(test_the_expiration_is_the_lifetime_plus_the_current_time, "test_the_expiration_is_the_lifetime_plus_the_current_time", 393);
  run_test(test_an_infinite_lifetime_never_expires, "test_an_infinite_lifetime_never_expires", 405);
  run_test(test_a_repeated_address_updates_the_expiration, "test_a_repeated_address_updates_the_expiration", 421);
  run_test(test_a_zero_lifetime_deletes_a_held_address, "test_a_zero_lifetime_deletes_a_held_address", 436);
  run_test(test_a_zero_lifetime_registers_nothing_for_an_address_not_held, "test_a_zero_lifetime_registers_nothing_for_an_address_not_held", 452);
  run_test(test_the_option_order_is_the_list_order, "test_the_option_order_is_the_list_order", 465);
  run_test(test_a_new_address_is_inserted_at_the_head, "test_a_new_address_is_inserted_at_the_head", 481);
  run_test(test_a_full_list_evicts_the_entry_that_expires_first, "test_a_full_list_evicts_the_entry_that_expires_first", 501);
  run_test(test_eviction_prefers_a_finite_entry_over_an_infinite_one, "test_eviction_prefers_a_finite_entry_over_an_infinite_one", 525);
  run_test(test_an_expired_entry_is_deleted, "test_an_expired_entry_is_deleted", 543);
  run_test(test_an_entry_stamped_before_the_clock_wraps_still_expires, "test_an_entry_stamped_before_the_clock_wraps_still_expires", 570);
  run_test(test_a_lifetime_past_the_thirty_two_bit_millisecond_range_still_expires, "test_a_lifetime_past_the_thirty_two_bit_millisecond_range_still_expires", 595);
  run_test(test_a_tick_reports_one_expiry_per_call, "test_a_tick_reports_one_expiry_per_call", 615);
  run_test(test_a_tick_with_nothing_expired_is_busy, "test_a_tick_with_nothing_expired_is_busy", 632);
  run_test(test_an_expiry_closes_the_gap, "test_an_expiry_closes_the_gap", 642);
  run_test(test_get_refuses_a_slot_that_holds_nothing, "test_get_refuses_a_slot_that_holds_nothing", 666);
  run_test(test_find_refuses_an_address_that_is_not_held, "test_find_refuses_an_address_that_is_not_held", 675);
  run_test(test_remove_deletes_one_entry, "test_remove_deletes_one_entry", 685);
  run_test(test_remove_refuses_an_address_that_is_not_held, "test_remove_refuses_an_address_that_is_not_held", 698);
  run_test(test_the_address_entries_refuse_what_names_no_address, "test_the_address_entries_refuse_what_names_no_address", 710);
  run_test(test_the_eviction_takes_the_server_with_the_least_left_on_it, "test_the_eviction_takes_the_server_with_the_least_left_on_it", 735);
  run_test(test_a_server_already_in_the_list_can_be_updated_to_infinity, "test_a_server_already_in_the_list_can_be_updated_to_infinity", 769);
  run_test(test_the_place_the_next_address_goes_follows_an_eviction_in_front_of_it, "test_the_place_the_next_address_goes_follows_an_eviction_in_front_of_it", 790);

  return UNITY_END();
}
