name=idemIP
version=0.1.0
author=Douglas Quigg (dstroy0) <dquigg123@gmail.com>
maintainer=Douglas Quigg (dstroy0) <dquigg123@gmail.com>
sentence=Zero-heap, asynchronous TCP/IP stack with a fully deterministic memory footprint. Thread safe design.
paragraph=Zero-heap, asynchronous TCP/IP stack with a fully deterministic memory footprint. Thread safe design. Designed for embedded targets (bare metal or with OS). Provides an intuitive API. Ideal for resource-constrained environments where memory management is critical.
category=Communication
url=https://github.com/dstroy0/idemIP
architectures=*
depends=
