/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/ip/ip6_select.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_uncleared_borrow_refuses_work(void);
extern void test_sec2_1_clear_loads_the_nine_default_rows(void);
extern void test_sec2_1_default_precedences_and_labels(void);
extern void test_sec2_1_lookup_takes_the_longest_matching_prefix(void);
extern void test_sec2_1_a_zone_qualified_row_answers_only_its_own_zone(void);
extern void test_sec2_1_a_row_can_be_reconfigured(void);
extern void test_a_full_policy_table_is_err_not_busy(void);
extern void test_sec2_2_worked_common_prefix_len(void);
extern void test_common_prefix_len_counts_the_leading_bits(void);
extern void test_sec3_2_ipv4_scopes(void);
extern void test_sec3_1_and_3_4_ipv6_scopes(void);
extern void test_sec4_refuses_multicast_and_the_unspecified_address(void);
extern void test_sec4_link_local_destination_keeps_to_the_outgoing_interface(void);
extern void test_no_candidate_is_ok_with_source_undefined(void);
extern void test_a_full_candidate_set_is_err_not_busy(void);
extern void test_rule1_prefer_same_address(void);
extern void test_rule2_prefer_appropriate_scope_for_a_global_destination(void);
extern void test_rule2_prefer_appropriate_scope_for_a_multicast_destination(void);
extern void test_rule2_beats_rule3_for_a_link_local_destination(void);
extern void test_rule3_avoid_deprecated_addresses(void);
extern void test_rule4_prefer_home_addresses(void);
extern void test_rule4_prefers_an_address_that_is_both(void);
extern void test_rule5_prefer_the_outgoing_interface(void);
extern void test_rule5_5_prefer_a_prefix_from_the_next_hop(void);
extern void test_rule6_prefer_matching_label(void);
extern void test_rule7_prefer_temporary_addresses(void);
extern void test_rule8_use_longest_matching_prefix(void);
extern void test_a_tie_keeps_the_candidate_that_was_added_first(void);
extern void test_sec10_2_first_prefer_matching_scope(void);
extern void test_sec10_2_second_matching_scope_reverses_the_list(void);
extern void test_sec10_2_third_prefer_higher_precedence(void);
extern void test_sec10_2_fourth_prefer_smaller_scope(void);
extern void test_sec10_2_fifth_prefer_home_address(void);
extern void test_dest_rule1_avoid_unusable_destinations(void);
extern void test_dest_rule1_ties_and_rule2_breaks_it(void);
extern void test_dest_rule3_avoids_a_deprecated_source(void);
extern void test_dest_rule5_prefers_a_matching_label(void);
extern void test_sec4_a_site_local_destination_only_takes_a_source_from_its_own_site(void);
extern void test_dest_rule7_prefer_native_transport(void);
extern void test_dest_rule9_use_longest_matching_prefix(void);
extern void test_dest_rule10_leaves_the_order_unchanged(void);
extern void test_a_destination_with_no_source_sorts_last(void);
extern void test_dest_at_refuses_before_a_sort_and_past_the_end(void);
extern void test_adding_after_a_sort_invalidates_it(void);
extern void test_no_entry_ever_reports_busy(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/ip/test_ip6_select\\test_ip6_select.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 204);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 220);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 249);
  run_test(test_uncleared_borrow_refuses_work, "test_uncleared_borrow_refuses_work", 272);
  run_test(test_sec2_1_clear_loads_the_nine_default_rows, "test_sec2_1_clear_loads_the_nine_default_rows", 306);
  run_test(test_sec2_1_default_precedences_and_labels, "test_sec2_1_default_precedences_and_labels", 314);
  run_test(test_sec2_1_lookup_takes_the_longest_matching_prefix, "test_sec2_1_lookup_takes_the_longest_matching_prefix", 354);
  run_test(test_sec2_1_a_zone_qualified_row_answers_only_its_own_zone, "test_sec2_1_a_zone_qualified_row_answers_only_its_own_zone", 374);
  run_test(test_sec2_1_a_row_can_be_reconfigured, "test_sec2_1_a_row_can_be_reconfigured", 404);
  run_test(test_a_full_policy_table_is_err_not_busy, "test_a_full_policy_table_is_err_not_busy", 423);
  run_test(test_sec2_2_worked_common_prefix_len, "test_sec2_2_worked_common_prefix_len", 451);
  run_test(test_common_prefix_len_counts_the_leading_bits, "test_common_prefix_len_counts_the_leading_bits", 461);
  run_test(test_sec3_2_ipv4_scopes, "test_sec3_2_ipv4_scopes", 484);
  run_test(test_sec3_1_and_3_4_ipv6_scopes, "test_sec3_1_and_3_4_ipv6_scopes", 509);
  run_test(test_sec4_refuses_multicast_and_the_unspecified_address, "test_sec4_refuses_multicast_and_the_unspecified_address", 533);
  run_test(test_sec4_link_local_destination_keeps_to_the_outgoing_interface, "test_sec4_link_local_destination_keeps_to_the_outgoing_interface", 549);
  run_test(test_no_candidate_is_ok_with_source_undefined, "test_no_candidate_is_ok_with_source_undefined", 567);
  run_test(test_a_full_candidate_set_is_err_not_busy, "test_a_full_candidate_set_is_err_not_busy", 578);
  run_test(test_rule1_prefer_same_address, "test_rule1_prefer_same_address", 598);
  run_test(test_rule2_prefer_appropriate_scope_for_a_global_destination, "test_rule2_prefer_appropriate_scope_for_a_global_destination", 611);
  run_test(test_rule2_prefer_appropriate_scope_for_a_multicast_destination, "test_rule2_prefer_appropriate_scope_for_a_multicast_destination", 624);
  run_test(test_rule2_beats_rule3_for_a_link_local_destination, "test_rule2_beats_rule3_for_a_link_local_destination", 637);
  run_test(test_rule3_avoid_deprecated_addresses, "test_rule3_avoid_deprecated_addresses", 649);
  run_test(test_rule4_prefer_home_addresses, "test_rule4_prefer_home_addresses", 662);
  run_test(test_rule4_prefers_an_address_that_is_both, "test_rule4_prefers_an_address_that_is_both", 674);
  run_test(test_rule5_prefer_the_outgoing_interface, "test_rule5_prefer_the_outgoing_interface", 686);
  run_test(test_rule5_5_prefer_a_prefix_from_the_next_hop, "test_rule5_5_prefer_a_prefix_from_the_next_hop", 698);
  run_test(test_rule6_prefer_matching_label, "test_rule6_prefer_matching_label", 712);
  run_test(test_rule7_prefer_temporary_addresses, "test_rule7_prefer_temporary_addresses", 725);
  run_test(test_rule8_use_longest_matching_prefix, "test_rule8_use_longest_matching_prefix", 738);
  run_test(test_a_tie_keeps_the_candidate_that_was_added_first, "test_a_tie_keeps_the_candidate_that_was_added_first", 750);
  run_test(test_sec10_2_first_prefer_matching_scope, "test_sec10_2_first_prefer_matching_scope", 770);
  run_test(test_sec10_2_second_matching_scope_reverses_the_list, "test_sec10_2_second_matching_scope_reverses_the_list", 794);
  run_test(test_sec10_2_third_prefer_higher_precedence, "test_sec10_2_third_prefer_higher_precedence", 816);
  run_test(test_sec10_2_fourth_prefer_smaller_scope, "test_sec10_2_fourth_prefer_smaller_scope", 839);
  run_test(test_sec10_2_fifth_prefer_home_address, "test_sec10_2_fifth_prefer_home_address", 860);
  run_test(test_dest_rule1_avoid_unusable_destinations, "test_dest_rule1_avoid_unusable_destinations", 881);
  run_test(test_dest_rule1_ties_and_rule2_breaks_it, "test_dest_rule1_ties_and_rule2_breaks_it", 902);
  run_test(test_dest_rule3_avoids_a_deprecated_source, "test_dest_rule3_avoids_a_deprecated_source", 921);
  run_test(test_dest_rule5_prefers_a_matching_label, "test_dest_rule5_prefers_a_matching_label", 943);
  run_test(test_sec4_a_site_local_destination_only_takes_a_source_from_its_own_site, "test_sec4_a_site_local_destination_only_takes_a_source_from_its_own_site", 980);
  run_test(test_dest_rule7_prefer_native_transport, "test_dest_rule7_prefer_native_transport", 1034);
  run_test(test_dest_rule9_use_longest_matching_prefix, "test_dest_rule9_use_longest_matching_prefix", 1052);
  run_test(test_dest_rule10_leaves_the_order_unchanged, "test_dest_rule10_leaves_the_order_unchanged", 1070);
  run_test(test_a_destination_with_no_source_sorts_last, "test_a_destination_with_no_source_sorts_last", 1091);
  run_test(test_dest_at_refuses_before_a_sort_and_past_the_end, "test_dest_at_refuses_before_a_sort_and_past_the_end", 1115);
  run_test(test_adding_after_a_sort_invalidates_it, "test_adding_after_a_sort_invalidates_it", 1135);
  run_test(test_no_entry_ever_reports_busy, "test_no_entry_ever_reports_busy", 1151);

  return UNITY_END();
}
