/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/ip/ip4_addr.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_uncleared_borrow_refuses_work(void);
extern void test_clear_admits_the_borrow(void);
extern void test_rfc791_class_a_is_the_leading_zero_bit(void);
extern void test_rfc791_class_b_is_the_leading_10_bits(void);
extern void test_rfc791_class_c_is_the_leading_110_bits(void);
extern void test_rfc1122_splits_the_791_escape_into_class_d_and_e(void);
extern void test_rfc1112_class_d_spans_224_through_239(void);
extern void test_limited_broadcast_is_its_own_type_inside_class_e(void);
extern void test_case_a_and_case_b_are_separate(void);
extern void test_case_g_loopback_is_127_slash_8(void);
extern void test_rfc3927_link_local_is_the_whole_169_254_slash_16(void);
extern void test_rfc3927_link_local_broadcast(void);
extern void test_rfc919_directed_broadcast_of_net_36(void);
extern void test_limited_broadcast_is_a_broadcast_under_every_mask(void);
extern void test_match_reports_network_host_and_prefix_len(void);
extern void test_match_reports_an_address_off_the_subnet(void);
extern void test_a_slash_32_has_no_directed_broadcast(void);
extern void test_a_slash_31_has_two_host_addresses_and_no_directed_broadcast(void);
extern void test_a_slash_0_covers_everything(void);
extern void test_a_non_contiguous_mask_is_reported_not_refused(void);
extern void test_rfc1112_map_places_the_low_23_bits_under_01_00_5e(void);
extern void test_rfc1112_map_keeps_the_24th_bit_clear(void);
extern void test_rfc1112_map_aliases_groups_that_differ_above_23_bits(void);
extern void test_map_refuses_an_address_outside_class_d(void);
extern void test_no_entry_ever_reports_busy(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/ip/test_ip4_addr\\test_ip4_addr.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 75);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 86);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 104);
  run_test(test_uncleared_borrow_refuses_work, "test_uncleared_borrow_refuses_work", 123);
  run_test(test_clear_admits_the_borrow, "test_clear_admits_the_borrow", 133);
  run_test(test_rfc791_class_a_is_the_leading_zero_bit, "test_rfc791_class_a_is_the_leading_zero_bit", 145);
  run_test(test_rfc791_class_b_is_the_leading_10_bits, "test_rfc791_class_b_is_the_leading_10_bits", 156);
  run_test(test_rfc791_class_c_is_the_leading_110_bits, "test_rfc791_class_c_is_the_leading_110_bits", 165);
  run_test(test_rfc1122_splits_the_791_escape_into_class_d_and_e, "test_rfc1122_splits_the_791_escape_into_class_d_and_e", 175);
  run_test(test_rfc1112_class_d_spans_224_through_239, "test_rfc1112_class_d_spans_224_through_239", 190);
  run_test(test_limited_broadcast_is_its_own_type_inside_class_e, "test_limited_broadcast_is_its_own_type_inside_class_e", 209);
  run_test(test_case_a_and_case_b_are_separate, "test_case_a_and_case_b_are_separate", 218);
  run_test(test_case_g_loopback_is_127_slash_8, "test_case_g_loopback_is_127_slash_8", 230);
  run_test(test_rfc3927_link_local_is_the_whole_169_254_slash_16, "test_rfc3927_link_local_is_the_whole_169_254_slash_16", 249);
  run_test(test_rfc3927_link_local_broadcast, "test_rfc3927_link_local_broadcast", 266);
  run_test(test_rfc919_directed_broadcast_of_net_36, "test_rfc919_directed_broadcast_of_net_36", 281);
  run_test(test_limited_broadcast_is_a_broadcast_under_every_mask, "test_limited_broadcast_is_a_broadcast_under_every_mask", 293);
  run_test(test_match_reports_network_host_and_prefix_len, "test_match_reports_network_host_and_prefix_len", 301);
  run_test(test_match_reports_an_address_off_the_subnet, "test_match_reports_an_address_off_the_subnet", 314);
  run_test(test_a_slash_32_has_no_directed_broadcast, "test_a_slash_32_has_no_directed_broadcast", 324);
  run_test(test_a_slash_31_has_two_host_addresses_and_no_directed_broadcast, "test_a_slash_31_has_two_host_addresses_and_no_directed_broadcast", 336);
  run_test(test_a_slash_0_covers_everything, "test_a_slash_0_covers_everything", 360);
  run_test(test_a_non_contiguous_mask_is_reported_not_refused, "test_a_non_contiguous_mask_is_reported_not_refused", 372);
  run_test(test_rfc1112_map_places_the_low_23_bits_under_01_00_5e, "test_rfc1112_map_places_the_low_23_bits_under_01_00_5e", 387);
  run_test(test_rfc1112_map_keeps_the_24th_bit_clear, "test_rfc1112_map_keeps_the_24th_bit_clear", 397);
  run_test(test_rfc1112_map_aliases_groups_that_differ_above_23_bits, "test_rfc1112_map_aliases_groups_that_differ_above_23_bits", 411);
  run_test(test_map_refuses_an_address_outside_class_d, "test_map_refuses_an_address_outside_class_d", 431);
  run_test(test_no_entry_ever_reports_busy, "test_no_entry_ever_reports_busy", 450);

  return UNITY_END();
}
