/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/core/dispatch.h"
#include "src/arp/arp.h"
#include "src/icmp/icmp.h"
#include "src/ip/ipv4.h"
#include "src/ip/ipv6.h"
#include "src/ip/pseudo.h"
#include "src/tcp/tcp.h"
#include "src/udp/udp.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_every_entry_refuses_an_uncleared_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_the_published_offsets_are_ordered_and_fit(void);
extern void test_input_refuses_a_null_frame_and_a_bad_interface(void);
extern void test_every_arriving_frame_counts_its_octets(void);
extern void test_a_short_frame_is_an_error_not_a_discard(void);
extern void test_an_unhandled_ethertype_counts_unknown_protos(void);
extern void test_an_untagged_interface_accepts_an_untagged_frame(void);
extern void test_an_untagged_interface_accepts_a_tagged_frame(void);
extern void test_a_tagged_interface_accepts_its_own_vid(void);
extern void test_a_tagged_interface_discards_another_vid(void);
extern void test_a_policy_drop_records_the_offending_vid(void);
extern void test_a_discarded_priority_tagged_frame_records_zero_not_the_sentinel(void);
extern void test_the_reserved_vid_is_an_error_not_a_policy_discard(void);
extern void test_the_reserved_vid_is_refused_on_an_untagged_interface(void);
extern void test_if_bind_refuses_a_membership_outside_the_usable_range(void);
extern void test_if_bind_and_if_get_refuse_an_index_past_the_table(void);
extern void test_clear_sets_every_row_to_the_sentinel(void);
extern void test_a_bad_ipv4_checksum_is_a_header_error(void);
extern void test_a_datagram_for_somewhere_else_is_reported_for_forwarding(void);
extern void test_the_limited_broadcast_is_local(void);
extern void test_the_directed_broadcast_of_our_subnet_is_local(void);
extern void test_a_group_we_never_joined_is_an_address_error(void);
extern void test_a_bound_udp_port_takes_the_datagram(void);
extern void test_an_unbound_udp_port_counts_no_ports(void);
extern void test_a_datagram_whose_source_address_is_barred_is_discarded(void);
extern void test_the_unspecified_source_an_address_request_carries_still_arrives(void);
extern void test_an_igmp_query_with_a_good_checksum_is_processed(void);
extern void test_an_igmp_message_longer_than_eight_octets_sums_over_the_whole_payload(void);
extern void test_an_unrecognized_igmp_type_is_silently_ignored(void);
extern void test_an_rfc_1042_encapsulated_datagram_is_received(void);
extern void test_an_igmp_query_with_a_bad_checksum_is_discarded(void);
extern void test_the_all_hosts_group_is_this_node_s_whether_or_not_it_joined_one(void);
extern void test_an_igmp_report_with_a_bad_checksum_is_discarded(void);
extern void test_a_bad_udp_checksum_is_discarded(void);
extern void test_a_zero_udp_checksum_is_accepted_over_ipv4(void);
extern void test_a_udp_length_past_the_ip_payload_is_an_error(void);
extern void test_a_broadcast_delivery_counts_non_unicast(void);
extern void test_an_icmp_echo_counts_itself_by_message_and_by_type(void);
extern void test_the_echo_reply_this_path_builds_takes_its_two_out_counters(void);
extern void test_an_icmp_message_with_a_bad_checksum_counts_as_an_error(void);
extern void test_an_icmp_message_of_unknown_type_is_discarded(void);
extern void test_an_icmp_message_too_short_for_its_type_is_an_error(void);
extern void test_an_unclaimed_ip_protocol_counts_unknown_protos(void);
extern void test_an_unclaimed_ipv6_next_header_counts_unknown_protos(void);
extern void test_a_raw_ipv6_binding_with_ipv6_checksum_verifies_the_received_checksum(void);
extern void test_a_raw_binding_takes_an_unclaimed_protocol(void);
extern void test_an_echo_request_builds_a_reply(void);
extern void test_a_reply_with_no_transmit_buffer_is_busy(void);
extern void test_an_arp_request_for_us_builds_a_reply(void);
extern void test_an_arp_request_for_someone_else_neither_answers_nor_is_learned(void);
extern void test_an_arp_request_for_us_is_learned(void);
extern void test_an_arp_reply_on_a_tagged_interface_carries_the_tag(void);
extern void test_an_arp_reply_with_no_transmit_buffer_is_busy(void);
extern void test_a_short_arp_packet_is_an_error(void);
extern void test_a_fragment_with_no_descriptor_is_discarded(void);
extern void test_a_fragment_the_reassembler_kept_pins_its_descriptor(void);
extern void test_a_fragment_the_reassembler_refuses_counts_a_reassembly_failure(void);
extern void test_the_last_fragment_completes_the_datagram(void);
extern void test_an_ipv6_packet_for_our_address_is_delivered(void);
extern void test_a_fragmented_neighbor_discovery_message_is_ignored(void);
extern void test_a_fragmented_echo_request_is_not_ignored(void);
extern void test_a_routing_header_with_segments_left_is_discarded(void);
extern void test_a_routing_header_with_no_segments_left_is_ignored(void);
extern void test_an_option_the_node_refuses_discards_the_packet(void);
extern void test_an_unrecognized_option_that_says_skip_is_skipped(void);
extern void test_an_icmpv6_message_of_unknown_type_is_discarded(void);
extern void test_the_icmpv6_echo_reply_this_path_builds_takes_its_two_out_counters(void);
extern void test_a_zero_udp_checksum_is_discarded_over_ipv6(void);
extern void test_a_bad_udp_checksum_is_discarded_over_ipv6(void);
extern void test_an_ipv6_packet_for_somewhere_else_is_reported_for_forwarding(void);
extern void test_an_ipv6_payload_length_past_the_frame_is_a_truncated_packet(void);
extern void test_an_ipv6_version_that_is_not_six_is_a_header_error(void);
extern void test_a_frame_too_short_for_the_ipv6_header_is_a_truncated_packet(void);
extern void test_a_multicast_destination_counts_an_ipv6_multicast_arrival(void);
extern void test_the_solicited_node_address_of_our_own_is_local(void);
extern void test_a_neighbor_solicitation_reaches_the_neighbor_discovery_module(void);
extern void test_a_neighbor_advertisement_reaches_the_neighbor_discovery_module(void);
extern void test_a_router_advertisement_carrying_a_prefix_option_reaches_the_module(void);
extern void test_an_mld_query_reaches_the_group_module(void);
extern void test_every_neighbor_discovery_and_listener_type_takes_its_own_rfc_2466_counter(void);
extern void test_a_packet_too_big_takes_the_rfc_2466_counter_of_its_own(void);
extern void test_a_prohibited_destination_unreachable_counts_under_both_its_counters(void);
extern void test_a_destination_unreachable_at_another_code_is_not_an_admin_prohibition(void);
extern void test_a_neighbor_solicitation_with_a_bad_checksum_is_discarded(void);
extern void test_a_neighbor_solicitation_without_its_target_address_is_discarded(void);
extern void test_an_icmpv6_message_too_short_for_its_type_is_an_error(void);
extern void test_a_neighbor_solicitation_from_off_link_is_discarded(void);
extern void test_a_router_advertisement_from_off_link_is_discarded(void);
extern void test_a_neighbor_solicitation_with_a_nonzero_code_is_discarded(void);
extern void test_an_nd_option_of_length_zero_discards_the_packet(void);
extern void test_the_all_nodes_address_identifies_this_host(void);
extern void test_the_interface_local_all_nodes_address_identifies_this_host(void);
extern void test_a_multicast_group_this_node_never_joined_is_not_local(void);
extern void test_a_unicast_address_that_is_not_ours_is_still_forwarded(void);
extern void test_a_multicast_group_this_node_joined_is_local(void);
extern void test_an_nd_option_running_past_the_message_discards_the_packet(void);
extern void test_an_ipv6_fragment_the_reassembler_kept_pins_its_descriptor(void);
extern void test_the_last_ipv6_fragment_completes_the_datagram(void);
extern void test_an_ipv6_fragment_with_no_descriptor_is_discarded(void);
extern void test_an_ipv6_fragment_the_reassembler_refuses_counts_a_reassembly_failure(void);
extern void test_a_bare_rst_at_a_listener_creates_no_tcb(void);
extern void test_a_syn_past_the_listeners_backlog_takes_no_connection(void);
extern void test_a_bare_ack_at_a_listener_resets_without_a_passive_open(void);
extern void test_a_syn_at_a_listener_is_the_one_passive_open(void);
extern void test_a_reset_sent_for_a_segment_with_no_tcb_is_counted(void);
extern void test_tcp_in_segs_counts_a_segment_shorter_than_the_header(void);
extern void test_a_segment_with_no_tcb_reaches_the_closed_state(void);
extern void test_a_syn_to_a_listener_creates_the_connection(void);
extern void test_the_second_segment_finds_the_connection(void);
extern void test_an_ordinary_acknowledgment_is_aggregated_and_not_reported(void);
extern void test_two_segments_earn_one_acknowledgment(void);
extern void test_an_ack_flush_with_nothing_owed_is_busy(void);
extern void test_a_segment_ahead_of_the_window_is_held(void);
extern void test_a_held_segment_waits_until_rcv_nxt_reaches_it(void);
extern void test_a_held_segment_is_redelivered_once_the_gap_is_filled(void);
extern void test_a_redelivery_owes_the_aggregate_acknowledgment(void);
extern void test_tcp_deliver_refuses_a_pcb_past_the_table(void);
extern void test_a_short_tcp_segment_is_an_error(void);
extern void test_a_challenge_acknowledgment_is_not_aggregated(void);
extern void test_a_udp_lite_datagram_reaches_a_lite_binding(void);
extern void test_a_udp_lite_datagram_with_an_illegal_coverage_is_discarded(void);
extern void test_a_udp_lite_datagram_with_a_bad_checksum_is_refused_as_a_checksum_fault(void);
extern void test_a_frame_with_no_vlan_borrow_is_refused(void);
extern void test_an_ipv4_frame_with_an_unbound_unit_is_refused(void);
extern void test_an_ipv6_frame_with_an_unbound_unit_is_refused(void);
extern void test_a_udp_datagram_with_an_unbound_unit_is_refused(void);
extern void test_a_tcp_segment_with_an_unbound_unit_is_refused(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/core/test_dispatch\\test_dispatch.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 446);
  run_test(test_every_entry_refuses_an_uncleared_borrow, "test_every_entry_refuses_an_uncleared_borrow", 461);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 482);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 503);
  run_test(test_the_published_offsets_are_ordered_and_fit, "test_the_published_offsets_are_ordered_and_fit", 521);
  run_test(test_input_refuses_a_null_frame_and_a_bad_interface, "test_input_refuses_a_null_frame_and_a_bad_interface", 531);
  run_test(test_every_arriving_frame_counts_its_octets, "test_every_arriving_frame_counts_its_octets", 555);
  run_test(test_a_short_frame_is_an_error_not_a_discard, "test_a_short_frame_is_an_error_not_a_discard", 564);
  run_test(test_an_unhandled_ethertype_counts_unknown_protos, "test_an_unhandled_ethertype_counts_unknown_protos", 574);
  run_test(test_an_untagged_interface_accepts_an_untagged_frame, "test_an_untagged_interface_accepts_an_untagged_frame", 587);
  run_test(test_an_untagged_interface_accepts_a_tagged_frame, "test_an_untagged_interface_accepts_a_tagged_frame", 598);
  run_test(test_a_tagged_interface_accepts_its_own_vid, "test_a_tagged_interface_accepts_its_own_vid", 611);
  run_test(test_a_tagged_interface_discards_another_vid, "test_a_tagged_interface_discards_another_vid", 623);
  run_test(test_a_policy_drop_records_the_offending_vid, "test_a_policy_drop_records_the_offending_vid", 637);
  run_test(test_a_discarded_priority_tagged_frame_records_zero_not_the_sentinel, "test_a_discarded_priority_tagged_frame_records_zero_not_the_sentinel", 664);
  run_test(test_the_reserved_vid_is_an_error_not_a_policy_discard, "test_the_reserved_vid_is_an_error_not_a_policy_discard", 681);
  run_test(test_the_reserved_vid_is_refused_on_an_untagged_interface, "test_the_reserved_vid_is_refused_on_an_untagged_interface", 695);
  run_test(test_if_bind_refuses_a_membership_outside_the_usable_range, "test_if_bind_refuses_a_membership_outside_the_usable_range", 707);
  run_test(test_if_bind_and_if_get_refuse_an_index_past_the_table, "test_if_bind_and_if_get_refuse_an_index_past_the_table", 723);
  run_test(test_clear_sets_every_row_to_the_sentinel, "test_clear_sets_every_row_to_the_sentinel", 735);
  run_test(test_a_bad_ipv4_checksum_is_a_header_error, "test_a_bad_ipv4_checksum_is_a_header_error", 749);
  run_test(test_a_datagram_for_somewhere_else_is_reported_for_forwarding, "test_a_datagram_for_somewhere_else_is_reported_for_forwarding", 763);
  run_test(test_the_limited_broadcast_is_local, "test_the_limited_broadcast_is_local", 773);
  run_test(test_the_directed_broadcast_of_our_subnet_is_local, "test_the_directed_broadcast_of_our_subnet_is_local", 783);
  run_test(test_a_group_we_never_joined_is_an_address_error, "test_a_group_we_never_joined_is_an_address_error", 811);
  run_test(test_a_bound_udp_port_takes_the_datagram, "test_a_bound_udp_port_takes_the_datagram", 823);
  run_test(test_an_unbound_udp_port_counts_no_ports, "test_an_unbound_udp_port_counts_no_ports", 845);
  run_test(test_a_datagram_whose_source_address_is_barred_is_discarded, "test_a_datagram_whose_source_address_is_barred_is_discarded", 862);
  run_test(test_the_unspecified_source_an_address_request_carries_still_arrives, "test_the_unspecified_source_an_address_request_carries_still_arrives", 889);
  run_test(test_an_igmp_query_with_a_good_checksum_is_processed, "test_an_igmp_query_with_a_good_checksum_is_processed", 933);
  run_test(test_an_igmp_message_longer_than_eight_octets_sums_over_the_whole_payload, "test_an_igmp_message_longer_than_eight_octets_sums_over_the_whole_payload", 951);
  run_test(test_an_unrecognized_igmp_type_is_silently_ignored, "test_an_unrecognized_igmp_type_is_silently_ignored", 982);
  run_test(test_an_rfc_1042_encapsulated_datagram_is_received, "test_an_rfc_1042_encapsulated_datagram_is_received", 1008);
  run_test(test_an_igmp_query_with_a_bad_checksum_is_discarded, "test_an_igmp_query_with_a_bad_checksum_is_discarded", 1060);
  run_test(test_the_all_hosts_group_is_this_node_s_whether_or_not_it_joined_one, "test_the_all_hosts_group_is_this_node_s_whether_or_not_it_joined_one", 1079);
  run_test(test_an_igmp_report_with_a_bad_checksum_is_discarded, "test_an_igmp_report_with_a_bad_checksum_is_discarded", 1097);
  run_test(test_a_bad_udp_checksum_is_discarded, "test_a_bad_udp_checksum_is_discarded", 1115);
  run_test(test_a_zero_udp_checksum_is_accepted_over_ipv4, "test_a_zero_udp_checksum_is_accepted_over_ipv4", 1136);
  run_test(test_a_udp_length_past_the_ip_payload_is_an_error, "test_a_udp_length_past_the_ip_payload_is_an_error", 1152);
  run_test(test_a_broadcast_delivery_counts_non_unicast, "test_a_broadcast_delivery_counts_non_unicast", 1173);
  run_test(test_an_icmp_echo_counts_itself_by_message_and_by_type, "test_an_icmp_echo_counts_itself_by_message_and_by_type", 1193);
  run_test(test_the_echo_reply_this_path_builds_takes_its_two_out_counters, "test_the_echo_reply_this_path_builds_takes_its_two_out_counters", 1216);
  run_test(test_an_icmp_message_with_a_bad_checksum_counts_as_an_error, "test_an_icmp_message_with_a_bad_checksum_counts_as_an_error", 1248);
  run_test(test_an_icmp_message_of_unknown_type_is_discarded, "test_an_icmp_message_of_unknown_type_is_discarded", 1274);
  run_test(test_an_icmp_message_too_short_for_its_type_is_an_error, "test_an_icmp_message_too_short_for_its_type_is_an_error", 1299);
  run_test(test_an_unclaimed_ip_protocol_counts_unknown_protos, "test_an_unclaimed_ip_protocol_counts_unknown_protos", 1323);
  run_test(test_an_unclaimed_ipv6_next_header_counts_unknown_protos, "test_an_unclaimed_ipv6_next_header_counts_unknown_protos", 1337);
  run_test(test_a_raw_ipv6_binding_with_ipv6_checksum_verifies_the_received_checksum, "test_a_raw_ipv6_binding_with_ipv6_checksum_verifies_the_received_checksum", 1357);
  run_test(test_a_raw_binding_takes_an_unclaimed_protocol, "test_a_raw_binding_takes_an_unclaimed_protocol", 1418);
  run_test(test_an_echo_request_builds_a_reply, "test_an_echo_request_builds_a_reply", 1443);
  run_test(test_a_reply_with_no_transmit_buffer_is_busy, "test_a_reply_with_no_transmit_buffer_is_busy", 1474);
  run_test(test_an_arp_request_for_us_builds_a_reply, "test_an_arp_request_for_us_builds_a_reply", 1498);
  run_test(test_an_arp_request_for_someone_else_neither_answers_nor_is_learned, "test_an_arp_request_for_someone_else_neither_answers_nor_is_learned", 1518);
  run_test(test_an_arp_request_for_us_is_learned, "test_an_arp_request_for_us_is_learned", 1531);
  run_test(test_an_arp_reply_on_a_tagged_interface_carries_the_tag, "test_an_arp_reply_on_a_tagged_interface_carries_the_tag", 1544);
  run_test(test_an_arp_reply_with_no_transmit_buffer_is_busy, "test_an_arp_reply_with_no_transmit_buffer_is_busy", 1558);
  run_test(test_a_short_arp_packet_is_an_error, "test_a_short_arp_packet_is_an_error", 1575);
  run_test(test_a_fragment_with_no_descriptor_is_discarded, "test_a_fragment_with_no_descriptor_is_discarded", 1587);
  run_test(test_a_fragment_the_reassembler_kept_pins_its_descriptor, "test_a_fragment_the_reassembler_kept_pins_its_descriptor", 1602);
  run_test(test_a_fragment_the_reassembler_refuses_counts_a_reassembly_failure, "test_a_fragment_the_reassembler_refuses_counts_a_reassembly_failure", 1628);
  run_test(test_the_last_fragment_completes_the_datagram, "test_the_last_fragment_completes_the_datagram", 1654);
  run_test(test_an_ipv6_packet_for_our_address_is_delivered, "test_an_ipv6_packet_for_our_address_is_delivered", 1701);
  run_test(test_a_fragmented_neighbor_discovery_message_is_ignored, "test_a_fragmented_neighbor_discovery_message_is_ignored", 1748);
  run_test(test_a_fragmented_echo_request_is_not_ignored, "test_a_fragmented_echo_request_is_not_ignored", 1763);
  run_test(test_a_routing_header_with_segments_left_is_discarded, "test_a_routing_header_with_segments_left_is_discarded", 1798);
  run_test(test_a_routing_header_with_no_segments_left_is_ignored, "test_a_routing_header_with_no_segments_left_is_ignored", 1819);
  run_test(test_an_option_the_node_refuses_discards_the_packet, "test_an_option_the_node_refuses_discards_the_packet", 1862);
  run_test(test_an_unrecognized_option_that_says_skip_is_skipped, "test_an_unrecognized_option_that_says_skip_is_skipped", 1888);
  run_test(test_an_icmpv6_message_of_unknown_type_is_discarded, "test_an_icmpv6_message_of_unknown_type_is_discarded", 1907);
  run_test(test_the_icmpv6_echo_reply_this_path_builds_takes_its_two_out_counters, "test_the_icmpv6_echo_reply_this_path_builds_takes_its_two_out_counters", 1968);
  run_test(test_a_zero_udp_checksum_is_discarded_over_ipv6, "test_a_zero_udp_checksum_is_discarded_over_ipv6", 1998);
  run_test(test_a_bad_udp_checksum_is_discarded_over_ipv6, "test_a_bad_udp_checksum_is_discarded_over_ipv6", 2022);
  run_test(test_an_ipv6_packet_for_somewhere_else_is_reported_for_forwarding, "test_an_ipv6_packet_for_somewhere_else_is_reported_for_forwarding", 2049);
  run_test(test_an_ipv6_payload_length_past_the_frame_is_a_truncated_packet, "test_an_ipv6_payload_length_past_the_frame_is_a_truncated_packet", 2065);
  run_test(test_an_ipv6_version_that_is_not_six_is_a_header_error, "test_an_ipv6_version_that_is_not_six_is_a_header_error", 2084);
  run_test(test_a_frame_too_short_for_the_ipv6_header_is_a_truncated_packet, "test_a_frame_too_short_for_the_ipv6_header_is_a_truncated_packet", 2102);
  run_test(test_a_multicast_destination_counts_an_ipv6_multicast_arrival, "test_a_multicast_destination_counts_an_ipv6_multicast_arrival", 2117);
  run_test(test_the_solicited_node_address_of_our_own_is_local, "test_the_solicited_node_address_of_our_own_is_local", 2142);
  run_test(test_a_neighbor_solicitation_reaches_the_neighbor_discovery_module, "test_a_neighbor_solicitation_reaches_the_neighbor_discovery_module", 2221);
  run_test(test_a_neighbor_advertisement_reaches_the_neighbor_discovery_module, "test_a_neighbor_advertisement_reaches_the_neighbor_discovery_module", 2262);
  run_test(test_a_router_advertisement_carrying_a_prefix_option_reaches_the_module, "test_a_router_advertisement_carrying_a_prefix_option_reaches_the_module", 2280);
  run_test(test_an_mld_query_reaches_the_group_module, "test_an_mld_query_reaches_the_group_module", 2308);
  run_test(test_every_neighbor_discovery_and_listener_type_takes_its_own_rfc_2466_counter, "test_every_neighbor_discovery_and_listener_type_takes_its_own_rfc_2466_counter", 2331);
  run_test(test_a_packet_too_big_takes_the_rfc_2466_counter_of_its_own, "test_a_packet_too_big_takes_the_rfc_2466_counter_of_its_own", 2384);
  run_test(test_a_prohibited_destination_unreachable_counts_under_both_its_counters, "test_a_prohibited_destination_unreachable_counts_under_both_its_counters", 2410);
  run_test(test_a_destination_unreachable_at_another_code_is_not_an_admin_prohibition, "test_a_destination_unreachable_at_another_code_is_not_an_admin_prohibition", 2434);
  run_test(test_a_neighbor_solicitation_with_a_bad_checksum_is_discarded, "test_a_neighbor_solicitation_with_a_bad_checksum_is_discarded", 2456);
  run_test(test_a_neighbor_solicitation_without_its_target_address_is_discarded, "test_a_neighbor_solicitation_without_its_target_address_is_discarded", 2477);
  run_test(test_an_icmpv6_message_too_short_for_its_type_is_an_error, "test_an_icmpv6_message_too_short_for_its_type_is_an_error", 2503);
  run_test(test_a_neighbor_solicitation_from_off_link_is_discarded, "test_a_neighbor_solicitation_from_off_link_is_discarded", 2529);
  run_test(test_a_router_advertisement_from_off_link_is_discarded, "test_a_router_advertisement_from_off_link_is_discarded", 2552);
  run_test(test_a_neighbor_solicitation_with_a_nonzero_code_is_discarded, "test_a_neighbor_solicitation_with_a_nonzero_code_is_discarded", 2570);
  run_test(test_an_nd_option_of_length_zero_discards_the_packet, "test_an_nd_option_of_length_zero_discards_the_packet", 2588);
  run_test(test_the_all_nodes_address_identifies_this_host, "test_the_all_nodes_address_identifies_this_host", 2612);
  run_test(test_the_interface_local_all_nodes_address_identifies_this_host, "test_the_interface_local_all_nodes_address_identifies_this_host", 2631);
  run_test(test_a_multicast_group_this_node_never_joined_is_not_local, "test_a_multicast_group_this_node_never_joined_is_not_local", 2646);
  run_test(test_a_unicast_address_that_is_not_ours_is_still_forwarded, "test_a_unicast_address_that_is_not_ours_is_still_forwarded", 2672);
  run_test(test_a_multicast_group_this_node_joined_is_local, "test_a_multicast_group_this_node_joined_is_local", 2691);
  run_test(test_an_nd_option_running_past_the_message_discards_the_packet, "test_an_nd_option_running_past_the_message_discards_the_packet", 2733);
  run_test(test_an_ipv6_fragment_the_reassembler_kept_pins_its_descriptor, "test_an_ipv6_fragment_the_reassembler_kept_pins_its_descriptor", 2774);
  run_test(test_the_last_ipv6_fragment_completes_the_datagram, "test_the_last_ipv6_fragment_completes_the_datagram", 2801);
  run_test(test_an_ipv6_fragment_with_no_descriptor_is_discarded, "test_an_ipv6_fragment_with_no_descriptor_is_discarded", 2824);
  run_test(test_an_ipv6_fragment_the_reassembler_refuses_counts_a_reassembly_failure, "test_an_ipv6_fragment_the_reassembler_refuses_counts_a_reassembly_failure", 2844);
  run_test(test_a_bare_rst_at_a_listener_creates_no_tcb, "test_a_bare_rst_at_a_listener_creates_no_tcb", 2917);
  run_test(test_a_syn_past_the_listeners_backlog_takes_no_connection, "test_a_syn_past_the_listeners_backlog_takes_no_connection", 2944);
  run_test(test_a_bare_ack_at_a_listener_resets_without_a_passive_open, "test_a_bare_ack_at_a_listener_resets_without_a_passive_open", 2990);
  run_test(test_a_syn_at_a_listener_is_the_one_passive_open, "test_a_syn_at_a_listener_is_the_one_passive_open", 3007);
  run_test(test_a_reset_sent_for_a_segment_with_no_tcb_is_counted, "test_a_reset_sent_for_a_segment_with_no_tcb_is_counted", 3018);
  run_test(test_tcp_in_segs_counts_a_segment_shorter_than_the_header, "test_tcp_in_segs_counts_a_segment_shorter_than_the_header", 3028);
  run_test(test_a_segment_with_no_tcb_reaches_the_closed_state, "test_a_segment_with_no_tcb_reaches_the_closed_state", 3042);
  run_test(test_a_syn_to_a_listener_creates_the_connection, "test_a_syn_to_a_listener_creates_the_connection", 3069);
  run_test(test_the_second_segment_finds_the_connection, "test_the_second_segment_finds_the_connection", 3088);
  run_test(test_an_ordinary_acknowledgment_is_aggregated_and_not_reported, "test_an_ordinary_acknowledgment_is_aggregated_and_not_reported", 3135);
  run_test(test_two_segments_earn_one_acknowledgment, "test_two_segments_earn_one_acknowledgment", 3154);
  run_test(test_an_ack_flush_with_nothing_owed_is_busy, "test_an_ack_flush_with_nothing_owed_is_busy", 3185);
  run_test(test_a_segment_ahead_of_the_window_is_held, "test_a_segment_ahead_of_the_window_is_held", 3194);
  run_test(test_a_held_segment_waits_until_rcv_nxt_reaches_it, "test_a_held_segment_waits_until_rcv_nxt_reaches_it", 3222);
  run_test(test_a_held_segment_is_redelivered_once_the_gap_is_filled, "test_a_held_segment_is_redelivered_once_the_gap_is_filled", 3240);
  run_test(test_a_redelivery_owes_the_aggregate_acknowledgment, "test_a_redelivery_owes_the_aggregate_acknowledgment", 3280);
  run_test(test_tcp_deliver_refuses_a_pcb_past_the_table, "test_tcp_deliver_refuses_a_pcb_past_the_table", 3306);
  run_test(test_a_short_tcp_segment_is_an_error, "test_a_short_tcp_segment_is_an_error", 3314);
  run_test(test_a_challenge_acknowledgment_is_not_aggregated, "test_a_challenge_acknowledgment_is_not_aggregated", 3326);
  run_test(test_a_udp_lite_datagram_reaches_a_lite_binding, "test_a_udp_lite_datagram_reaches_a_lite_binding", 3353);
  run_test(test_a_udp_lite_datagram_with_an_illegal_coverage_is_discarded, "test_a_udp_lite_datagram_with_an_illegal_coverage_is_discarded", 3405);
  run_test(test_a_udp_lite_datagram_with_a_bad_checksum_is_refused_as_a_checksum_fault, "test_a_udp_lite_datagram_with_a_bad_checksum_is_refused_as_a_checksum_fault", 3423);
  run_test(test_a_frame_with_no_vlan_borrow_is_refused, "test_a_frame_with_no_vlan_borrow_is_refused", 3478);
  run_test(test_an_ipv4_frame_with_an_unbound_unit_is_refused, "test_an_ipv4_frame_with_an_unbound_unit_is_refused", 3489);
  run_test(test_an_ipv6_frame_with_an_unbound_unit_is_refused, "test_an_ipv6_frame_with_an_unbound_unit_is_refused", 3533);
  run_test(test_a_udp_datagram_with_an_unbound_unit_is_refused, "test_a_udp_datagram_with_an_unbound_unit_is_refused", 3559);
  run_test(test_a_tcp_segment_with_an_unbound_unit_is_refused, "test_a_tcp_segment_with_an_unbound_unit_is_refused", 3590);

  return UNITY_END();
}
