/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/ip/ipv6.h"
#include "src/tcp/tcp_in.h"
#include "src/tcp/tcp_out.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_clear_repeats(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_built_segment_reads_back_through_the_parse(void);
extern void test_the_data_offset_counts_the_header_words_and_reserved_is_zero(void);
extern void test_the_options_a_syn_carries_read_back(void);
extern void test_the_syn_only_options_are_left_off_a_segment_without_syn(void);
extern void test_the_options_are_padded_to_a_word_with_zeros(void);
extern void test_the_sack_option_carries_the_blocks_the_control_state_holds(void);
extern void test_the_window_field_is_shifted_on_every_segment_but_a_syn(void);
extern void test_the_acknowledgment_and_urgent_fields_go_out_zero_without_their_bits(void);
extern void test_a_built_ipv6_segment_checks_out_against_the_rfc_8200_pseudo_header(void);
extern void test_the_build_refuses_what_no_retry_fixes(void);
extern void test_the_usable_window_is_the_offered_window_less_what_is_in_flight(void);
extern void test_rule_1_sends_a_maximum_sized_segment_even_with_data_unacknowledged(void);
extern void test_nagle_holds_a_short_pushed_segment_while_data_is_unacknowledged(void);
extern void test_nagle_can_be_disabled_on_the_connection(void);
extern void test_rule_3_sends_at_half_the_largest_window_ever_seen(void);
extern void test_rule_4_the_override_timeout_sends_what_is_there(void);
extern void test_the_congestion_window_holds_the_usable_window_down(void);
extern void test_a_zero_offered_window_sends_nothing(void);
extern void test_send_refuses_a_zero_maximum_segment_size(void);
extern void test_the_first_measurement_takes_rule_2_2(void);
extern void test_a_later_measurement_takes_rule_2_3_in_the_stated_order(void);
extern void test_the_rto_is_floored_at_a_second_and_capped_at_the_maximum(void);
extern void test_a_zero_variance_term_is_rounded_to_the_clock_granularity(void);
extern void test_rtx_arm_starts_the_timer_only_when_it_is_not_running(void);
extern void test_an_unmeasured_connection_arms_at_the_initial_rto(void);
extern void test_rtx_stop_turns_the_timer_off_and_rtx_restart_restarts_it(void);
extern void test_the_timeout_doubles_the_rto_and_restarts_from_the_doubled_value(void);
extern void test_the_retransmission_count_reaching_r2_asks_the_caller_to_close(void);
extern void test_an_unacknowledged_syn_is_counted_against_the_syn_threshold(void);
extern void test_an_r2_of_infinity_never_closes_the_connection(void);
extern void test_the_doubling_is_bounded_by_the_maximum_rto(void);
extern void test_the_timeout_halves_ssthresh_and_drops_cwnd_to_one_segment(void);
extern void test_a_segment_already_retransmitted_holds_ssthresh_constant(void);
extern void test_slow_start_grows_cwnd_by_the_lesser_of_n_and_smss(void);
extern void test_slow_start_resists_the_ack_division_of_rfc_5681_section_3_1(void);
extern void test_congestion_avoidance_counts_bytes_acked_per_rfc_3465(void);
extern void test_the_third_duplicate_ack_sets_ssthresh_and_inflates_cwnd(void);
extern void test_each_duplicate_ack_after_the_third_inflates_cwnd_by_one_segment(void);
extern void test_the_recovering_acknowledgment_deflates_cwnd_to_ssthresh(void);
extern void test_the_congestion_entries_refuse_a_zero_segment_size(void);
extern void test_the_acknowledgment_is_the_challenge_ack_tcp_in_asks_for(void);
extern void test_the_reset_of_figure_10_takes_its_sequence_from_the_ack_field(void);
extern void test_the_reset_for_a_segment_without_an_ack_takes_sequence_zero(void);
extern void test_a_reset_built_onto_the_wire_reads_back(void);
extern void test_a_syn_ack_carries_the_timestamp_echo(void);
extern void test_the_initial_window_takes_the_three_way_table(void);
extern void test_a_new_connection_starts_in_slow_start_and_can_send(void);
extern void test_the_handshake_acknowledgment_does_not_open_the_window(void);
extern void test_a_syn_timeout_floors_the_rto_at_three_seconds_once_data_begins(void);
extern void test_a_sample_taken_across_a_retransmission_is_refused(void);
extern void test_an_idle_connection_restarts_at_the_restart_window(void);
extern void test_the_same_operands_on_two_borrows_decide_alike(void);
extern void test_the_build_refuses_a_segment_with_no_address_at_either_end(void);
extern void test_the_build_refuses_more_options_than_the_data_offset_can_reach(void);
extern void test_a_sack_option_with_no_blocks_is_not_written(void);
extern void test_a_receive_scale_past_the_maximum_shifts_by_the_maximum(void);
extern void test_a_push_with_nothing_queued_sends_nothing(void);
extern void test_a_gap_inside_the_timeout_is_not_idle_and_the_restart_never_raises_the_window(void);
extern void test_the_rtt_entry_refuses_a_measurement_of_nothing(void);
extern void test_a_measurement_above_the_estimate_moves_the_variance_the_same_way_one_below_it_does(void);
extern void test_a_timer_started_before_any_measurement_runs_at_one_second(void);
extern void test_a_deadline_landing_on_the_instant_that_names_a_stopped_timer_takes_the_next_one(void);
extern void test_the_syn_floor_waits_for_the_handshake_and_never_lowers_an_rto_already_past_it(void);
extern void test_a_timeout_on_a_syn_is_marked_and_counted_as_a_syn_at_either_end_of_the_handshake(void);
extern void test_the_congestion_entries_refuse_a_segment_size_of_nothing_and_an_acknowledgment_of_nothing(void);
extern void test_the_duplicate_count_holds_at_the_top_of_its_width(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/unit/tcp/test_tcp_out/test_tcp_out.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 148);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 156);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 166);
  run_test(test_clear_repeats, "test_clear_repeats", 180);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 191);
  run_test(test_a_built_segment_reads_back_through_the_parse, "test_a_built_segment_reads_back_through_the_parse", 206);
  run_test(test_the_data_offset_counts_the_header_words_and_reserved_is_zero, "test_the_data_offset_counts_the_header_words_and_reserved_is_zero", 236);
  run_test(test_the_options_a_syn_carries_read_back, "test_the_options_a_syn_carries_read_back", 252);
  run_test(test_the_syn_only_options_are_left_off_a_segment_without_syn, "test_the_syn_only_options_are_left_off_a_segment_without_syn", 302);
  run_test(test_the_options_are_padded_to_a_word_with_zeros, "test_the_options_are_padded_to_a_word_with_zeros", 338);
  run_test(test_the_sack_option_carries_the_blocks_the_control_state_holds, "test_the_sack_option_carries_the_blocks_the_control_state_holds", 354);
  run_test(test_the_window_field_is_shifted_on_every_segment_but_a_syn, "test_the_window_field_is_shifted_on_every_segment_but_a_syn", 393);
  run_test(test_the_acknowledgment_and_urgent_fields_go_out_zero_without_their_bits, "test_the_acknowledgment_and_urgent_fields_go_out_zero_without_their_bits", 417);
  run_test(test_a_built_ipv6_segment_checks_out_against_the_rfc_8200_pseudo_header, "test_a_built_ipv6_segment_checks_out_against_the_rfc_8200_pseudo_header", 435);
  run_test(test_the_build_refuses_what_no_retry_fixes, "test_the_build_refuses_what_no_retry_fixes", 451);
  run_test(test_the_usable_window_is_the_offered_window_less_what_is_in_flight, "test_the_usable_window_is_the_offered_window_less_what_is_in_flight", 483);
  run_test(test_rule_1_sends_a_maximum_sized_segment_even_with_data_unacknowledged, "test_rule_1_sends_a_maximum_sized_segment_even_with_data_unacknowledged", 501);
  run_test(test_nagle_holds_a_short_pushed_segment_while_data_is_unacknowledged, "test_nagle_holds_a_short_pushed_segment_while_data_is_unacknowledged", 515);
  run_test(test_nagle_can_be_disabled_on_the_connection, "test_nagle_can_be_disabled_on_the_connection", 538);
  run_test(test_rule_3_sends_at_half_the_largest_window_ever_seen, "test_rule_3_sends_at_half_the_largest_window_ever_seen", 552);
  run_test(test_rule_4_the_override_timeout_sends_what_is_there, "test_rule_4_the_override_timeout_sends_what_is_there", 578);
  run_test(test_the_congestion_window_holds_the_usable_window_down, "test_the_congestion_window_holds_the_usable_window_down", 595);
  run_test(test_a_zero_offered_window_sends_nothing, "test_a_zero_offered_window_sends_nothing", 614);
  run_test(test_send_refuses_a_zero_maximum_segment_size, "test_send_refuses_a_zero_maximum_segment_size", 628);
  run_test(test_the_first_measurement_takes_rule_2_2, "test_the_first_measurement_takes_rule_2_2", 640);
  run_test(test_a_later_measurement_takes_rule_2_3_in_the_stated_order, "test_a_later_measurement_takes_rule_2_3_in_the_stated_order", 653);
  run_test(test_the_rto_is_floored_at_a_second_and_capped_at_the_maximum, "test_the_rto_is_floored_at_a_second_and_capped_at_the_maximum", 670);
  run_test(test_a_zero_variance_term_is_rounded_to_the_clock_granularity, "test_a_zero_variance_term_is_rounded_to_the_clock_granularity", 685);
  run_test(test_rtx_arm_starts_the_timer_only_when_it_is_not_running, "test_rtx_arm_starts_the_timer_only_when_it_is_not_running", 698);
  run_test(test_an_unmeasured_connection_arms_at_the_initial_rto, "test_an_unmeasured_connection_arms_at_the_initial_rto", 715);
  run_test(test_rtx_stop_turns_the_timer_off_and_rtx_restart_restarts_it, "test_rtx_stop_turns_the_timer_off_and_rtx_restart_restarts_it", 727);
  run_test(test_the_timeout_doubles_the_rto_and_restarts_from_the_doubled_value, "test_the_timeout_doubles_the_rto_and_restarts_from_the_doubled_value", 750);
  run_test(test_the_retransmission_count_reaching_r2_asks_the_caller_to_close, "test_the_retransmission_count_reaching_r2_asks_the_caller_to_close", 774);
  run_test(test_an_unacknowledged_syn_is_counted_against_the_syn_threshold, "test_an_unacknowledged_syn_is_counted_against_the_syn_threshold", 795);
  run_test(test_an_r2_of_infinity_never_closes_the_connection, "test_an_r2_of_infinity_never_closes_the_connection", 816);
  run_test(test_the_doubling_is_bounded_by_the_maximum_rto, "test_the_doubling_is_bounded_by_the_maximum_rto", 834);
  run_test(test_the_timeout_halves_ssthresh_and_drops_cwnd_to_one_segment, "test_the_timeout_halves_ssthresh_and_drops_cwnd_to_one_segment", 848);
  run_test(test_a_segment_already_retransmitted_holds_ssthresh_constant, "test_a_segment_already_retransmitted_holds_ssthresh_constant", 873);
  run_test(test_slow_start_grows_cwnd_by_the_lesser_of_n_and_smss, "test_slow_start_grows_cwnd_by_the_lesser_of_n_and_smss", 890);
  run_test(test_slow_start_resists_the_ack_division_of_rfc_5681_section_3_1, "test_slow_start_resists_the_ack_division_of_rfc_5681_section_3_1", 909);
  run_test(test_congestion_avoidance_counts_bytes_acked_per_rfc_3465, "test_congestion_avoidance_counts_bytes_acked_per_rfc_3465", 927);
  run_test(test_the_third_duplicate_ack_sets_ssthresh_and_inflates_cwnd, "test_the_third_duplicate_ack_sets_ssthresh_and_inflates_cwnd", 948);
  run_test(test_each_duplicate_ack_after_the_third_inflates_cwnd_by_one_segment, "test_each_duplicate_ack_after_the_third_inflates_cwnd_by_one_segment", 966);
  run_test(test_the_recovering_acknowledgment_deflates_cwnd_to_ssthresh, "test_the_recovering_acknowledgment_deflates_cwnd_to_ssthresh", 986);
  run_test(test_the_congestion_entries_refuse_a_zero_segment_size, "test_the_congestion_entries_refuse_a_zero_segment_size", 1013);
  run_test(test_the_acknowledgment_is_the_challenge_ack_tcp_in_asks_for, "test_the_acknowledgment_is_the_challenge_ack_tcp_in_asks_for", 1029);
  run_test(test_the_reset_of_figure_10_takes_its_sequence_from_the_ack_field, "test_the_reset_of_figure_10_takes_its_sequence_from_the_ack_field", 1061);
  run_test(test_the_reset_for_a_segment_without_an_ack_takes_sequence_zero, "test_the_reset_for_a_segment_without_an_ack_takes_sequence_zero", 1077);
  run_test(test_a_reset_built_onto_the_wire_reads_back, "test_a_reset_built_onto_the_wire_reads_back", 1091);
  run_test(test_a_syn_ack_carries_the_timestamp_echo, "test_a_syn_ack_carries_the_timestamp_echo", 1123);
  run_test(test_the_initial_window_takes_the_three_way_table, "test_the_initial_window_takes_the_three_way_table", 1150);
  run_test(test_a_new_connection_starts_in_slow_start_and_can_send, "test_a_new_connection_starts_in_slow_start_and_can_send", 1178);
  run_test(test_the_handshake_acknowledgment_does_not_open_the_window, "test_the_handshake_acknowledgment_does_not_open_the_window", 1204);
  run_test(test_a_syn_timeout_floors_the_rto_at_three_seconds_once_data_begins, "test_a_syn_timeout_floors_the_rto_at_three_seconds_once_data_begins", 1225);
  run_test(test_a_sample_taken_across_a_retransmission_is_refused, "test_a_sample_taken_across_a_retransmission_is_refused", 1255);
  run_test(test_an_idle_connection_restarts_at_the_restart_window, "test_an_idle_connection_restarts_at_the_restart_window", 1286);
  run_test(test_the_same_operands_on_two_borrows_decide_alike, "test_the_same_operands_on_two_borrows_decide_alike", 1311);
  run_test(test_the_build_refuses_a_segment_with_no_address_at_either_end, "test_the_build_refuses_a_segment_with_no_address_at_either_end", 1332);
  run_test(test_the_build_refuses_more_options_than_the_data_offset_can_reach, "test_the_build_refuses_more_options_than_the_data_offset_can_reach", 1350);
  run_test(test_a_sack_option_with_no_blocks_is_not_written, "test_a_sack_option_with_no_blocks_is_not_written", 1368);
  run_test(test_a_receive_scale_past_the_maximum_shifts_by_the_maximum, "test_a_receive_scale_past_the_maximum_shifts_by_the_maximum", 1394);
  run_test(test_a_push_with_nothing_queued_sends_nothing, "test_a_push_with_nothing_queued_sends_nothing", 1406);
  run_test(test_a_gap_inside_the_timeout_is_not_idle_and_the_restart_never_raises_the_window, "test_a_gap_inside_the_timeout_is_not_idle_and_the_restart_never_raises_the_window", 1420);
  run_test(test_the_rtt_entry_refuses_a_measurement_of_nothing, "test_the_rtt_entry_refuses_a_measurement_of_nothing", 1443);
  run_test(test_a_measurement_above_the_estimate_moves_the_variance_the_same_way_one_below_it_does, "test_a_measurement_above_the_estimate_moves_the_variance_the_same_way_one_below_it_does", 1454);
  run_test(test_a_timer_started_before_any_measurement_runs_at_one_second, "test_a_timer_started_before_any_measurement_runs_at_one_second", 1480);
  run_test(test_a_deadline_landing_on_the_instant_that_names_a_stopped_timer_takes_the_next_one, "test_a_deadline_landing_on_the_instant_that_names_a_stopped_timer_takes_the_next_one", 1517);
  run_test(test_the_syn_floor_waits_for_the_handshake_and_never_lowers_an_rto_already_past_it, "test_the_syn_floor_waits_for_the_handshake_and_never_lowers_an_rto_already_past_it", 1535);
  run_test(test_a_timeout_on_a_syn_is_marked_and_counted_as_a_syn_at_either_end_of_the_handshake, "test_a_timeout_on_a_syn_is_marked_and_counted_as_a_syn_at_either_end_of_the_handshake", 1567);
  run_test(test_the_congestion_entries_refuse_a_segment_size_of_nothing_and_an_acknowledgment_of_nothing, "test_the_congestion_entries_refuse_a_segment_size_of_nothing_and_an_acknowledgment_of_nothing", 1589);
  run_test(test_the_duplicate_count_holds_at_the_top_of_its_width, "test_the_duplicate_count_holds_at_the_top_of_its_width", 1611);

  return UNITY_END();
}
