/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/ip/ipv6.h"
#include "src/tcp/tcp_in.h"
#include "src/tcp/tcp_out.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_clear_repeats(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_built_segment_reads_back_through_the_parse(void);
extern void test_the_data_offset_counts_the_header_words_and_reserved_is_zero(void);
extern void test_the_options_a_syn_carries_read_back(void);
extern void test_the_syn_only_options_are_left_off_a_segment_without_syn(void);
extern void test_the_options_are_padded_to_a_word_with_zeros(void);
extern void test_the_sack_option_carries_the_blocks_the_control_state_holds(void);
extern void test_the_window_field_is_shifted_on_every_segment_but_a_syn(void);
extern void test_the_acknowledgment_and_urgent_fields_go_out_zero_without_their_bits(void);
extern void test_a_built_ipv6_segment_checks_out_against_the_rfc_8200_pseudo_header(void);
extern void test_the_build_refuses_what_no_retry_fixes(void);
extern void test_the_usable_window_is_the_offered_window_less_what_is_in_flight(void);
extern void test_rule_1_sends_a_maximum_sized_segment_even_with_data_unacknowledged(void);
extern void test_nagle_holds_a_short_pushed_segment_while_data_is_unacknowledged(void);
extern void test_nagle_can_be_disabled_on_the_connection(void);
extern void test_rule_3_sends_at_half_the_largest_window_ever_seen(void);
extern void test_rule_4_the_override_timeout_sends_what_is_there(void);
extern void test_the_congestion_window_holds_the_usable_window_down(void);
extern void test_a_zero_offered_window_sends_nothing(void);
extern void test_send_refuses_a_zero_maximum_segment_size(void);
extern void test_the_first_measurement_takes_rule_2_2(void);
extern void test_a_later_measurement_takes_rule_2_3_in_the_stated_order(void);
extern void test_the_rto_is_floored_at_a_second_and_capped_at_the_maximum(void);
extern void test_a_zero_variance_term_is_rounded_to_the_clock_granularity(void);
extern void test_rtx_arm_starts_the_timer_only_when_it_is_not_running(void);
extern void test_an_unmeasured_connection_arms_at_the_initial_rto(void);
extern void test_rtx_stop_turns_the_timer_off_and_rtx_restart_restarts_it(void);
extern void test_the_timeout_doubles_the_rto_and_restarts_from_the_doubled_value(void);
extern void test_the_doubling_is_bounded_by_the_maximum_rto(void);
extern void test_the_timeout_halves_ssthresh_and_drops_cwnd_to_one_segment(void);
extern void test_a_segment_already_retransmitted_holds_ssthresh_constant(void);
extern void test_slow_start_grows_cwnd_by_the_lesser_of_n_and_smss(void);
extern void test_slow_start_resists_the_ack_division_of_rfc_5681_section_3_1(void);
extern void test_congestion_avoidance_counts_bytes_acked_per_rfc_3465(void);
extern void test_the_third_duplicate_ack_sets_ssthresh_and_inflates_cwnd(void);
extern void test_each_duplicate_ack_after_the_third_inflates_cwnd_by_one_segment(void);
extern void test_the_recovering_acknowledgment_deflates_cwnd_to_ssthresh(void);
extern void test_the_congestion_entries_refuse_a_zero_segment_size(void);
extern void test_the_acknowledgment_is_the_challenge_ack_tcp_in_asks_for(void);
extern void test_the_reset_of_figure_10_takes_its_sequence_from_the_ack_field(void);
extern void test_the_reset_for_a_segment_without_an_ack_takes_sequence_zero(void);
extern void test_a_reset_built_onto_the_wire_reads_back(void);
extern void test_the_same_operands_on_two_borrows_decide_alike(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/tcp/test_tcp_out\\test_tcp_out.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 121);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 129);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 139);
  run_test(test_clear_repeats, "test_clear_repeats", 158);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 169);
  run_test(test_a_built_segment_reads_back_through_the_parse, "test_a_built_segment_reads_back_through_the_parse", 184);
  run_test(test_the_data_offset_counts_the_header_words_and_reserved_is_zero, "test_the_data_offset_counts_the_header_words_and_reserved_is_zero", 214);
  run_test(test_the_options_a_syn_carries_read_back, "test_the_options_a_syn_carries_read_back", 230);
  run_test(test_the_syn_only_options_are_left_off_a_segment_without_syn, "test_the_syn_only_options_are_left_off_a_segment_without_syn", 275);
  run_test(test_the_options_are_padded_to_a_word_with_zeros, "test_the_options_are_padded_to_a_word_with_zeros", 298);
  run_test(test_the_sack_option_carries_the_blocks_the_control_state_holds, "test_the_sack_option_carries_the_blocks_the_control_state_holds", 314);
  run_test(test_the_window_field_is_shifted_on_every_segment_but_a_syn, "test_the_window_field_is_shifted_on_every_segment_but_a_syn", 353);
  run_test(test_the_acknowledgment_and_urgent_fields_go_out_zero_without_their_bits, "test_the_acknowledgment_and_urgent_fields_go_out_zero_without_their_bits", 376);
  run_test(test_a_built_ipv6_segment_checks_out_against_the_rfc_8200_pseudo_header, "test_a_built_ipv6_segment_checks_out_against_the_rfc_8200_pseudo_header", 394);
  run_test(test_the_build_refuses_what_no_retry_fixes, "test_the_build_refuses_what_no_retry_fixes", 410);
  run_test(test_the_usable_window_is_the_offered_window_less_what_is_in_flight, "test_the_usable_window_is_the_offered_window_less_what_is_in_flight", 442);
  run_test(test_rule_1_sends_a_maximum_sized_segment_even_with_data_unacknowledged, "test_rule_1_sends_a_maximum_sized_segment_even_with_data_unacknowledged", 460);
  run_test(test_nagle_holds_a_short_pushed_segment_while_data_is_unacknowledged, "test_nagle_holds_a_short_pushed_segment_while_data_is_unacknowledged", 474);
  run_test(test_nagle_can_be_disabled_on_the_connection, "test_nagle_can_be_disabled_on_the_connection", 497);
  run_test(test_rule_3_sends_at_half_the_largest_window_ever_seen, "test_rule_3_sends_at_half_the_largest_window_ever_seen", 511);
  run_test(test_rule_4_the_override_timeout_sends_what_is_there, "test_rule_4_the_override_timeout_sends_what_is_there", 537);
  run_test(test_the_congestion_window_holds_the_usable_window_down, "test_the_congestion_window_holds_the_usable_window_down", 554);
  run_test(test_a_zero_offered_window_sends_nothing, "test_a_zero_offered_window_sends_nothing", 573);
  run_test(test_send_refuses_a_zero_maximum_segment_size, "test_send_refuses_a_zero_maximum_segment_size", 587);
  run_test(test_the_first_measurement_takes_rule_2_2, "test_the_first_measurement_takes_rule_2_2", 599);
  run_test(test_a_later_measurement_takes_rule_2_3_in_the_stated_order, "test_a_later_measurement_takes_rule_2_3_in_the_stated_order", 612);
  run_test(test_the_rto_is_floored_at_a_second_and_capped_at_the_maximum, "test_the_rto_is_floored_at_a_second_and_capped_at_the_maximum", 629);
  run_test(test_a_zero_variance_term_is_rounded_to_the_clock_granularity, "test_a_zero_variance_term_is_rounded_to_the_clock_granularity", 644);
  run_test(test_rtx_arm_starts_the_timer_only_when_it_is_not_running, "test_rtx_arm_starts_the_timer_only_when_it_is_not_running", 657);
  run_test(test_an_unmeasured_connection_arms_at_the_initial_rto, "test_an_unmeasured_connection_arms_at_the_initial_rto", 674);
  run_test(test_rtx_stop_turns_the_timer_off_and_rtx_restart_restarts_it, "test_rtx_stop_turns_the_timer_off_and_rtx_restart_restarts_it", 686);
  run_test(test_the_timeout_doubles_the_rto_and_restarts_from_the_doubled_value, "test_the_timeout_doubles_the_rto_and_restarts_from_the_doubled_value", 709);
  run_test(test_the_doubling_is_bounded_by_the_maximum_rto, "test_the_doubling_is_bounded_by_the_maximum_rto", 733);
  run_test(test_the_timeout_halves_ssthresh_and_drops_cwnd_to_one_segment, "test_the_timeout_halves_ssthresh_and_drops_cwnd_to_one_segment", 747);
  run_test(test_a_segment_already_retransmitted_holds_ssthresh_constant, "test_a_segment_already_retransmitted_holds_ssthresh_constant", 772);
  run_test(test_slow_start_grows_cwnd_by_the_lesser_of_n_and_smss, "test_slow_start_grows_cwnd_by_the_lesser_of_n_and_smss", 789);
  run_test(test_slow_start_resists_the_ack_division_of_rfc_5681_section_3_1, "test_slow_start_resists_the_ack_division_of_rfc_5681_section_3_1", 808);
  run_test(test_congestion_avoidance_counts_bytes_acked_per_rfc_3465, "test_congestion_avoidance_counts_bytes_acked_per_rfc_3465", 826);
  run_test(test_the_third_duplicate_ack_sets_ssthresh_and_inflates_cwnd, "test_the_third_duplicate_ack_sets_ssthresh_and_inflates_cwnd", 847);
  run_test(test_each_duplicate_ack_after_the_third_inflates_cwnd_by_one_segment, "test_each_duplicate_ack_after_the_third_inflates_cwnd_by_one_segment", 865);
  run_test(test_the_recovering_acknowledgment_deflates_cwnd_to_ssthresh, "test_the_recovering_acknowledgment_deflates_cwnd_to_ssthresh", 885);
  run_test(test_the_congestion_entries_refuse_a_zero_segment_size, "test_the_congestion_entries_refuse_a_zero_segment_size", 912);
  run_test(test_the_acknowledgment_is_the_challenge_ack_tcp_in_asks_for, "test_the_acknowledgment_is_the_challenge_ack_tcp_in_asks_for", 928);
  run_test(test_the_reset_of_figure_10_takes_its_sequence_from_the_ack_field, "test_the_reset_of_figure_10_takes_its_sequence_from_the_ack_field", 960);
  run_test(test_the_reset_for_a_segment_without_an_ack_takes_sequence_zero, "test_the_reset_for_a_segment_without_an_ack_takes_sequence_zero", 976);
  run_test(test_a_reset_built_onto_the_wire_reads_back, "test_a_reset_built_onto_the_wire_reads_back", 990);
  run_test(test_the_same_operands_on_two_borrows_decide_alike, "test_the_same_operands_on_two_borrows_decide_alike", 1021);

  return UNITY_END();
}
