/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/dhcp/dhcp4.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_the_published_offsets_are_ordered_and_fit(void);
extern void test_the_io_macro_lands_on_the_published_offset(void);
extern void test_clear_zeroes_the_regions(void);
extern void test_clear_touches_one_borrow_only(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_unbound_borrow_refuses_work(void);
extern void test_clear_does_not_bind(void);
extern void test_bind_refuses_null_cfg(void);
extern void test_bind_refuses_an_unusable_cfg(void);
extern void test_bind_accepts_a_complete_cfg(void);
extern void test_the_states_of_figure_5_are_distinct(void);
extern void test_the_message_types_and_ports_are_as_the_rfc_prints_them(void);
extern void test_an_option_of_the_wrong_length_discards_the_message(void);
extern void test_the_first_occurrence_of_each_option_is_the_one_read(void);
extern void test_the_first_occurrence_of_the_remaining_options_is_the_one_read(void);
extern void test_an_option_area_that_ends_without_an_end_option_is_still_read(void);
extern void test_an_option_running_off_the_end_of_the_area_discards_the_message(void);
extern void test_an_option_running_off_the_end_of_an_overloaded_field_discards_the_message(void);
extern void test_a_pad_and_an_unread_option_are_stepped_over(void);
extern void test_the_renewal_interval_is_floored_at_sixty_seconds(void);
extern void test_a_reply_naming_another_hardware_type_or_length_is_discarded(void);
extern void test_an_inform_goes_to_the_server_the_last_answer_named(void);
extern void test_release_decline_and_inform_each_refuse_what_no_tick_fixes(void);
extern void test_a_unicast_owed_with_no_server_to_send_it_to_cannot_be_built(void);
extern void test_a_lease_of_no_duration_runs_no_t1_and_no_t2(void);
extern void test_an_acknowledgement_with_no_lease_option_keeps_the_duration_already_held(void);
extern void test_a_tick_before_the_deadline_sends_nothing(void);
extern void test_an_overload_naming_both_fields_is_read_once(void);
extern void test_input_with_no_message_is_refused(void);
extern void test_start_owes_nothing_until_the_section_441_delay_passes(void);
extern void test_the_start_delay_lands_between_one_and_ten_seconds(void);
extern void test_start_is_refused_while_a_transaction_runs(void);
extern void test_the_discover_carries_the_table_5_fields(void);
extern void test_a_built_message_spans_the_minimal_bootp_header(void);
extern void test_the_broadcast_flag_follows_the_configuration(void);
extern void test_an_offer_without_a_server_identifier_is_not_selected(void);
extern void test_an_offer_records_the_parameters_and_moves_to_requesting(void);
extern void test_the_dns_option_reports_every_address_where_it_lies(void);
extern void test_the_request_out_of_selecting_names_the_server_and_the_address(void);
extern void test_an_ack_with_no_t1_or_t2_takes_the_section_445_defaults(void);
extern void test_an_ordered_t1_and_t2_from_the_server_are_taken(void);
extern void test_a_t1_after_t2_falls_back_to_the_section_445_defaults(void);
extern void test_a_t2_past_the_lease_falls_back_to_the_section_445_defaults(void);
extern void test_t1_moves_bound_to_renewing_and_unicasts_to_the_leasing_server(void);
extern void test_t2_moves_to_rebinding_and_broadcasts(void);
extern void test_an_ack_in_renewing_returns_the_machine_to_bound(void);
extern void test_the_lease_expiry_returns_the_machine_to_init_with_no_address(void);
extern void test_an_infinite_lease_runs_no_deadline(void);
extern void test_a_renewing_retransmission_waits_half_the_time_left_to_t2(void);
extern void test_the_discover_backoff_doubles_from_four_seconds_to_sixty_four(void);
extern void test_the_backoff_jitter_stays_inside_one_second(void);
extern void test_a_request_that_is_never_answered_reverts_to_init(void);
extern void test_a_message_with_a_foreign_xid_is_discarded(void);
extern void test_a_message_with_the_wrong_cookie_is_discarded(void);
extern void test_a_message_with_a_foreign_chaddr_is_discarded(void);
extern void test_a_message_that_is_not_a_bootreply_is_discarded(void);
extern void test_an_ack_in_selecting_is_discarded(void);
extern void test_bound_discards_an_offer_an_ack_and_a_nak(void);
extern void test_a_nak_in_requesting_returns_the_machine_to_init(void);
extern void test_a_nak_in_renewing_halts_the_network(void);
extern void test_a_client_message_type_from_a_server_is_discarded(void);
extern void test_an_option_running_past_the_message_is_discarded(void);
extern void test_an_option_with_the_wrong_length_is_discarded(void);
extern void test_a_router_option_that_is_not_a_multiple_of_four_is_discarded(void);
extern void test_a_repeated_option_takes_the_first(void);
extern void test_options_overloaded_into_file_and_sname_are_read(void);
extern void test_an_illegal_overload_value_is_discarded(void);
extern void test_a_message_with_no_message_type_option_is_discarded(void);
extern void test_a_message_shorter_than_the_fixed_part_is_discarded(void);
extern void test_a_known_address_reboots_with_a_broadcast_request(void);
extern void test_a_rebooting_ack_from_any_server_binds_the_lease(void);
extern void test_a_release_unicasts_to_the_server_and_ends_the_lease(void);
extern void test_a_release_without_a_lease_is_refused(void);
extern void test_a_decline_names_the_address_already_in_use(void);
extern void test_a_restart_after_a_decline_waits_ten_seconds(void);
extern void test_a_decline_before_the_ack_is_refused(void);
extern void test_an_inform_carries_the_external_address_and_no_lease_options(void);
extern void test_the_ack_answering_an_inform_sets_parameters_and_no_lease(void);
extern void test_an_inform_gives_up_after_four_tries(void);
extern void test_an_inform_without_an_address_is_refused(void);
extern void test_stop_halts_the_machine_and_repeats(void);
extern void test_build_refuses_a_buffer_shorter_than_the_bootp_minimum(void);
extern void test_build_with_nothing_owed_is_busy(void);
extern void test_two_borrows_run_independent_exchanges(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/dhcp/test_dhcp4\\test_dhcp4.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 79);
  run_test(test_the_published_offsets_are_ordered_and_fit, "test_the_published_offsets_are_ordered_and_fit", 96);
  run_test(test_the_io_macro_lands_on_the_published_offset, "test_the_io_macro_lands_on_the_published_offset", 105);
  run_test(test_clear_zeroes_the_regions, "test_clear_zeroes_the_regions", 112);
  run_test(test_clear_touches_one_borrow_only, "test_clear_touches_one_borrow_only", 132);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 146);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 171);
  run_test(test_unbound_borrow_refuses_work, "test_unbound_borrow_refuses_work", 189);
  run_test(test_clear_does_not_bind, "test_clear_does_not_bind", 210);
  run_test(test_bind_refuses_null_cfg, "test_bind_refuses_null_cfg", 220);
  run_test(test_bind_refuses_an_unusable_cfg, "test_bind_refuses_an_unusable_cfg", 229);
  run_test(test_bind_accepts_a_complete_cfg, "test_bind_accepts_a_complete_cfg", 253);
  run_test(test_the_states_of_figure_5_are_distinct, "test_the_states_of_figure_5_are_distinct", 263);
  run_test(test_the_message_types_and_ports_are_as_the_rfc_prints_them, "test_the_message_types_and_ports_are_as_the_rfc_prints_them", 273);
  run_test(test_an_option_of_the_wrong_length_discards_the_message, "test_an_option_of_the_wrong_length_discards_the_message", 491);
  run_test(test_the_first_occurrence_of_each_option_is_the_one_read, "test_the_first_occurrence_of_each_option_is_the_one_read", 534);
  run_test(test_the_first_occurrence_of_the_remaining_options_is_the_one_read, "test_the_first_occurrence_of_the_remaining_options_is_the_one_read", 562);
  run_test(test_an_option_area_that_ends_without_an_end_option_is_still_read, "test_an_option_area_that_ends_without_an_end_option_is_still_read", 599);
  run_test(test_an_option_running_off_the_end_of_the_area_discards_the_message, "test_an_option_running_off_the_end_of_the_area_discards_the_message", 620);
  run_test(test_an_option_running_off_the_end_of_an_overloaded_field_discards_the_message, "test_an_option_running_off_the_end_of_an_overloaded_field_discards_the_message", 658);
  run_test(test_a_pad_and_an_unread_option_are_stepped_over, "test_a_pad_and_an_unread_option_are_stepped_over", 694);
  run_test(test_the_renewal_interval_is_floored_at_sixty_seconds, "test_the_renewal_interval_is_floored_at_sixty_seconds", 737);
  run_test(test_a_reply_naming_another_hardware_type_or_length_is_discarded, "test_a_reply_naming_another_hardware_type_or_length_is_discarded", 761);
  run_test(test_an_inform_goes_to_the_server_the_last_answer_named, "test_an_inform_goes_to_the_server_the_last_answer_named", 792);
  run_test(test_release_decline_and_inform_each_refuse_what_no_tick_fixes, "test_release_decline_and_inform_each_refuse_what_no_tick_fixes", 829);
  run_test(test_a_unicast_owed_with_no_server_to_send_it_to_cannot_be_built, "test_a_unicast_owed_with_no_server_to_send_it_to_cannot_be_built", 876);
  run_test(test_a_lease_of_no_duration_runs_no_t1_and_no_t2, "test_a_lease_of_no_duration_runs_no_t1_and_no_t2", 895);
  run_test(test_an_acknowledgement_with_no_lease_option_keeps_the_duration_already_held, "test_an_acknowledgement_with_no_lease_option_keeps_the_duration_already_held", 916);
  run_test(test_a_tick_before_the_deadline_sends_nothing, "test_a_tick_before_the_deadline_sends_nothing", 937);
  run_test(test_an_overload_naming_both_fields_is_read_once, "test_an_overload_naming_both_fields_is_read_once", 955);
  run_test(test_input_with_no_message_is_refused, "test_input_with_no_message_is_refused", 984);
  run_test(test_start_owes_nothing_until_the_section_441_delay_passes, "test_start_owes_nothing_until_the_section_441_delay_passes", 1000);
  run_test(test_the_start_delay_lands_between_one_and_ten_seconds, "test_the_start_delay_lands_between_one_and_ten_seconds", 1024);
  run_test(test_start_is_refused_while_a_transaction_runs, "test_start_is_refused_while_a_transaction_runs", 1043);
  run_test(test_the_discover_carries_the_table_5_fields, "test_the_discover_carries_the_table_5_fields", 1055);
  run_test(test_a_built_message_spans_the_minimal_bootp_header, "test_a_built_message_spans_the_minimal_bootp_header", 1110);
  run_test(test_the_broadcast_flag_follows_the_configuration, "test_the_broadcast_flag_follows_the_configuration", 1138);
  run_test(test_an_offer_without_a_server_identifier_is_not_selected, "test_an_offer_without_a_server_identifier_is_not_selected", 1154);
  run_test(test_an_offer_records_the_parameters_and_moves_to_requesting, "test_an_offer_records_the_parameters_and_moves_to_requesting", 1169);
  run_test(test_the_dns_option_reports_every_address_where_it_lies, "test_the_dns_option_reports_every_address_where_it_lies", 1185);
  run_test(test_the_request_out_of_selecting_names_the_server_and_the_address, "test_the_request_out_of_selecting_names_the_server_and_the_address", 1200);
  run_test(test_an_ack_with_no_t1_or_t2_takes_the_section_445_defaults, "test_an_ack_with_no_t1_or_t2_takes_the_section_445_defaults", 1226);
  run_test(test_an_ordered_t1_and_t2_from_the_server_are_taken, "test_an_ordered_t1_and_t2_from_the_server_are_taken", 1238);
  run_test(test_a_t1_after_t2_falls_back_to_the_section_445_defaults, "test_a_t1_after_t2_falls_back_to_the_section_445_defaults", 1257);
  run_test(test_a_t2_past_the_lease_falls_back_to_the_section_445_defaults, "test_a_t2_past_the_lease_falls_back_to_the_section_445_defaults", 1275);
  run_test(test_t1_moves_bound_to_renewing_and_unicasts_to_the_leasing_server, "test_t1_moves_bound_to_renewing_and_unicasts_to_the_leasing_server", 1296);
  run_test(test_t2_moves_to_rebinding_and_broadcasts, "test_t2_moves_to_rebinding_and_broadcasts", 1321);
  run_test(test_an_ack_in_renewing_returns_the_machine_to_bound, "test_an_ack_in_renewing_returns_the_machine_to_bound", 1335);
  run_test(test_the_lease_expiry_returns_the_machine_to_init_with_no_address, "test_the_lease_expiry_returns_the_machine_to_init_with_no_address", 1356);
  run_test(test_an_infinite_lease_runs_no_deadline, "test_an_infinite_lease_runs_no_deadline", 1369);
  run_test(test_a_renewing_retransmission_waits_half_the_time_left_to_t2, "test_a_renewing_retransmission_waits_half_the_time_left_to_t2", 1382);
  run_test(test_the_discover_backoff_doubles_from_four_seconds_to_sixty_four, "test_the_discover_backoff_doubles_from_four_seconds_to_sixty_four", 1403);
  run_test(test_the_backoff_jitter_stays_inside_one_second, "test_the_backoff_jitter_stays_inside_one_second", 1426);
  run_test(test_a_request_that_is_never_answered_reverts_to_init, "test_a_request_that_is_never_answered_reverts_to_init", 1443);
  run_test(test_a_message_with_a_foreign_xid_is_discarded, "test_a_message_with_a_foreign_xid_is_discarded", 1464);
  run_test(test_a_message_with_the_wrong_cookie_is_discarded, "test_a_message_with_the_wrong_cookie_is_discarded", 1477);
  run_test(test_a_message_with_a_foreign_chaddr_is_discarded, "test_a_message_with_a_foreign_chaddr_is_discarded", 1491);
  run_test(test_a_message_that_is_not_a_bootreply_is_discarded, "test_a_message_that_is_not_a_bootreply_is_discarded", 1504);
  run_test(test_an_ack_in_selecting_is_discarded, "test_an_ack_in_selecting_is_discarded", 1516);
  run_test(test_bound_discards_an_offer_an_ack_and_a_nak, "test_bound_discards_an_offer_an_ack_and_a_nak", 1531);
  run_test(test_a_nak_in_requesting_returns_the_machine_to_init, "test_a_nak_in_requesting_returns_the_machine_to_init", 1558);
  run_test(test_a_nak_in_renewing_halts_the_network, "test_a_nak_in_renewing_halts_the_network", 1574);
  run_test(test_a_client_message_type_from_a_server_is_discarded, "test_a_client_message_type_from_a_server_is_discarded", 1589);
  run_test(test_an_option_running_past_the_message_is_discarded, "test_an_option_running_past_the_message_is_discarded", 1604);
  run_test(test_an_option_with_the_wrong_length_is_discarded, "test_an_option_with_the_wrong_length_is_discarded", 1617);
  run_test(test_a_router_option_that_is_not_a_multiple_of_four_is_discarded, "test_a_router_option_that_is_not_a_multiple_of_four_is_discarded", 1631);
  run_test(test_a_repeated_option_takes_the_first, "test_a_repeated_option_takes_the_first", 1645);
  run_test(test_options_overloaded_into_file_and_sname_are_read, "test_options_overloaded_into_file_and_sname_are_read", 1661);
  run_test(test_an_illegal_overload_value_is_discarded, "test_an_illegal_overload_value_is_discarded", 1693);
  run_test(test_a_message_with_no_message_type_option_is_discarded, "test_a_message_with_no_message_type_option_is_discarded", 1707);
  run_test(test_a_message_shorter_than_the_fixed_part_is_discarded, "test_a_message_shorter_than_the_fixed_part_is_discarded", 1726);
  run_test(test_a_known_address_reboots_with_a_broadcast_request, "test_a_known_address_reboots_with_a_broadcast_request", 1742);
  run_test(test_a_rebooting_ack_from_any_server_binds_the_lease, "test_a_rebooting_ack_from_any_server_binds_the_lease", 1769);
  run_test(test_a_release_unicasts_to_the_server_and_ends_the_lease, "test_a_release_unicasts_to_the_server_and_ends_the_lease", 1793);
  run_test(test_a_release_without_a_lease_is_refused, "test_a_release_without_a_lease_is_refused", 1819);
  run_test(test_a_decline_names_the_address_already_in_use, "test_a_decline_names_the_address_already_in_use", 1829);
  run_test(test_a_restart_after_a_decline_waits_ten_seconds, "test_a_restart_after_a_decline_waits_ten_seconds", 1854);
  run_test(test_a_decline_before_the_ack_is_refused, "test_a_decline_before_the_ack_is_refused", 1872);
  run_test(test_an_inform_carries_the_external_address_and_no_lease_options, "test_an_inform_carries_the_external_address_and_no_lease_options", 1886);
  run_test(test_the_ack_answering_an_inform_sets_parameters_and_no_lease, "test_the_ack_answering_an_inform_sets_parameters_and_no_lease", 1913);
  run_test(test_an_inform_gives_up_after_four_tries, "test_an_inform_gives_up_after_four_tries", 1940);
  run_test(test_an_inform_without_an_address_is_refused, "test_an_inform_without_an_address_is_refused", 1967);
  run_test(test_stop_halts_the_machine_and_repeats, "test_stop_halts_the_machine_and_repeats", 1979);
  run_test(test_build_refuses_a_buffer_shorter_than_the_bootp_minimum, "test_build_refuses_a_buffer_shorter_than_the_bootp_minimum", 2002);
  run_test(test_build_with_nothing_owed_is_busy, "test_build_with_nothing_owed_is_busy", 2019);
  run_test(test_two_borrows_run_independent_exchanges, "test_two_borrows_run_independent_exchanges", 2033);

  return UNITY_END();
}
