/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/udp/udp.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_field_offsets_are_the_rfc_768_figure(void);
extern void test_accessors_read_the_figure_fields(void);
extern void test_accessors_read_at_an_odd_address(void);
extern void test_two_headers_side_by_side_do_not_read_each_other(void);
extern void test_length_of_eight_is_the_minimum(void);
extern void test_length_below_eight_is_refused(void);
extern void test_payload_len_is_length_less_the_header(void);
extern void test_a_short_length_cannot_wrap_the_payload_len(void);
extern void test_build_writes_the_four_fields_and_clears_the_checksum(void);
extern void test_build_round_trips_through_the_accessors(void);
extern void test_each_setter_writes_only_its_own_field(void);
extern void test_an_unused_source_port_is_zero(void);
extern void test_checksum_over_an_odd_length_datagram(void);
extern void test_checksum_over_an_even_length_datagram(void);
extern void test_checksum_over_a_bare_header(void);
extern void test_a_computed_zero_is_transmitted_as_all_ones(void);
extern void test_all_zero_means_no_checksum_was_generated(void);
extern void test_compute_never_returns_the_no_checksum_value(void);
extern void test_the_pseudo_header_covers_the_addresses_the_protocol_and_the_length(void);
extern void test_udp_is_protocol_seventeen(void);
extern void test_cksum_write_stores_what_compute_returned(void);
extern void test_cksum_write_repeats(void);
extern void test_a_carried_checksum_verifies_and_a_flipped_bit_does_not(void);
extern void test_a_misrouted_datagram_does_not_verify(void);
extern void test_the_all_ones_substitution_verifies(void);
extern void test_coverage_replaces_length_in_place(void);
extern void test_udplite_is_protocol_one_hundred_thirty_six(void);
extern void test_coverage_of_zero_covers_the_whole_packet(void);
extern void test_coverage_of_one_through_seven_is_discarded(void);
extern void test_coverage_past_the_ip_length_is_discarded(void);
extern void test_a_payload_shorter_than_the_header_is_discarded(void);
extern void test_udplite_build_writes_coverage_and_clears_the_checksum(void);
extern void test_checksum_at_coverage_eight(void);
extern void test_octets_past_the_coverage_do_not_enter_the_sum(void);
extern void test_coverage_of_twelve_covers_four_payload_octets(void);
extern void test_checksum_at_full_coverage(void);
extern void test_the_pseudo_header_length_comes_from_the_ip_module(void);
extern void test_a_computed_zero_at_partial_coverage_is_all_ones(void);
extern void test_udplite_cksum_write_stores_what_compute_returned(void);
extern void test_udplite_verifies_over_its_coverage_only(void);
extern void test_udplite_never_transmits_an_all_zero_checksum(void);
extern void test_coverage_eight_still_covers_the_coverage_field(void);
extern void test_coverage_is_sixteen_bits(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/udp/test_udp\\test_udp.c");
  run_test(test_field_offsets_are_the_rfc_768_figure, "test_field_offsets_are_the_rfc_768_figure", 80);
  run_test(test_accessors_read_the_figure_fields, "test_accessors_read_the_figure_fields", 89);
  run_test(test_accessors_read_at_an_odd_address, "test_accessors_read_at_an_odd_address", 99);
  run_test(test_two_headers_side_by_side_do_not_read_each_other, "test_two_headers_side_by_side_do_not_read_each_other", 110);
  run_test(test_length_of_eight_is_the_minimum, "test_length_of_eight_is_the_minimum", 125);
  run_test(test_length_below_eight_is_refused, "test_length_below_eight_is_refused", 132);
  run_test(test_payload_len_is_length_less_the_header, "test_payload_len_is_length_less_the_header", 142);
  run_test(test_a_short_length_cannot_wrap_the_payload_len, "test_a_short_length_cannot_wrap_the_payload_len", 150);
  run_test(test_build_writes_the_four_fields_and_clears_the_checksum, "test_build_writes_the_four_fields_and_clears_the_checksum", 161);
  run_test(test_build_round_trips_through_the_accessors, "test_build_round_trips_through_the_accessors", 169);
  run_test(test_each_setter_writes_only_its_own_field, "test_each_setter_writes_only_its_own_field", 179);
  run_test(test_an_unused_source_port_is_zero, "test_an_unused_source_port_is_zero", 201);
  run_test(test_checksum_over_an_odd_length_datagram, "test_checksum_over_an_odd_length_datagram", 212);
  run_test(test_checksum_over_an_even_length_datagram, "test_checksum_over_an_even_length_datagram", 217);
  run_test(test_checksum_over_a_bare_header, "test_checksum_over_a_bare_header", 222);
  run_test(test_a_computed_zero_is_transmitted_as_all_ones, "test_a_computed_zero_is_transmitted_as_all_ones", 230);
  run_test(test_all_zero_means_no_checksum_was_generated, "test_all_zero_means_no_checksum_was_generated", 243);
  run_test(test_compute_never_returns_the_no_checksum_value, "test_compute_never_returns_the_no_checksum_value", 256);
  run_test(test_the_pseudo_header_covers_the_addresses_the_protocol_and_the_length, "test_the_pseudo_header_covers_the_addresses_the_protocol_and_the_length", 271);
  run_test(test_udp_is_protocol_seventeen, "test_udp_is_protocol_seventeen", 287);
  run_test(test_cksum_write_stores_what_compute_returned, "test_cksum_write_stores_what_compute_returned", 293);
  run_test(test_cksum_write_repeats, "test_cksum_write_repeats", 303);
  run_test(test_a_carried_checksum_verifies_and_a_flipped_bit_does_not, "test_a_carried_checksum_verifies_and_a_flipped_bit_does_not", 313);
  run_test(test_a_misrouted_datagram_does_not_verify, "test_a_misrouted_datagram_does_not_verify", 330);
  run_test(test_the_all_ones_substitution_verifies, "test_the_all_ones_substitution_verifies", 339);
  run_test(test_coverage_replaces_length_in_place, "test_coverage_replaces_length_in_place", 351);
  run_test(test_udplite_is_protocol_one_hundred_thirty_six, "test_udplite_is_protocol_one_hundred_thirty_six", 361);
  run_test(test_coverage_of_zero_covers_the_whole_packet, "test_coverage_of_zero_covers_the_whole_packet", 369);
  run_test(test_coverage_of_one_through_seven_is_discarded, "test_coverage_of_one_through_seven_is_discarded", 379);
  run_test(test_coverage_past_the_ip_length_is_discarded, "test_coverage_past_the_ip_length_is_discarded", 393);
  run_test(test_a_payload_shorter_than_the_header_is_discarded, "test_a_payload_shorter_than_the_header_is_discarded", 402);
  run_test(test_udplite_build_writes_coverage_and_clears_the_checksum, "test_udplite_build_writes_coverage_and_clears_the_checksum", 414);
  run_test(test_checksum_at_coverage_eight, "test_checksum_at_coverage_eight", 426);
  run_test(test_octets_past_the_coverage_do_not_enter_the_sum, "test_octets_past_the_coverage_do_not_enter_the_sum", 433);
  run_test(test_coverage_of_twelve_covers_four_payload_octets, "test_coverage_of_twelve_covers_four_payload_octets", 449);
  run_test(test_checksum_at_full_coverage, "test_checksum_at_full_coverage", 463);
  run_test(test_the_pseudo_header_length_comes_from_the_ip_module, "test_the_pseudo_header_length_comes_from_the_ip_module", 479);
  run_test(test_a_computed_zero_at_partial_coverage_is_all_ones, "test_a_computed_zero_at_partial_coverage_is_all_ones", 486);
  run_test(test_udplite_cksum_write_stores_what_compute_returned, "test_udplite_cksum_write_stores_what_compute_returned", 496);
  run_test(test_udplite_verifies_over_its_coverage_only, "test_udplite_verifies_over_its_coverage_only", 506);
  run_test(test_udplite_never_transmits_an_all_zero_checksum, "test_udplite_never_transmits_an_all_zero_checksum", 531);
  run_test(test_coverage_eight_still_covers_the_coverage_field, "test_coverage_eight_still_covers_the_coverage_field", 544);
  run_test(test_coverage_is_sixteen_bits, "test_coverage_is_sixteen_bits", 554);

  return UNITY_END();
}
