/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/ip/ip6_addr.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_uncleared_borrow_refuses_work(void);
extern void test_a_null_address_is_refused(void);
extern void test_sec2_4_unspecified_and_loopback(void);
extern void test_sec2_4_multicast_and_link_local(void);
extern void test_sec2_4_global_unicast_is_everything_else(void);
extern void test_sec2_5_7_site_local_is_fec0_slash_10(void);
extern void test_sec2_5_5_embedded_ipv4_forms(void);
extern void test_sec2_7_ntp_group_scopes(void);
extern void test_sec2_7_transient_flag(void);
extern void test_a_unicast_address_reports_no_multicast_flags(void);
extern void test_sec2_7_1_worked_example(void);
extern void test_sec2_7_1_range_endpoints(void);
extern void test_sec2_7_1_high_order_bits_alias(void);
extern void test_solicited_refuses_a_multicast_or_unspecified_address(void);
extern void test_rfc4007_link_local_takes_the_interface_index(void);
extern void test_rfc4007_interface_local_multicast_takes_the_interface_index(void);
extern void test_rfc4007_global_scope_is_the_default_zone(void);
extern void test_rfc4007_a_site_zone_is_not_derived(void);
extern void test_a_reserved_scop_of_zero_has_no_zone(void);
extern void test_a_reserved_scop_of_f_takes_the_global_zone(void);
extern void test_the_unspecified_address_has_no_scope(void);
extern void test_the_loopback_address_has_link_local_scope(void);
extern void test_the_same_link_local_address_in_two_zones_is_not_one_interface(void);
extern void test_the_default_zone_matches_whatever_the_other_names(void);
extern void test_a_global_address_ignores_zone_indices(void);
extern void test_prefix_equality_over_the_leading_bits(void);
extern void test_a_prefix_longer_than_the_address_is_refused(void);
extern void test_no_entry_ever_reports_busy(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/ip/test_ip6_addr\\test_ip6_addr.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 92);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 102);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 120);
  run_test(test_uncleared_borrow_refuses_work, "test_uncleared_borrow_refuses_work", 141);
  run_test(test_a_null_address_is_refused, "test_a_null_address_is_refused", 160);
  run_test(test_sec2_4_unspecified_and_loopback, "test_sec2_4_unspecified_and_loopback", 175);
  run_test(test_sec2_4_multicast_and_link_local, "test_sec2_4_multicast_and_link_local", 188);
  run_test(test_sec2_4_global_unicast_is_everything_else, "test_sec2_4_global_unicast_is_everything_else", 206);
  run_test(test_sec2_5_7_site_local_is_fec0_slash_10, "test_sec2_5_7_site_local_is_fec0_slash_10", 218);
  run_test(test_sec2_5_5_embedded_ipv4_forms, "test_sec2_5_5_embedded_ipv4_forms", 233);
  run_test(test_sec2_7_ntp_group_scopes, "test_sec2_7_ntp_group_scopes", 255);
  run_test(test_sec2_7_transient_flag, "test_sec2_7_transient_flag", 278);
  run_test(test_a_unicast_address_reports_no_multicast_flags, "test_a_unicast_address_reports_no_multicast_flags", 293);
  run_test(test_sec2_7_1_worked_example, "test_sec2_7_1_worked_example", 305);
  run_test(test_sec2_7_1_range_endpoints, "test_sec2_7_1_range_endpoints", 318);
  run_test(test_sec2_7_1_high_order_bits_alias, "test_sec2_7_1_high_order_bits_alias", 336);
  run_test(test_solicited_refuses_a_multicast_or_unspecified_address, "test_solicited_refuses_a_multicast_or_unspecified_address", 354);
  run_test(test_rfc4007_link_local_takes_the_interface_index, "test_rfc4007_link_local_takes_the_interface_index", 372);
  run_test(test_rfc4007_interface_local_multicast_takes_the_interface_index, "test_rfc4007_interface_local_multicast_takes_the_interface_index", 384);
  run_test(test_rfc4007_global_scope_is_the_default_zone, "test_rfc4007_global_scope_is_the_default_zone", 396);
  run_test(test_rfc4007_a_site_zone_is_not_derived, "test_rfc4007_a_site_zone_is_not_derived", 408);
  run_test(test_a_reserved_scop_of_zero_has_no_zone, "test_a_reserved_scop_of_zero_has_no_zone", 421);
  run_test(test_a_reserved_scop_of_f_takes_the_global_zone, "test_a_reserved_scop_of_f_takes_the_global_zone", 432);
  run_test(test_the_unspecified_address_has_no_scope, "test_the_unspecified_address_has_no_scope", 444);
  run_test(test_the_loopback_address_has_link_local_scope, "test_the_loopback_address_has_link_local_scope", 456);
  run_test(test_the_same_link_local_address_in_two_zones_is_not_one_interface, "test_the_same_link_local_address_in_two_zones_is_not_one_interface", 468);
  run_test(test_the_default_zone_matches_whatever_the_other_names, "test_the_default_zone_matches_whatever_the_other_names", 488);
  run_test(test_a_global_address_ignores_zone_indices, "test_a_global_address_ignores_zone_indices", 503);
  run_test(test_prefix_equality_over_the_leading_bits, "test_prefix_equality_over_the_leading_bits", 518);
  run_test(test_a_prefix_longer_than_the_address_is_refused, "test_a_prefix_longer_than_the_address_is_refused", 545);
  run_test(test_no_entry_ever_reports_busy, "test_no_entry_ever_reports_busy", 557);

  return UNITY_END();
}
