/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/nd/nd6.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_clear_on_one_borrow_leaves_the_other_untouched(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_every_published_offset_is_aligned(void);
extern void test_the_io_macro_reaches_the_operand_block(void);
extern void test_clear_reports_ok(void);
extern void test_clear_zeroes_the_tables(void);
extern void test_clear_zeroes_the_context_apart_from_the_cleared_mark(void);
extern void test_clear_leaves_the_operand_block_alone(void);
extern void test_clear_is_idempotent(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_clearing_one_borrow_does_not_ready_the_other(void);
extern void test_none_is_outside_every_table(void);
extern void test_the_five_reachability_states_are_distinct_and_one_octet(void);
extern void test_the_infinite_lifetime_is_all_one_bits(void);
extern void test_the_random_factors_are_shifts_of_base_reachable_time(void);
extern void test_a_full_destination_cache_is_busy(void);
extern void test_a_destination_with_no_next_hop_is_not_recorded(void);
extern void test_a_full_prefix_list_is_busy(void);
extern void test_a_full_default_router_list_is_busy(void);
extern void test_an_l_clear_option_does_not_cancel_an_on_link_indication(void);
extern void test_an_l_clear_option_takes_no_prefix_list_slot(void);
extern void test_a_zero_router_lifetime_still_records_the_link_layer_address(void);
extern void test_dropping_a_default_router_leaves_is_router_alone(void);
extern void test_a_prefix_length_that_is_not_a_whole_number_of_octets_matches_on_its_bits(void);
extern void test_a_shorter_prefix_matching_the_same_address_does_not_displace_the_longer(void);
extern void test_a_router_advertisement_with_no_neighbor_slot_left_is_busy(void);
extern void test_a_router_advertising_a_new_link_layer_address_takes_the_entry_to_stale(void);
extern void test_a_push_with_every_queue_entry_held_elsewhere_is_busy(void);
extern void test_every_entry_that_takes_an_address_refuses_a_null_one(void);
extern void test_every_entry_that_names_a_row_refuses_one_that_is_not_in_use(void);
extern void test_the_node_constants_are_the_ones_section_10_prints(void);
extern void test_an_entry_is_keyed_on_the_neighbors_address(void);
extern void test_a_created_entry_takes_the_state_the_caller_names(void);
extern void test_an_advertisement_resolving_an_incomplete_entry_uses_the_solicited_flag(void);
extern void test_an_advertisement_with_no_link_layer_address_leaves_an_incomplete_entry_alone(void);
extern void test_an_override_clear_advertisement_makes_a_reachable_entry_stale_and_keeps_the_address(void);
extern void test_an_override_clear_advertisement_is_ignored_outside_reachable(void);
extern void test_an_override_set_solicited_advertisement_replaces_the_address_and_makes_it_reachable(void);
extern void test_an_unsolicited_advertisement_changes_the_state_only_when_the_address_changes(void);
extern void test_the_router_flag_going_false_removes_the_router_from_the_default_router_list(void);
extern void test_a_full_neighbor_cache_is_busy(void);
extern void test_confirm_makes_an_entry_reachable_but_not_an_incomplete_one(void);
extern void test_a_packet_to_a_stale_neighbor_makes_it_delay_and_leaves_reachable_alone(void);
extern void test_reachable_becomes_stale_after_reachable_time(void);
extern void test_delay_becomes_probe_and_sends_a_unicast_solicitation(void);
extern void test_an_incomplete_entry_multicasts_a_solicitation_once_per_retrans_timer(void);
extern void test_an_unanswered_incomplete_entry_is_deleted_after_max_multicast_solicit(void);
extern void test_a_retrans_timer_past_the_deadline_span_still_rate_limits(void);
extern void test_a_probe_stops_after_max_unicast_solicit_and_a_confirmation_returns_it_to_reachable(void);
extern void test_an_unanswered_probe_deletes_the_entry(void);
extern void test_queued_frames_come_back_in_arrival_order(void);
extern void test_a_full_queue_replaces_the_oldest_and_hands_its_descriptor_back(void);
extern void test_removing_a_neighbor_hands_back_every_queued_descriptor_first(void);
extern void test_a_failed_resolution_releases_its_queued_descriptor_before_deleting_the_entry(void);
extern void test_a_prefix_with_a_non_zero_lifetime_is_installed_and_makes_its_addresses_on_link(void);
extern void test_a_zero_lifetime_on_an_unlisted_prefix_is_silently_ignored(void);
extern void test_a_zero_lifetime_times_out_a_listed_prefix(void);
extern void test_a_second_advertisement_resets_the_invalidation_timer(void);
extern void test_an_expired_prefix_makes_its_addresses_off_link_again(void);
extern void test_an_infinite_lifetime_prefix_never_expires(void);
extern void test_the_link_local_prefix_is_ignored_as_an_option_and_on_link_regardless(void);
extern void test_the_longest_matching_prefix_wins(void);
extern void test_an_address_with_no_on_link_information_is_off_link(void);
extern void test_a_prefix_without_the_l_flag_conveys_no_on_link_information(void);
extern void test_a_multicast_destination_is_on_link(void);
extern void test_a_prefix_length_past_128_is_refused(void);
extern void test_a_router_advertising_its_link_layer_address_is_listed_and_cached_stale(void);
extern void test_a_router_advertising_no_link_layer_address_is_listed_without_a_cache_entry(void);
extern void test_a_later_advertisement_with_a_link_layer_address_fills_the_cache_entry(void);
extern void test_a_zero_lifetime_on_an_unlisted_router_creates_nothing(void);
extern void test_a_zero_lifetime_times_out_a_listed_router(void);
extern void test_a_router_lifetime_expires_the_entry(void);
extern void test_removing_a_router_makes_its_destinations_redo_next_hop_determination(void);
extern void test_select_prefers_a_router_that_is_not_incomplete(void);
extern void test_select_prefers_a_reachable_router_over_a_stale_one(void);
extern void test_select_round_robins_among_routers_of_unknown_reachability(void);
extern void test_select_on_an_empty_default_router_list_is_an_error(void);
extern void test_a_destination_maps_to_its_next_hop_and_path_mtu(void);
extern void test_a_redirect_revises_the_next_hop_and_keeps_the_path_mtu(void);
extern void test_finding_an_unknown_destination_is_an_error(void);
extern void test_an_unspecified_field_leaves_the_host_variable_alone(void);
extern void test_reachable_time_is_drawn_between_the_two_random_factors(void);
extern void test_a_repeated_reachable_time_does_not_redraw(void);
extern void test_an_mtu_option_outside_the_link_bounds_is_not_copied(void);
extern void test_the_advertised_retrans_timer_governs_the_solicitation_interval(void);
extern void test_a_sweep_with_nothing_due_is_busy(void);
extern void test_a_sweep_reports_the_soonest_deadline(void);
extern void test_the_machine_on_one_borrow_reaches_no_byte_of_another(void);
extern void test_a_router_advertised_from_a_global_address_names_no_router(void);
extern void test_a_router_advertised_from_a_link_local_address_names_one(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/nd/test_nd6\\test_nd6.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 89);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 97);
  run_test(test_clear_on_one_borrow_leaves_the_other_untouched, "test_clear_on_one_borrow_leaves_the_other_untouched", 119);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 137);
  run_test(test_every_published_offset_is_aligned, "test_every_published_offset_is_aligned", 161);
  run_test(test_the_io_macro_reaches_the_operand_block, "test_the_io_macro_reaches_the_operand_block", 172);
  run_test(test_clear_reports_ok, "test_clear_reports_ok", 180);
  run_test(test_clear_zeroes_the_tables, "test_clear_zeroes_the_tables", 188);
  run_test(test_clear_zeroes_the_context_apart_from_the_cleared_mark, "test_clear_zeroes_the_context_apart_from_the_cleared_mark", 201);
  run_test(test_clear_leaves_the_operand_block_alone, "test_clear_leaves_the_operand_block_alone", 217);
  run_test(test_clear_is_idempotent, "test_clear_is_idempotent", 229);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 240);
  run_test(test_clearing_one_borrow_does_not_ready_the_other, "test_clearing_one_borrow_does_not_ready_the_other", 281);
  run_test(test_none_is_outside_every_table, "test_none_is_outside_every_table", 292);
  run_test(test_the_five_reachability_states_are_distinct_and_one_octet, "test_the_five_reachability_states_are_distinct_and_one_octet", 303);
  run_test(test_the_infinite_lifetime_is_all_one_bits, "test_the_infinite_lifetime_is_all_one_bits", 314);
  run_test(test_the_random_factors_are_shifts_of_base_reachable_time, "test_the_random_factors_are_shifts_of_base_reachable_time", 321);
  run_test(test_a_full_destination_cache_is_busy, "test_a_full_destination_cache_is_busy", 445);
  run_test(test_a_destination_with_no_next_hop_is_not_recorded, "test_a_destination_with_no_next_hop_is_not_recorded", 475);
  run_test(test_a_full_prefix_list_is_busy, "test_a_full_prefix_list_is_busy", 491);
  run_test(test_a_full_default_router_list_is_busy, "test_a_full_default_router_list_is_busy", 518);
  run_test(test_an_l_clear_option_does_not_cancel_an_on_link_indication, "test_an_l_clear_option_does_not_cancel_an_on_link_indication", 536);
  run_test(test_an_l_clear_option_takes_no_prefix_list_slot, "test_an_l_clear_option_takes_no_prefix_list_slot", 559);
  run_test(test_a_zero_router_lifetime_still_records_the_link_layer_address, "test_a_zero_router_lifetime_still_records_the_link_layer_address", 581);
  run_test(test_dropping_a_default_router_leaves_is_router_alone, "test_dropping_a_default_router_leaves_is_router_alone", 600);
  run_test(test_a_prefix_length_that_is_not_a_whole_number_of_octets_matches_on_its_bits, "test_a_prefix_length_that_is_not_a_whole_number_of_octets_matches_on_its_bits", 639);
  run_test(test_a_shorter_prefix_matching_the_same_address_does_not_displace_the_longer, "test_a_shorter_prefix_matching_the_same_address_does_not_displace_the_longer", 667);
  run_test(test_a_router_advertisement_with_no_neighbor_slot_left_is_busy, "test_a_router_advertisement_with_no_neighbor_slot_left_is_busy", 690);
  run_test(test_a_router_advertising_a_new_link_layer_address_takes_the_entry_to_stale, "test_a_router_advertising_a_new_link_layer_address_takes_the_entry_to_stale", 709);
  run_test(test_a_push_with_every_queue_entry_held_elsewhere_is_busy, "test_a_push_with_every_queue_entry_held_elsewhere_is_busy", 739);
  run_test(test_every_entry_that_takes_an_address_refuses_a_null_one, "test_every_entry_that_takes_an_address_refuses_a_null_one", 773);
  run_test(test_every_entry_that_names_a_row_refuses_one_that_is_not_in_use, "test_every_entry_that_names_a_row_refuses_one_that_is_not_in_use", 812);
  run_test(test_the_node_constants_are_the_ones_section_10_prints, "test_the_node_constants_are_the_ones_section_10_prints", 840);
  run_test(test_an_entry_is_keyed_on_the_neighbors_address, "test_an_entry_is_keyed_on_the_neighbors_address", 853);
  run_test(test_a_created_entry_takes_the_state_the_caller_names, "test_a_created_entry_takes_the_state_the_caller_names", 871);
  run_test(test_an_advertisement_resolving_an_incomplete_entry_uses_the_solicited_flag, "test_an_advertisement_resolving_an_incomplete_entry_uses_the_solicited_flag", 886);
  run_test(test_an_advertisement_with_no_link_layer_address_leaves_an_incomplete_entry_alone, "test_an_advertisement_with_no_link_layer_address_leaves_an_incomplete_entry_alone", 903);
  run_test(test_an_override_clear_advertisement_makes_a_reachable_entry_stale_and_keeps_the_address, "test_an_override_clear_advertisement_makes_a_reachable_entry_stale_and_keeps_the_address", 915);
  run_test(test_an_override_clear_advertisement_is_ignored_outside_reachable, "test_an_override_clear_advertisement_is_ignored_outside_reachable", 929);
  run_test(test_an_override_set_solicited_advertisement_replaces_the_address_and_makes_it_reachable, "test_an_override_set_solicited_advertisement_replaces_the_address_and_makes_it_reachable", 942);
  run_test(test_an_unsolicited_advertisement_changes_the_state_only_when_the_address_changes, "test_an_unsolicited_advertisement_changes_the_state_only_when_the_address_changes", 955);
  run_test(test_the_router_flag_going_false_removes_the_router_from_the_default_router_list, "test_the_router_flag_going_false_removes_the_router_from_the_default_router_list", 972);
  run_test(test_a_full_neighbor_cache_is_busy, "test_a_full_neighbor_cache_is_busy", 990);
  run_test(test_confirm_makes_an_entry_reachable_but_not_an_incomplete_one, "test_confirm_makes_an_entry_reachable_but_not_an_incomplete_one", 1011);
  run_test(test_a_packet_to_a_stale_neighbor_makes_it_delay_and_leaves_reachable_alone, "test_a_packet_to_a_stale_neighbor_makes_it_delay_and_leaves_reachable_alone", 1032);
  run_test(test_reachable_becomes_stale_after_reachable_time, "test_reachable_becomes_stale_after_reachable_time", 1053);
  run_test(test_delay_becomes_probe_and_sends_a_unicast_solicitation, "test_delay_becomes_probe_and_sends_a_unicast_solicitation", 1071);
  run_test(test_an_incomplete_entry_multicasts_a_solicitation_once_per_retrans_timer, "test_an_incomplete_entry_multicasts_a_solicitation_once_per_retrans_timer", 1101);
  run_test(test_an_unanswered_incomplete_entry_is_deleted_after_max_multicast_solicit, "test_an_unanswered_incomplete_entry_is_deleted_after_max_multicast_solicit", 1127);
  run_test(test_a_retrans_timer_past_the_deadline_span_still_rate_limits, "test_a_retrans_timer_past_the_deadline_span_still_rate_limits", 1156);
  run_test(test_a_probe_stops_after_max_unicast_solicit_and_a_confirmation_returns_it_to_reachable, "test_a_probe_stops_after_max_unicast_solicit_and_a_confirmation_returns_it_to_reachable", 1183);
  run_test(test_an_unanswered_probe_deletes_the_entry, "test_an_unanswered_probe_deletes_the_entry", 1205);
  run_test(test_queued_frames_come_back_in_arrival_order, "test_queued_frames_come_back_in_arrival_order", 1227);
  run_test(test_a_full_queue_replaces_the_oldest_and_hands_its_descriptor_back, "test_a_full_queue_replaces_the_oldest_and_hands_its_descriptor_back", 1250);
  run_test(test_removing_a_neighbor_hands_back_every_queued_descriptor_first, "test_removing_a_neighbor_hands_back_every_queued_descriptor_first", 1273);
  run_test(test_a_failed_resolution_releases_its_queued_descriptor_before_deleting_the_entry, "test_a_failed_resolution_releases_its_queued_descriptor_before_deleting_the_entry", 1297);
  run_test(test_a_prefix_with_a_non_zero_lifetime_is_installed_and_makes_its_addresses_on_link, "test_a_prefix_with_a_non_zero_lifetime_is_installed_and_makes_its_addresses_on_link", 1326);
  run_test(test_a_zero_lifetime_on_an_unlisted_prefix_is_silently_ignored, "test_a_zero_lifetime_on_an_unlisted_prefix_is_silently_ignored", 1339);
  run_test(test_a_zero_lifetime_times_out_a_listed_prefix, "test_a_zero_lifetime_times_out_a_listed_prefix", 1351);
  run_test(test_a_second_advertisement_resets_the_invalidation_timer, "test_a_second_advertisement_resets_the_invalidation_timer", 1367);
  run_test(test_an_expired_prefix_makes_its_addresses_off_link_again, "test_an_expired_prefix_makes_its_addresses_off_link_again", 1388);
  run_test(test_an_infinite_lifetime_prefix_never_expires, "test_an_infinite_lifetime_prefix_never_expires", 1404);
  run_test(test_the_link_local_prefix_is_ignored_as_an_option_and_on_link_regardless, "test_the_link_local_prefix_is_ignored_as_an_option_and_on_link_regardless", 1418);
  run_test(test_the_longest_matching_prefix_wins, "test_the_longest_matching_prefix_wins", 1433);
  run_test(test_an_address_with_no_on_link_information_is_off_link, "test_an_address_with_no_on_link_information_is_off_link", 1452);
  run_test(test_a_prefix_without_the_l_flag_conveys_no_on_link_information, "test_a_prefix_without_the_l_flag_conveys_no_on_link_information", 1464);
  run_test(test_a_multicast_destination_is_on_link, "test_a_multicast_destination_is_on_link", 1475);
  run_test(test_a_prefix_length_past_128_is_refused, "test_a_prefix_length_past_128_is_refused", 1483);
  run_test(test_a_router_advertising_its_link_layer_address_is_listed_and_cached_stale, "test_a_router_advertising_its_link_layer_address_is_listed_and_cached_stale", 1499);
  run_test(test_a_router_advertising_no_link_layer_address_is_listed_without_a_cache_entry, "test_a_router_advertising_no_link_layer_address_is_listed_without_a_cache_entry", 1522);
  run_test(test_a_later_advertisement_with_a_link_layer_address_fills_the_cache_entry, "test_a_later_advertisement_with_a_link_layer_address_fills_the_cache_entry", 1544);
  run_test(test_a_zero_lifetime_on_an_unlisted_router_creates_nothing, "test_a_zero_lifetime_on_an_unlisted_router_creates_nothing", 1561);
  run_test(test_a_zero_lifetime_times_out_a_listed_router, "test_a_zero_lifetime_times_out_a_listed_router", 1576);
  run_test(test_a_router_lifetime_expires_the_entry, "test_a_router_lifetime_expires_the_entry", 1589);
  run_test(test_removing_a_router_makes_its_destinations_redo_next_hop_determination, "test_removing_a_router_makes_its_destinations_redo_next_hop_determination", 1608);
  run_test(test_select_prefers_a_router_that_is_not_incomplete, "test_select_prefers_a_router_that_is_not_incomplete", 1633);
  run_test(test_select_prefers_a_reachable_router_over_a_stale_one, "test_select_prefers_a_reachable_router_over_a_stale_one", 1650);
  run_test(test_select_round_robins_among_routers_of_unknown_reachability, "test_select_round_robins_among_routers_of_unknown_reachability", 1667);
  run_test(test_select_on_an_empty_default_router_list_is_an_error, "test_select_on_an_empty_default_router_list_is_an_error", 1686);
  run_test(test_a_destination_maps_to_its_next_hop_and_path_mtu, "test_a_destination_maps_to_its_next_hop_and_path_mtu", 1700);
  run_test(test_a_redirect_revises_the_next_hop_and_keeps_the_path_mtu, "test_a_redirect_revises_the_next_hop_and_keeps_the_path_mtu", 1721);
  run_test(test_finding_an_unknown_destination_is_an_error, "test_finding_an_unknown_destination_is_an_error", 1742);
  run_test(test_an_unspecified_field_leaves_the_host_variable_alone, "test_an_unspecified_field_leaves_the_host_variable_alone", 1759);
  run_test(test_reachable_time_is_drawn_between_the_two_random_factors, "test_reachable_time_is_drawn_between_the_two_random_factors", 1791);
  run_test(test_a_repeated_reachable_time_does_not_redraw, "test_a_repeated_reachable_time_does_not_redraw", 1823);
  run_test(test_an_mtu_option_outside_the_link_bounds_is_not_copied, "test_an_mtu_option_outside_the_link_bounds_is_not_copied", 1850);
  run_test(test_the_advertised_retrans_timer_governs_the_solicitation_interval, "test_the_advertised_retrans_timer_governs_the_solicitation_interval", 1876);
  run_test(test_a_sweep_with_nothing_due_is_busy, "test_a_sweep_with_nothing_due_is_busy", 1904);
  run_test(test_a_sweep_reports_the_soonest_deadline, "test_a_sweep_reports_the_soonest_deadline", 1916);
  run_test(test_the_machine_on_one_borrow_reaches_no_byte_of_another, "test_the_machine_on_one_borrow_reaches_no_byte_of_another", 1930);
  run_test(test_a_router_advertised_from_a_global_address_names_no_router, "test_a_router_advertised_from_a_global_address_names_no_router", 1952);
  run_test(test_a_router_advertised_from_a_link_local_address_names_one, "test_a_router_advertised_from_a_link_local_address_names_one", 1967);

  return UNITY_END();
}
