/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/igmp/igmp.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_clear_on_one_borrow_leaves_the_other_untouched(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_no_entry_leaves_a_stale_send_leave_behind(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_every_published_offset_is_aligned(void);
extern void test_the_io_macro_reaches_the_operand_block(void);
extern void test_clear_reports_ok(void);
extern void test_clear_zeroes_the_table(void);
extern void test_clear_zeroes_the_context_apart_from_the_mark(void);
extern void test_clear_takes_the_regions_to_one_state(void);
extern void test_clear_leaves_the_operand_block_alone(void);
extern void test_clear_is_idempotent(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_clearing_one_borrow_does_not_ready_the_other(void);
extern void test_a_refused_call_reports_no_entry(void);
extern void test_a_membership_needs_a_class_d_address(void);
extern void test_the_all_systems_group_is_never_a_membership(void);
extern void test_a_membership_needs_an_interface_this_build_carries(void);
extern void test_the_message_types_are_the_ones_rfc_2236_prints(void);
extern void test_the_message_is_eight_octets_at_the_offsets_rfc_2236_draws(void);
extern void test_the_datagram_carries_protocol_two_at_ttl_one(void);
extern void test_the_well_known_groups_are_the_ones_rfc_2236_prints(void);
extern void test_max_response_time_is_tenths_of_a_second(void);
extern void test_the_router_alert_option_is_the_one_rfc_2113_prints(void);
extern void test_the_three_host_states_are_distinct_and_one_octet(void);
extern void test_none_is_outside_the_table(void);
extern void test_the_host_timers_are_the_ones_rfc_2236_prints(void);
extern void test_join_sends_a_report_sets_the_flag_and_starts_a_timer(void);
extern void test_join_arms_the_timer_inside_the_unsolicited_report_interval(void);
extern void test_a_second_join_of_the_same_group_takes_a_reference(void);
extern void test_the_same_group_on_two_interfaces_is_two_memberships(void);
extern void test_a_full_table_is_busy_and_a_leave_makes_the_retry_succeed(void);
extern void test_the_delay_draw_reaches_the_top_of_the_interval(void);
extern void test_the_delay_draw_never_yields_zero(void);
extern void test_the_delay_draw_covers_the_interval_and_leaves_it_at_neither_end(void);
extern void test_a_general_query_arms_every_membership_on_its_own_interface_only(void);
extern void test_a_group_specific_query_arms_only_the_group_it_names(void);
extern void test_a_query_draws_over_the_whole_max_response_time(void);
extern void test_a_general_query_gives_each_timer_a_different_value(void);
extern void test_a_running_timer_is_reset_only_by_a_shorter_max_response_time(void);
extern void test_a_query_never_sends_a_report_itself(void);
extern void test_a_query_for_a_group_the_host_has_not_joined_changes_nothing(void);
extern void test_a_max_response_time_wider_than_the_field_can_carry_is_refused(void);
extern void test_a_query_needs_an_interface_this_build_carries(void);
extern void test_a_group_specific_query_needs_a_class_d_group(void);
extern void test_a_v1_query_arms_the_ten_second_interval_sec_4_prints(void);
extern void test_a_v1_query_makes_the_reports_version_one_reports(void);
extern void test_the_v1_router_record_ages_out_after_the_sec_8_11_timeout(void);
extern void test_the_v1_router_record_is_per_interface(void);
extern void test_a_v1_querier_suppresses_the_leave_message(void);
extern void test_another_hosts_report_stops_the_timer_and_clears_the_flag(void);
extern void test_a_report_is_ignored_in_the_idle_member_state(void);
extern void test_a_report_on_another_interface_does_not_suppress_this_one(void);
extern void test_a_report_for_a_group_the_host_has_not_joined_is_ignored(void);
extern void test_an_expired_timer_sends_a_report_and_sets_the_flag(void);
extern void test_a_timer_that_has_not_expired_is_left_running(void);
extern void test_a_sweep_counts_every_due_timer_and_hands_out_one_report_per_call(void);
extern void test_a_deadline_the_clock_wrapped_past_still_fires_once(void);
extern void test_leave_from_idle_member_sends_a_leave_and_frees_the_entry(void);
extern void test_leave_from_delaying_member_stops_the_timer(void);
extern void test_leave_sends_nothing_when_the_last_reporter_flag_is_clear(void);
extern void test_leave_of_a_group_that_was_never_joined_is_refused(void);
extern void test_leave_on_the_wrong_interface_is_refused(void);
extern void test_find_reports_the_state_the_deadline_and_the_flag(void);
extern void test_two_borrows_run_independent_state_machines(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/igmp/test_igmp\\test_igmp.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 166);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 175);
  run_test(test_clear_on_one_borrow_leaves_the_other_untouched, "test_clear_on_one_borrow_leaves_the_other_untouched", 202);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 218);
  run_test(test_no_entry_leaves_a_stale_send_leave_behind, "test_no_entry_leaves_a_stale_send_leave_behind", 252);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 298);
  run_test(test_every_published_offset_is_aligned, "test_every_published_offset_is_aligned", 310);
  run_test(test_the_io_macro_reaches_the_operand_block, "test_the_io_macro_reaches_the_operand_block", 319);
  run_test(test_clear_reports_ok, "test_clear_reports_ok", 327);
  run_test(test_clear_zeroes_the_table, "test_clear_zeroes_the_table", 335);
  run_test(test_clear_zeroes_the_context_apart_from_the_mark, "test_clear_zeroes_the_context_apart_from_the_mark", 347);
  run_test(test_clear_takes_the_regions_to_one_state, "test_clear_takes_the_regions_to_one_state", 364);
  run_test(test_clear_leaves_the_operand_block_alone, "test_clear_leaves_the_operand_block_alone", 374);
  run_test(test_clear_is_idempotent, "test_clear_is_idempotent", 384);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 395);
  run_test(test_clearing_one_borrow_does_not_ready_the_other, "test_clearing_one_borrow_does_not_ready_the_other", 416);
  run_test(test_a_refused_call_reports_no_entry, "test_a_refused_call_reports_no_entry", 424);
  run_test(test_a_membership_needs_a_class_d_address, "test_a_membership_needs_a_class_d_address", 435);
  run_test(test_the_all_systems_group_is_never_a_membership, "test_the_all_systems_group_is_never_a_membership", 446);
  run_test(test_a_membership_needs_an_interface_this_build_carries, "test_a_membership_needs_an_interface_this_build_carries", 456);
  run_test(test_the_message_types_are_the_ones_rfc_2236_prints, "test_the_message_types_are_the_ones_rfc_2236_prints", 468);
  run_test(test_the_message_is_eight_octets_at_the_offsets_rfc_2236_draws, "test_the_message_is_eight_octets_at_the_offsets_rfc_2236_draws", 478);
  run_test(test_the_datagram_carries_protocol_two_at_ttl_one, "test_the_datagram_carries_protocol_two_at_ttl_one", 489);
  run_test(test_the_well_known_groups_are_the_ones_rfc_2236_prints, "test_the_well_known_groups_are_the_ones_rfc_2236_prints", 496);
  run_test(test_max_response_time_is_tenths_of_a_second, "test_max_response_time_is_tenths_of_a_second", 505);
  run_test(test_the_router_alert_option_is_the_one_rfc_2113_prints, "test_the_router_alert_option_is_the_one_rfc_2113_prints", 515);
  run_test(test_the_three_host_states_are_distinct_and_one_octet, "test_the_three_host_states_are_distinct_and_one_octet", 527);
  run_test(test_none_is_outside_the_table, "test_none_is_outside_the_table", 537);
  run_test(test_the_host_timers_are_the_ones_rfc_2236_prints, "test_the_host_timers_are_the_ones_rfc_2236_prints", 545);
  run_test(test_join_sends_a_report_sets_the_flag_and_starts_a_timer, "test_join_sends_a_report_sets_the_flag_and_starts_a_timer", 581);
  run_test(test_join_arms_the_timer_inside_the_unsolicited_report_interval, "test_join_arms_the_timer_inside_the_unsolicited_report_interval", 596);
  run_test(test_a_second_join_of_the_same_group_takes_a_reference, "test_a_second_join_of_the_same_group_takes_a_reference", 612);
  run_test(test_the_same_group_on_two_interfaces_is_two_memberships, "test_the_same_group_on_two_interfaces_is_two_memberships", 650);
  run_test(test_a_full_table_is_busy_and_a_leave_makes_the_retry_succeed, "test_a_full_table_is_busy_and_a_leave_makes_the_retry_succeed", 665);
  run_test(test_the_delay_draw_reaches_the_top_of_the_interval, "test_the_delay_draw_reaches_the_top_of_the_interval", 687);
  run_test(test_the_delay_draw_never_yields_zero, "test_the_delay_draw_never_yields_zero", 697);
  run_test(test_the_delay_draw_covers_the_interval_and_leaves_it_at_neither_end, "test_the_delay_draw_covers_the_interval_and_leaves_it_at_neither_end", 707);
  run_test(test_a_general_query_arms_every_membership_on_its_own_interface_only, "test_a_general_query_arms_every_membership_on_its_own_interface_only", 732);
  run_test(test_a_group_specific_query_arms_only_the_group_it_names, "test_a_group_specific_query_arms_only_the_group_it_names", 756);
  run_test(test_a_query_draws_over_the_whole_max_response_time, "test_a_query_draws_over_the_whole_max_response_time", 776);
  run_test(test_a_general_query_gives_each_timer_a_different_value, "test_a_general_query_gives_each_timer_a_different_value", 800);
  run_test(test_a_running_timer_is_reset_only_by_a_shorter_max_response_time, "test_a_running_timer_is_reset_only_by_a_shorter_max_response_time", 816);
  run_test(test_a_query_never_sends_a_report_itself, "test_a_query_never_sends_a_report_itself", 835);
  run_test(test_a_query_for_a_group_the_host_has_not_joined_changes_nothing, "test_a_query_for_a_group_the_host_has_not_joined_changes_nothing", 848);
  run_test(test_a_max_response_time_wider_than_the_field_can_carry_is_refused, "test_a_max_response_time_wider_than_the_field_can_carry_is_refused", 864);
  run_test(test_a_query_needs_an_interface_this_build_carries, "test_a_query_needs_an_interface_this_build_carries", 880);
  run_test(test_a_group_specific_query_needs_a_class_d_group, "test_a_group_specific_query_needs_a_class_d_group", 889);
  run_test(test_a_v1_query_arms_the_ten_second_interval_sec_4_prints, "test_a_v1_query_arms_the_ten_second_interval_sec_4_prints", 901);
  run_test(test_a_v1_query_makes_the_reports_version_one_reports, "test_a_v1_query_makes_the_reports_version_one_reports", 919);
  run_test(test_the_v1_router_record_ages_out_after_the_sec_8_11_timeout, "test_the_v1_router_record_ages_out_after_the_sec_8_11_timeout", 939);
  run_test(test_the_v1_router_record_is_per_interface, "test_the_v1_router_record_is_per_interface", 955);
  run_test(test_a_v1_querier_suppresses_the_leave_message, "test_a_v1_querier_suppresses_the_leave_message", 970);
  run_test(test_another_hosts_report_stops_the_timer_and_clears_the_flag, "test_another_hosts_report_stops_the_timer_and_clears_the_flag", 991);
  run_test(test_a_report_is_ignored_in_the_idle_member_state, "test_a_report_is_ignored_in_the_idle_member_state", 1010);
  run_test(test_a_report_on_another_interface_does_not_suppress_this_one, "test_a_report_on_another_interface_does_not_suppress_this_one", 1029);
  run_test(test_a_report_for_a_group_the_host_has_not_joined_is_ignored, "test_a_report_for_a_group_the_host_has_not_joined_is_ignored", 1044);
  run_test(test_an_expired_timer_sends_a_report_and_sets_the_flag, "test_an_expired_timer_sends_a_report_and_sets_the_flag", 1056);
  run_test(test_a_timer_that_has_not_expired_is_left_running, "test_a_timer_that_has_not_expired_is_left_running", 1076);
  run_test(test_a_sweep_counts_every_due_timer_and_hands_out_one_report_per_call, "test_a_sweep_counts_every_due_timer_and_hands_out_one_report_per_call", 1093);
  run_test(test_a_deadline_the_clock_wrapped_past_still_fires_once, "test_a_deadline_the_clock_wrapped_past_still_fires_once", 1123);
  run_test(test_leave_from_idle_member_sends_a_leave_and_frees_the_entry, "test_leave_from_idle_member_sends_a_leave_and_frees_the_entry", 1145);
  run_test(test_leave_from_delaying_member_stops_the_timer, "test_leave_from_delaying_member_stops_the_timer", 1164);
  run_test(test_leave_sends_nothing_when_the_last_reporter_flag_is_clear, "test_leave_sends_nothing_when_the_last_reporter_flag_is_clear", 1182);
  run_test(test_leave_of_a_group_that_was_never_joined_is_refused, "test_leave_of_a_group_that_was_never_joined_is_refused", 1196);
  run_test(test_leave_on_the_wrong_interface_is_refused, "test_leave_on_the_wrong_interface_is_refused", 1206);
  run_test(test_find_reports_the_state_the_deadline_and_the_flag, "test_find_reports_the_state_the_deadline_and_the_flag", 1218);
  run_test(test_two_borrows_run_independent_state_machines, "test_two_borrows_run_independent_state_machines", 1237);

  return UNITY_END();
}
