/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/ethernet/ethernet.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_rfc894_ipv4_type_code_is_0800(void);
extern void test_rfc1042_assigned_type_codes_in_decimal(void);
extern void test_rfc2464_ipv6_type_code_bit_figure(void);
extern void test_header_is_two_addresses_then_a_type_code(void);
extern void test_addresses_are_read_in_place(void);
extern void test_type_code_reads_the_same_at_any_frame_address(void);
extern void test_build_writes_exactly_the_header(void);
extern void test_build_then_parse_round_trips(void);
extern void test_broadcast_address_is_all_ones(void);
extern void test_a_broadcast_destination_is_recognized_in_a_frame(void);
extern void test_min_payload_is_46_octets(void);
extern void test_max_payload_is_1500_octets(void);
extern void test_pad_zeroes_the_shortfall(void);
extern void test_a_full_length_payload_is_not_padded(void);
extern void test_payload_follows_the_header(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/ethernet/test_ethernet\\test_ethernet.c");
  run_test(test_rfc894_ipv4_type_code_is_0800, "test_rfc894_ipv4_type_code_is_0800", 51);
  run_test(test_rfc1042_assigned_type_codes_in_decimal, "test_rfc1042_assigned_type_codes_in_decimal", 63);
  run_test(test_rfc2464_ipv6_type_code_bit_figure, "test_rfc2464_ipv6_type_code_bit_figure", 76);
  run_test(test_header_is_two_addresses_then_a_type_code, "test_header_is_two_addresses_then_a_type_code", 97);
  run_test(test_addresses_are_read_in_place, "test_addresses_are_read_in_place", 109);
  run_test(test_type_code_reads_the_same_at_any_frame_address, "test_type_code_reads_the_same_at_any_frame_address", 122);
  run_test(test_build_writes_exactly_the_header, "test_build_writes_exactly_the_header", 135);
  run_test(test_build_then_parse_round_trips, "test_build_then_parse_round_trips", 144);
  run_test(test_broadcast_address_is_all_ones, "test_broadcast_address_is_all_ones", 156);
  run_test(test_a_broadcast_destination_is_recognized_in_a_frame, "test_a_broadcast_destination_is_recognized_in_a_frame", 175);
  run_test(test_min_payload_is_46_octets, "test_min_payload_is_46_octets", 185);
  run_test(test_max_payload_is_1500_octets, "test_max_payload_is_1500_octets", 199);
  run_test(test_pad_zeroes_the_shortfall, "test_pad_zeroes_the_shortfall", 208);
  run_test(test_a_full_length_payload_is_not_padded, "test_a_full_length_payload_is_not_padded", 229);
  run_test(test_payload_follows_the_header, "test_payload_follows_the_header", 246);

  return UNITY_END();
}
