/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/acd/acd.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_clear_on_one_borrow_leaves_the_other_untouched(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_every_published_offset_is_aligned(void);
extern void test_the_io_macro_reaches_the_operand_block(void);
extern void test_clear_reports_ok(void);
extern void test_clear_takes_the_context_to_one_state(void);
extern void test_clear_zeroes_the_context_apart_from_the_mark(void);
extern void test_clear_leaves_the_operand_block_alone(void);
extern void test_clear_is_idempotent(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_clearing_one_borrow_does_not_ready_the_other(void);
extern void test_start_refuses_no_address_and_no_hardware_address(void);
extern void test_arp_in_refuses_no_packet(void);
extern void test_the_timing_constants_are_the_ones_rfc_5227_prints(void);
extern void test_the_probe_delay_has_a_range_to_draw_from(void);
extern void test_the_states_are_distinct_and_one_octet(void);
extern void test_the_three_conflict_responses_are_distinct_and_one_octet(void);
extern void test_every_deadline_is_seconds_scaled_to_milliseconds(void);
extern void test_start_waits_out_a_delay_inside_probe_wait(void);
extern void test_the_initial_delay_reaches_zero_and_probe_wait(void);
extern void test_start_puts_the_address_in_the_machine(void);
extern void test_start_over_a_running_machine_reclaims_from_the_delay(void);
extern void test_a_tick_before_the_deadline_is_busy_and_sends_nothing(void);
extern void test_the_tick_on_the_deadline_sends_the_first_probe(void);
extern void test_every_probe_gap_lies_between_probe_min_and_probe_max(void);
extern void test_the_probe_gap_reaches_probe_min_and_probe_max(void);
extern void test_exactly_probe_num_probes_go_out_then_announce_wait(void);
extern void test_exactly_announce_num_announcements_go_out_announce_interval_apart(void);
extern void test_a_tick_with_no_deadline_reports_ok_and_sends_nothing(void);
extern void test_a_deadline_survives_the_clock_wrap(void);
extern void test_a_reply_whose_sender_ip_is_the_probed_address_is_a_conflict(void);
extern void test_a_request_whose_sender_ip_is_the_probed_address_is_a_conflict(void);
extern void test_the_sender_ip_clause_carries_no_hardware_address_test(void);
extern void test_a_foreign_probe_for_the_same_address_is_a_conflict(void);
extern void test_this_hosts_own_probe_echoed_back_is_not_a_conflict(void);
extern void test_a_foreign_probe_for_another_address_is_not_a_conflict(void);
extern void test_a_reply_with_an_all_zero_sender_ip_is_not_a_probe(void);
extern void test_the_probing_window_reaches_through_announce_wait(void);
extern void test_announcing_takes_the_section_2_4_test_and_not_the_probe_test(void);
extern void test_an_ongoing_conflict_needs_a_foreign_sender_hardware_address(void);
extern void test_an_ongoing_packet_for_another_address_is_not_a_conflict(void);
extern void test_defend_never_ceases_on_the_first_conflict(void);
extern void test_defend_once_announces_and_keeps_the_address(void);
extern void test_defend_once_ceases_on_a_second_conflict_inside_defend_interval(void);
extern void test_defend_once_announces_again_a_full_defend_interval_later(void);
extern void test_defend_always_announces_and_never_ceases(void);
extern void test_defend_always_sends_nothing_on_a_second_conflict_inside_the_interval(void);
extern void test_max_conflicts_enters_the_rate_limit(void);
extern void test_a_conflict_below_max_conflicts_does_not_rate_limit(void);
extern void test_defended_conflicts_reach_the_rate_limit_without_an_abandon(void);
extern void test_a_claim_inside_the_rate_limit_interval_is_busy(void);
extern void test_a_tick_ends_the_rate_limit_interval(void);
extern void test_a_claim_does_not_clear_the_conflict_count(void);
extern void test_start_refuses_a_defense_that_is_none_of_a_b_or_c(void);
extern void test_the_conflict_count_holds_at_its_ceiling(void);
extern void test_clear_takes_the_conflict_count_back_to_zero(void);
extern void test_stop_ceases_and_keeps_the_conflict_count(void);
extern void test_stop_is_idempotent(void);
extern void test_stop_does_not_clear_a_standing_rate_limit(void);
extern void test_arp_in_refuses_a_packet_that_is_not_ethernet_ipv4(void);
extern void test_an_opcode_that_is_neither_request_nor_reply_holds_no_conflict(void);
extern void test_off_and_rate_limit_find_no_conflict_in_any_packet(void);
extern void test_an_entry_clears_every_result_member_it_did_not_set(void);
extern void test_two_machines_probe_and_conflict_independently(void);
extern void test_a_defense_on_one_borrow_does_not_arm_the_others_interval(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/acd/test_acd\\test_acd.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 88);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 96);
  run_test(test_clear_on_one_borrow_leaves_the_other_untouched, "test_clear_on_one_borrow_leaves_the_other_untouched", 113);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 129);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 150);
  run_test(test_every_published_offset_is_aligned, "test_every_published_offset_is_aligned", 161);
  run_test(test_the_io_macro_reaches_the_operand_block, "test_the_io_macro_reaches_the_operand_block", 168);
  run_test(test_clear_reports_ok, "test_clear_reports_ok", 176);
  run_test(test_clear_takes_the_context_to_one_state, "test_clear_takes_the_context_to_one_state", 184);
  run_test(test_clear_zeroes_the_context_apart_from_the_mark, "test_clear_zeroes_the_context_apart_from_the_mark", 195);
  run_test(test_clear_leaves_the_operand_block_alone, "test_clear_leaves_the_operand_block_alone", 212);
  run_test(test_clear_is_idempotent, "test_clear_is_idempotent", 223);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 234);
  run_test(test_clearing_one_borrow_does_not_ready_the_other, "test_clearing_one_borrow_does_not_ready_the_other", 250);
  run_test(test_start_refuses_no_address_and_no_hardware_address, "test_start_refuses_no_address_and_no_hardware_address", 259);
  run_test(test_arp_in_refuses_no_packet, "test_arp_in_refuses_no_packet", 275);
  run_test(test_the_timing_constants_are_the_ones_rfc_5227_prints, "test_the_timing_constants_are_the_ones_rfc_5227_prints", 288);
  run_test(test_the_probe_delay_has_a_range_to_draw_from, "test_the_probe_delay_has_a_range_to_draw_from", 304);
  run_test(test_the_states_are_distinct_and_one_octet, "test_the_states_are_distinct_and_one_octet", 311);
  run_test(test_the_three_conflict_responses_are_distinct_and_one_octet, "test_the_three_conflict_responses_are_distinct_and_one_octet", 325);
  run_test(test_every_deadline_is_seconds_scaled_to_milliseconds, "test_every_deadline_is_seconds_scaled_to_milliseconds", 335);
  run_test(test_start_waits_out_a_delay_inside_probe_wait, "test_start_waits_out_a_delay_inside_probe_wait", 434);
  run_test(test_the_initial_delay_reaches_zero_and_probe_wait, "test_the_initial_delay_reaches_zero_and_probe_wait", 447);
  run_test(test_start_puts_the_address_in_the_machine, "test_start_puts_the_address_in_the_machine", 457);
  run_test(test_start_over_a_running_machine_reclaims_from_the_delay, "test_start_over_a_running_machine_reclaims_from_the_delay", 470);
  run_test(test_a_tick_before_the_deadline_is_busy_and_sends_nothing, "test_a_tick_before_the_deadline_is_busy_and_sends_nothing", 488);
  run_test(test_the_tick_on_the_deadline_sends_the_first_probe, "test_the_tick_on_the_deadline_sends_the_first_probe", 498);
  run_test(test_every_probe_gap_lies_between_probe_min_and_probe_max, "test_every_probe_gap_lies_between_probe_min_and_probe_max", 511);
  run_test(test_the_probe_gap_reaches_probe_min_and_probe_max, "test_the_probe_gap_reaches_probe_min_and_probe_max", 526);
  run_test(test_exactly_probe_num_probes_go_out_then_announce_wait, "test_exactly_probe_num_probes_go_out_then_announce_wait", 540);
  run_test(test_exactly_announce_num_announcements_go_out_announce_interval_apart, "test_exactly_announce_num_announcements_go_out_announce_interval_apart", 564);
  run_test(test_a_tick_with_no_deadline_reports_ok_and_sends_nothing, "test_a_tick_with_no_deadline_reports_ok_and_sends_nothing", 593);
  run_test(test_a_deadline_survives_the_clock_wrap, "test_a_deadline_survives_the_clock_wrap", 613);
  run_test(test_a_reply_whose_sender_ip_is_the_probed_address_is_a_conflict, "test_a_reply_whose_sender_ip_is_the_probed_address_is_a_conflict", 632);
  run_test(test_a_request_whose_sender_ip_is_the_probed_address_is_a_conflict, "test_a_request_whose_sender_ip_is_the_probed_address_is_a_conflict", 647);
  run_test(test_the_sender_ip_clause_carries_no_hardware_address_test, "test_the_sender_ip_clause_carries_no_hardware_address_test", 659);
  run_test(test_a_foreign_probe_for_the_same_address_is_a_conflict, "test_a_foreign_probe_for_the_same_address_is_a_conflict", 671);
  run_test(test_this_hosts_own_probe_echoed_back_is_not_a_conflict, "test_this_hosts_own_probe_echoed_back_is_not_a_conflict", 685);
  run_test(test_a_foreign_probe_for_another_address_is_not_a_conflict, "test_a_foreign_probe_for_another_address_is_not_a_conflict", 703);
  run_test(test_a_reply_with_an_all_zero_sender_ip_is_not_a_probe, "test_a_reply_with_an_all_zero_sender_ip_is_not_a_probe", 717);
  run_test(test_the_probing_window_reaches_through_announce_wait, "test_the_probing_window_reaches_through_announce_wait", 729);
  run_test(test_announcing_takes_the_section_2_4_test_and_not_the_probe_test, "test_announcing_takes_the_section_2_4_test_and_not_the_probe_test", 747);
  run_test(test_an_ongoing_conflict_needs_a_foreign_sender_hardware_address, "test_an_ongoing_conflict_needs_a_foreign_sender_hardware_address", 766);
  run_test(test_an_ongoing_packet_for_another_address_is_not_a_conflict, "test_an_ongoing_packet_for_another_address_is_not_a_conflict", 780);
  run_test(test_defend_never_ceases_on_the_first_conflict, "test_defend_never_ceases_on_the_first_conflict", 795);
  run_test(test_defend_once_announces_and_keeps_the_address, "test_defend_once_announces_and_keeps_the_address", 817);
  run_test(test_defend_once_ceases_on_a_second_conflict_inside_defend_interval, "test_defend_once_ceases_on_a_second_conflict_inside_defend_interval", 835);
  run_test(test_defend_once_announces_again_a_full_defend_interval_later, "test_defend_once_announces_again_a_full_defend_interval_later", 856);
  run_test(test_defend_always_announces_and_never_ceases, "test_defend_always_announces_and_never_ceases", 878);
  run_test(test_defend_always_sends_nothing_on_a_second_conflict_inside_the_interval, "test_defend_always_sends_nothing_on_a_second_conflict_inside_the_interval", 899);
  run_test(test_max_conflicts_enters_the_rate_limit, "test_max_conflicts_enters_the_rate_limit", 941);
  run_test(test_a_conflict_below_max_conflicts_does_not_rate_limit, "test_a_conflict_below_max_conflicts_does_not_rate_limit", 952);
  run_test(test_defended_conflicts_reach_the_rate_limit_without_an_abandon, "test_defended_conflicts_reach_the_rate_limit_without_an_abandon", 973);
  run_test(test_a_claim_inside_the_rate_limit_interval_is_busy, "test_a_claim_inside_the_rate_limit_interval_is_busy", 1009);
  run_test(test_a_tick_ends_the_rate_limit_interval, "test_a_tick_ends_the_rate_limit_interval", 1028);
  run_test(test_a_claim_does_not_clear_the_conflict_count, "test_a_claim_does_not_clear_the_conflict_count", 1050);
  run_test(test_start_refuses_a_defense_that_is_none_of_a_b_or_c, "test_start_refuses_a_defense_that_is_none_of_a_b_or_c", 1068);
  run_test(test_the_conflict_count_holds_at_its_ceiling, "test_the_conflict_count_holds_at_its_ceiling", 1079);
  run_test(test_clear_takes_the_conflict_count_back_to_zero, "test_clear_takes_the_conflict_count_back_to_zero", 1096);
  run_test(test_stop_ceases_and_keeps_the_conflict_count, "test_stop_ceases_and_keeps_the_conflict_count", 1110);
  run_test(test_stop_is_idempotent, "test_stop_is_idempotent", 1128);
  run_test(test_stop_does_not_clear_a_standing_rate_limit, "test_stop_does_not_clear_a_standing_rate_limit", 1140);
  run_test(test_arp_in_refuses_a_packet_that_is_not_ethernet_ipv4, "test_arp_in_refuses_a_packet_that_is_not_ethernet_ipv4", 1159);
  run_test(test_an_opcode_that_is_neither_request_nor_reply_holds_no_conflict, "test_an_opcode_that_is_neither_request_nor_reply_holds_no_conflict", 1177);
  run_test(test_off_and_rate_limit_find_no_conflict_in_any_packet, "test_off_and_rate_limit_find_no_conflict_in_any_packet", 1190);
  run_test(test_an_entry_clears_every_result_member_it_did_not_set, "test_an_entry_clears_every_result_member_it_did_not_set", 1212);
  run_test(test_two_machines_probe_and_conflict_independently, "test_two_machines_probe_and_conflict_independently", 1249);
  run_test(test_a_defense_on_one_borrow_does_not_arm_the_others_interval, "test_a_defense_on_one_borrow_does_not_arm_the_others_interval", 1278);

  return UNITY_END();
}
