/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/mld/mld6.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_clear_on_one_borrow_leaves_the_other_untouched(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_every_published_offset_is_aligned(void);
extern void test_the_io_macro_reaches_the_operand_block(void);
extern void test_clear_reports_ok(void);
extern void test_clear_zeroes_the_table(void);
extern void test_clear_zeroes_the_context_apart_from_the_cleared_mark(void);
extern void test_clear_leaves_the_operand_block_alone(void);
extern void test_clear_is_idempotent(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_clearing_one_borrow_does_not_ready_the_other(void);
extern void test_none_is_outside_the_table(void);
extern void test_the_three_node_states_are_distinct_and_one_octet(void);
extern void test_the_message_is_twenty_four_octets(void);
extern void test_the_hop_limit_is_one(void);
extern void test_the_delays_are_milliseconds(void);
extern void test_join_sends_a_report_sets_the_flag_and_starts_the_timer(void);
extern void test_the_join_timer_is_drawn_over_the_unsolicited_report_interval(void);
extern void test_the_join_timer_follows_the_callers_random_word(void);
extern void test_the_done_optimization_can_be_turned_off(void);
extern void test_joining_a_group_twice_transitions_nothing(void);
extern void test_the_same_group_on_two_interfaces_is_two_entries(void);
extern void test_a_full_table_is_busy_and_the_retry_after_a_leave_succeeds(void);
extern void test_join_refuses_a_non_multicast_address(void);
extern void test_join_and_leave_refuse_an_interface_out_of_range(void);
extern void test_the_all_nodes_address_starts_idle_and_never_reports(void);
extern void test_scope_zero_and_node_local_groups_never_report(void);
extern void test_link_local_and_global_groups_do_report(void);
extern void test_leave_sends_a_done_when_the_flag_is_set_and_frees_the_entry(void);
extern void test_leave_after_a_suppressed_report_sends_no_done(void);
extern void test_leaving_a_group_that_is_not_listened_to_is_refused(void);
extern void test_the_zeroed_state_is_non_listener(void);
extern void test_find_reports_the_state_and_the_deadline(void);
extern void test_find_on_a_group_that_is_not_listened_to_is_refused(void);
extern void test_a_general_query_arms_every_listened_group_on_that_interface(void);
extern void test_a_general_query_does_not_reach_another_interface(void);
extern void test_a_general_query_excludes_all_nodes_and_scope_zero_and_one(void);
extern void test_a_general_query_sets_a_different_value_per_group(void);
extern void test_the_per_group_draws_do_not_share_a_value(void);
extern void test_every_drawn_delay_lies_within_the_maximum_response_delay(void);
extern void test_the_drawn_delay_holds_at_the_range_edges(void);
extern void test_a_larger_requested_delay_does_not_reset_a_running_timer(void);
extern void test_a_smaller_requested_delay_resets_a_running_timer(void);
extern void test_a_maximum_response_delay_of_zero_is_due_at_once(void);
extern void test_a_zero_maximum_response_delay_overrides_a_running_timer(void);
extern void test_a_specific_query_arms_only_the_queried_group(void);
extern void test_a_specific_query_for_a_group_not_listened_to_is_refused(void);
extern void test_a_general_query_with_nothing_listened_to_is_ok(void);
extern void test_query_in_refuses_a_bad_argument(void);
extern void test_a_specific_query_for_all_nodes_arms_nothing(void);
extern void test_a_report_stops_the_timer_and_clears_the_flag(void);
extern void test_a_report_in_idle_listener_changes_nothing(void);
extern void test_a_report_on_another_interface_suppresses_nothing(void);
extern void test_a_report_for_a_group_not_listened_to_is_refused(void);
extern void test_an_expiring_timer_sends_a_report_and_sets_the_flag(void);
extern void test_a_sweep_before_the_deadline_fires_nothing(void);
extern void test_a_sweep_counts_every_due_timer_and_fires_one_per_call(void);
extern void test_a_sweep_with_nothing_due_is_ok_and_not_busy(void);
extern void test_a_deadline_survives_the_millisecond_clocks_wrap(void);
extern void test_the_state_diagram_walks_end_to_end(void);
extern void test_the_machine_on_two_borrows_stays_independent(void);
extern void test_the_same_query_on_two_identical_borrows_draws_the_same_delay(void);
extern void test_the_group_entries_refuse_a_call_that_names_no_group(void);
extern void test_a_join_that_names_no_group_is_refused(void);
extern void test_a_query_asking_for_longer_than_the_running_timer_leaves_it(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/unit/mld/test_mld6/test_mld6.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 80);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 88);
  run_test(test_clear_on_one_borrow_leaves_the_other_untouched, "test_clear_on_one_borrow_leaves_the_other_untouched", 106);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 124);
  run_test(test_every_published_offset_is_aligned, "test_every_published_offset_is_aligned", 136);
  run_test(test_the_io_macro_reaches_the_operand_block, "test_the_io_macro_reaches_the_operand_block", 143);
  run_test(test_clear_reports_ok, "test_clear_reports_ok", 151);
  run_test(test_clear_zeroes_the_table, "test_clear_zeroes_the_table", 159);
  run_test(test_clear_zeroes_the_context_apart_from_the_cleared_mark, "test_clear_zeroes_the_context_apart_from_the_cleared_mark", 171);
  run_test(test_clear_leaves_the_operand_block_alone, "test_clear_leaves_the_operand_block_alone", 187);
  run_test(test_clear_is_idempotent, "test_clear_is_idempotent", 199);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 210);
  run_test(test_clearing_one_borrow_does_not_ready_the_other, "test_clearing_one_borrow_does_not_ready_the_other", 230);
  run_test(test_none_is_outside_the_table, "test_none_is_outside_the_table", 241);
  run_test(test_the_three_node_states_are_distinct_and_one_octet, "test_the_three_node_states_are_distinct_and_one_octet", 248);
  run_test(test_the_message_is_twenty_four_octets, "test_the_message_is_twenty_four_octets", 259);
  run_test(test_the_hop_limit_is_one, "test_the_hop_limit_is_one", 266);
  run_test(test_the_delays_are_milliseconds, "test_the_delays_are_milliseconds", 273);
  run_test(test_join_sends_a_report_sets_the_flag_and_starts_the_timer, "test_join_sends_a_report_sets_the_flag_and_starts_the_timer", 417);
  run_test(test_the_join_timer_is_drawn_over_the_unsolicited_report_interval, "test_the_join_timer_is_drawn_over_the_unsolicited_report_interval", 433);
  run_test(test_the_join_timer_follows_the_callers_random_word, "test_the_join_timer_follows_the_callers_random_word", 445);
  run_test(test_the_done_optimization_can_be_turned_off, "test_the_done_optimization_can_be_turned_off", 464);
  run_test(test_joining_a_group_twice_transitions_nothing, "test_joining_a_group_twice_transitions_nothing", 494);
  run_test(test_the_same_group_on_two_interfaces_is_two_entries, "test_the_same_group_on_two_interfaces_is_two_entries", 509);
  run_test(test_a_full_table_is_busy_and_the_retry_after_a_leave_succeeds, "test_a_full_table_is_busy_and_the_retry_after_a_leave_succeeds", 524);
  run_test(test_join_refuses_a_non_multicast_address, "test_join_refuses_a_non_multicast_address", 547);
  run_test(test_join_and_leave_refuse_an_interface_out_of_range, "test_join_and_leave_refuse_an_interface_out_of_range", 556);
  run_test(test_the_all_nodes_address_starts_idle_and_never_reports, "test_the_all_nodes_address_starts_idle_and_never_reports", 566);
  run_test(test_scope_zero_and_node_local_groups_never_report, "test_scope_zero_and_node_local_groups_never_report", 580);
  run_test(test_link_local_and_global_groups_do_report, "test_link_local_and_global_groups_do_report", 595);
  run_test(test_leave_sends_a_done_when_the_flag_is_set_and_frees_the_entry, "test_leave_sends_a_done_when_the_flag_is_set_and_frees_the_entry", 611);
  run_test(test_leave_after_a_suppressed_report_sends_no_done, "test_leave_after_a_suppressed_report_sends_no_done", 626);
  run_test(test_leaving_a_group_that_is_not_listened_to_is_refused, "test_leaving_a_group_that_is_not_listened_to_is_refused", 639);
  run_test(test_the_zeroed_state_is_non_listener, "test_the_zeroed_state_is_non_listener", 653);
  run_test(test_find_reports_the_state_and_the_deadline, "test_find_reports_the_state_and_the_deadline", 675);
  run_test(test_find_on_a_group_that_is_not_listened_to_is_refused, "test_find_on_a_group_that_is_not_listened_to_is_refused", 690);
  run_test(test_a_general_query_arms_every_listened_group_on_that_interface, "test_a_general_query_arms_every_listened_group_on_that_interface", 703);
  run_test(test_a_general_query_does_not_reach_another_interface, "test_a_general_query_does_not_reach_another_interface", 725);
  run_test(test_a_general_query_excludes_all_nodes_and_scope_zero_and_one, "test_a_general_query_excludes_all_nodes_and_scope_zero_and_one", 740);
  run_test(test_a_general_query_sets_a_different_value_per_group, "test_a_general_query_sets_a_different_value_per_group", 758);
  run_test(test_the_per_group_draws_do_not_share_a_value, "test_the_per_group_draws_do_not_share_a_value", 776);
  run_test(test_every_drawn_delay_lies_within_the_maximum_response_delay, "test_every_drawn_delay_lies_within_the_maximum_response_delay", 803);
  run_test(test_the_drawn_delay_holds_at_the_range_edges, "test_the_drawn_delay_holds_at_the_range_edges", 818);
  run_test(test_a_larger_requested_delay_does_not_reset_a_running_timer, "test_a_larger_requested_delay_does_not_reset_a_running_timer", 841);
  run_test(test_a_smaller_requested_delay_resets_a_running_timer, "test_a_smaller_requested_delay_resets_a_running_timer", 861);
  run_test(test_a_maximum_response_delay_of_zero_is_due_at_once, "test_a_maximum_response_delay_of_zero_is_due_at_once", 883);
  run_test(test_a_zero_maximum_response_delay_overrides_a_running_timer, "test_a_zero_maximum_response_delay_overrides_a_running_timer", 899);
  run_test(test_a_specific_query_arms_only_the_queried_group, "test_a_specific_query_arms_only_the_queried_group", 915);
  run_test(test_a_specific_query_for_a_group_not_listened_to_is_refused, "test_a_specific_query_for_a_group_not_listened_to_is_refused", 931);
  run_test(test_a_general_query_with_nothing_listened_to_is_ok, "test_a_general_query_with_nothing_listened_to_is_ok", 945);
  run_test(test_query_in_refuses_a_bad_argument, "test_query_in_refuses_a_bad_argument", 955);
  run_test(test_a_specific_query_for_all_nodes_arms_nothing, "test_a_specific_query_for_all_nodes_arms_nothing", 964);
  run_test(test_a_report_stops_the_timer_and_clears_the_flag, "test_a_report_stops_the_timer_and_clears_the_flag", 980);
  run_test(test_a_report_in_idle_listener_changes_nothing, "test_a_report_in_idle_listener_changes_nothing", 996);
  run_test(test_a_report_on_another_interface_suppresses_nothing, "test_a_report_on_another_interface_suppresses_nothing", 1012);
  run_test(test_a_report_for_a_group_not_listened_to_is_refused, "test_a_report_for_a_group_not_listened_to_is_refused", 1023);
  run_test(test_an_expiring_timer_sends_a_report_and_sets_the_flag, "test_an_expiring_timer_sends_a_report_and_sets_the_flag", 1035);
  run_test(test_a_sweep_before_the_deadline_fires_nothing, "test_a_sweep_before_the_deadline_fires_nothing", 1053);
  run_test(test_a_sweep_counts_every_due_timer_and_fires_one_per_call, "test_a_sweep_counts_every_due_timer_and_fires_one_per_call", 1069);
  run_test(test_a_sweep_with_nothing_due_is_ok_and_not_busy, "test_a_sweep_with_nothing_due_is_ok_and_not_busy", 1088);
  run_test(test_a_deadline_survives_the_millisecond_clocks_wrap, "test_a_deadline_survives_the_millisecond_clocks_wrap", 1101);
  run_test(test_the_state_diagram_walks_end_to_end, "test_the_state_diagram_walks_end_to_end", 1116);
  run_test(test_the_machine_on_two_borrows_stays_independent, "test_the_machine_on_two_borrows_stays_independent", 1146);
  run_test(test_the_same_query_on_two_identical_borrows_draws_the_same_delay, "test_the_same_query_on_two_identical_borrows_draws_the_same_delay", 1165);
  run_test(test_the_group_entries_refuse_a_call_that_names_no_group, "test_the_group_entries_refuse_a_call_that_names_no_group", 1181);
  run_test(test_a_join_that_names_no_group_is_refused, "test_a_join_that_names_no_group_is_refused", 1199);
  run_test(test_a_query_asking_for_longer_than_the_running_timer_leaves_it, "test_a_query_asking_for_longer_than_the_running_timer_leaves_it", 1208);

  return UNITY_END();
}
