/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/checksum.h"
#include "src/ip/ipv4.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_rfc791_figure4_offsets(void);
extern void test_each_accessor_reads_only_its_own_field(void);
extern void test_version_and_ihl_share_the_first_octet(void);
extern void test_ihl_bounds_are_five_through_fifteen(void);
extern void test_ihl_word_count_scales_by_a_shift_of_two(void);
extern void test_flag_bit_positions(void);
extern void test_each_flag_predicate_reads_its_own_bit(void);
extern void test_fragment_offset_is_units_of_eight_octets(void);
extern void test_unfragmented_has_all_zero_fragmentation_information(void);
extern void test_rfc791_figure5_minimal_datagram(void);
extern void test_rfc791_figure6_moderate_datagram(void);
extern void test_rfc791_figure7_first_fragment(void);
extern void test_rfc791_figure8_second_fragment(void);
extern void test_rfc791_appendix_a_fragments_cover_the_original(void);
extern void test_rfc791_example_fragmentation_procedure(void);
extern void test_rfc791_figure9_options_datagram(void);
extern void test_five_word_header_has_no_options(void);
extern void test_recksum_computes_with_the_field_zero(void);
extern void test_a_built_header_checks_out_over_itself(void);
extern void test_verify_rejects_every_single_bit_flip(void);
extern void test_recksum_after_a_field_edit(void);
extern void test_verify_rejects_a_version_other_than_four(void);
extern void test_verify_rejects_an_ihl_below_five(void);
extern void test_verify_rejects_a_buffer_shorter_than_the_fixed_header(void);
extern void test_verify_rejects_a_header_longer_than_the_buffer(void);
extern void test_verify_rejects_total_length_below_the_header(void);
extern void test_verify_rejects_total_length_past_the_buffer(void);
extern void test_verify_accepts_a_buffer_longer_than_total_length(void);
extern void test_reserved_flag_is_readable_and_does_not_fail_verify(void);
extern void test_build_is_a_function_of_its_fields_alone(void);
extern void test_build_round_trips_every_field(void);
extern void test_length_constants(void);
extern void test_minimum_forwardable_datagram_is_sixty_eight_octets(void);
extern void test_five_hundred_seventy_six_is_the_required_reassembly_size(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/ip/test_ipv4\\test_ipv4.c");
  run_test(test_rfc791_figure4_offsets, "test_rfc791_figure4_offsets", 122);
  run_test(test_each_accessor_reads_only_its_own_field, "test_each_accessor_reads_only_its_own_field", 140);
  run_test(test_version_and_ihl_share_the_first_octet, "test_version_and_ihl_share_the_first_octet", 196);
  run_test(test_ihl_bounds_are_five_through_fifteen, "test_ihl_bounds_are_five_through_fifteen", 220);
  run_test(test_ihl_word_count_scales_by_a_shift_of_two, "test_ihl_word_count_scales_by_a_shift_of_two", 245);
  run_test(test_flag_bit_positions, "test_flag_bit_positions", 260);
  run_test(test_each_flag_predicate_reads_its_own_bit, "test_each_flag_predicate_reads_its_own_bit", 273);
  run_test(test_fragment_offset_is_units_of_eight_octets, "test_fragment_offset_is_units_of_eight_octets", 306);
  run_test(test_unfragmented_has_all_zero_fragmentation_information, "test_unfragmented_has_all_zero_fragmentation_information", 333);
  run_test(test_rfc791_figure5_minimal_datagram, "test_rfc791_figure5_minimal_datagram", 358);
  run_test(test_rfc791_figure6_moderate_datagram, "test_rfc791_figure6_moderate_datagram", 394);
  run_test(test_rfc791_figure7_first_fragment, "test_rfc791_figure7_first_fragment", 417);
  run_test(test_rfc791_figure8_second_fragment, "test_rfc791_figure8_second_fragment", 444);
  run_test(test_rfc791_appendix_a_fragments_cover_the_original, "test_rfc791_appendix_a_fragments_cover_the_original", 466);
  run_test(test_rfc791_example_fragmentation_procedure, "test_rfc791_example_fragmentation_procedure", 493);
  run_test(test_rfc791_figure9_options_datagram, "test_rfc791_figure9_options_datagram", 522);
  run_test(test_five_word_header_has_no_options, "test_five_word_header_has_no_options", 562);
  run_test(test_recksum_computes_with_the_field_zero, "test_recksum_computes_with_the_field_zero", 576);
  run_test(test_a_built_header_checks_out_over_itself, "test_a_built_header_checks_out_over_itself", 590);
  run_test(test_verify_rejects_every_single_bit_flip, "test_verify_rejects_every_single_bit_flip", 601);
  run_test(test_recksum_after_a_field_edit, "test_recksum_after_a_field_edit", 623);
  run_test(test_verify_rejects_a_version_other_than_four, "test_verify_rejects_a_version_other_than_four", 639);
  run_test(test_verify_rejects_an_ihl_below_five, "test_verify_rejects_an_ihl_below_five", 664);
  run_test(test_verify_rejects_a_buffer_shorter_than_the_fixed_header, "test_verify_rejects_a_buffer_shorter_than_the_fixed_header", 679);
  run_test(test_verify_rejects_a_header_longer_than_the_buffer, "test_verify_rejects_a_header_longer_than_the_buffer", 691);
  run_test(test_verify_rejects_total_length_below_the_header, "test_verify_rejects_total_length_below_the_header", 707);
  run_test(test_verify_rejects_total_length_past_the_buffer, "test_verify_rejects_total_length_past_the_buffer", 723);
  run_test(test_verify_accepts_a_buffer_longer_than_total_length, "test_verify_accepts_a_buffer_longer_than_total_length", 736);
  run_test(test_reserved_flag_is_readable_and_does_not_fail_verify, "test_reserved_flag_is_readable_and_does_not_fail_verify", 749);
  run_test(test_build_is_a_function_of_its_fields_alone, "test_build_is_a_function_of_its_fields_alone", 764);
  run_test(test_build_round_trips_every_field, "test_build_round_trips_every_field", 782);
  run_test(test_length_constants, "test_length_constants", 822);
  run_test(test_minimum_forwardable_datagram_is_sixty_eight_octets, "test_minimum_forwardable_datagram_is_sixty_eight_octets", 832);
  run_test(test_five_hundred_seventy_six_is_the_required_reassembly_size, "test_five_hundred_seventy_six_is_the_required_reassembly_size", 840);

  return UNITY_END();
}
