/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/ip/ip4_reass.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_clear_on_one_borrow_leaves_the_other_alone(void);
extern void test_clear_reports_ok(void);
extern void test_clear_zeroes_the_tables(void);
extern void test_clear_leaves_the_operand_block_alone(void);
extern void test_an_uncleared_borrow_is_refused(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_the_borrow_covers_the_published_map(void);
extern void test_a_row_index_fits_the_published_terminator(void);
extern void test_every_region_starts_aligned(void);
extern void test_the_hole_table_matches_rfc_815(void);
extern void test_a_refused_hold_reports_no_row(void);
extern void test_a_576_octet_datagram_reassembles_from_its_smallest_fragments(void);
extern void test_two_fragments_in_order_complete_the_datagram(void);
extern void test_fragments_out_of_order_complete_the_datagram(void);
extern void test_the_last_fragment_alone_leaves_the_leading_hole(void);
extern void test_a_fragment_in_the_middle_of_a_hole_leaves_a_hole_at_each_end(void);
extern void test_step_six_makes_no_hole_past_the_last_fragment(void);
extern void test_a_duplicate_fragment_is_refused_and_pins_nothing(void);
extern void test_a_partially_overlapping_fragment_fills_the_hole(void);
extern void test_an_exactly_repeated_fragment_is_not_an_overlap(void);
extern void test_each_field_of_the_buffer_identifier_selects_the_row(void);
extern void test_a_whole_datagram_flushes_its_buffer_identifier(void);
extern void test_a_whole_datagram_with_no_row_names_none(void);
extern void test_total_len_is_the_rfc_791_total_data_length(void);
extern void test_next_reports_every_fragment_in_ascending_offset(void);
extern void test_next_reports_the_header_length_of_each_fragment(void);
extern void test_next_on_a_gathering_row_is_busy_and_past_the_table_is_refused(void);
extern void test_release_then_reclaim_hands_every_descriptor_back(void);
extern void test_release_of_a_free_or_already_released_row_is_refused(void);
extern void test_a_gathering_row_can_be_released(void);
extern void test_reclaim_with_nothing_waiting_is_busy(void);
extern void test_a_partial_datagram_times_out_at_the_lower_bound(void);
extern void test_the_deadline_does_not_come_from_the_time_to_live(void);
extern void test_a_later_fragment_does_not_move_the_deadline(void);
extern void test_a_timeout_reports_the_source_and_whether_fragment_zero_arrived(void);
extern void test_a_completed_row_the_caller_left_also_times_out(void);
extern void test_the_sweep_names_every_reached_row_one_at_a_time(void);
extern void test_the_deadline_survives_the_clock_wrapping(void);
extern void test_a_full_datagram_table_is_busy_and_the_retry_succeeds(void);
extern void test_a_full_fragment_table_is_busy_and_the_retry_succeeds(void);
extern void test_a_fragment_with_no_data_is_refused(void);
extern void test_a_non_final_fragment_off_the_eight_octet_boundary_is_refused(void);
extern void test_a_fragment_past_the_total_length_field_is_refused(void);
extern void test_a_fragment_past_the_total_data_length_is_refused(void);
extern void test_a_second_last_fragment_of_a_different_length_is_refused(void);
extern void test_a_last_fragment_below_what_is_held_is_refused(void);
extern void test_a_malformed_header_is_refused(void);
extern void test_a_refused_fragment_consumes_nothing(void);
extern void test_two_borrows_reassemble_independently(void);
extern void test_a_hold_is_a_function_of_its_borrow_alone(void);
extern void test_clear_drops_a_reassembly_in_progress(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/ip/test_ip4_reass\\test_ip4_reass.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 74);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 86);
  run_test(test_clear_on_one_borrow_leaves_the_other_alone, "test_clear_on_one_borrow_leaves_the_other_alone", 114);
  run_test(test_clear_reports_ok, "test_clear_reports_ok", 128);
  run_test(test_clear_zeroes_the_tables, "test_clear_zeroes_the_tables", 135);
  run_test(test_clear_leaves_the_operand_block_alone, "test_clear_leaves_the_operand_block_alone", 142);
  run_test(test_an_uncleared_borrow_is_refused, "test_an_uncleared_borrow_is_refused", 155);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 176);
  run_test(test_the_borrow_covers_the_published_map, "test_the_borrow_covers_the_published_map", 190);
  run_test(test_a_row_index_fits_the_published_terminator, "test_a_row_index_fits_the_published_terminator", 196);
  run_test(test_every_region_starts_aligned, "test_every_region_starts_aligned", 203);
  run_test(test_the_hole_table_matches_rfc_815, "test_the_hole_table_matches_rfc_815", 212);
  run_test(test_a_refused_hold_reports_no_row, "test_a_refused_hold_reports_no_row", 320);
  run_test(test_a_576_octet_datagram_reassembles_from_its_smallest_fragments, "test_a_576_octet_datagram_reassembles_from_its_smallest_fragments", 336);
  run_test(test_two_fragments_in_order_complete_the_datagram, "test_two_fragments_in_order_complete_the_datagram", 374);
  run_test(test_fragments_out_of_order_complete_the_datagram, "test_fragments_out_of_order_complete_the_datagram", 393);
  run_test(test_the_last_fragment_alone_leaves_the_leading_hole, "test_the_last_fragment_alone_leaves_the_leading_hole", 408);
  run_test(test_a_fragment_in_the_middle_of_a_hole_leaves_a_hole_at_each_end, "test_a_fragment_in_the_middle_of_a_hole_leaves_a_hole_at_each_end", 427);
  run_test(test_step_six_makes_no_hole_past_the_last_fragment, "test_step_six_makes_no_hole_past_the_last_fragment", 445);
  run_test(test_a_duplicate_fragment_is_refused_and_pins_nothing, "test_a_duplicate_fragment_is_refused_and_pins_nothing", 458);
  run_test(test_a_partially_overlapping_fragment_fills_the_hole, "test_a_partially_overlapping_fragment_fills_the_hole", 481);
  run_test(test_an_exactly_repeated_fragment_is_not_an_overlap, "test_an_exactly_repeated_fragment_is_not_an_overlap", 494);
  run_test(test_each_field_of_the_buffer_identifier_selects_the_row, "test_each_field_of_the_buffer_identifier_selects_the_row", 510);
  run_test(test_a_whole_datagram_flushes_its_buffer_identifier, "test_a_whole_datagram_flushes_its_buffer_identifier", 547);
  run_test(test_a_whole_datagram_with_no_row_names_none, "test_a_whole_datagram_with_no_row_names_none", 566);
  run_test(test_total_len_is_the_rfc_791_total_data_length, "test_total_len_is_the_rfc_791_total_data_length", 576);
  run_test(test_next_reports_every_fragment_in_ascending_offset, "test_next_reports_every_fragment_in_ascending_offset", 590);
  run_test(test_next_reports_the_header_length_of_each_fragment, "test_next_reports_the_header_length_of_each_fragment", 624);
  run_test(test_next_on_a_gathering_row_is_busy_and_past_the_table_is_refused, "test_next_on_a_gathering_row_is_busy_and_past_the_table_is_refused", 643);
  run_test(test_release_then_reclaim_hands_every_descriptor_back, "test_release_then_reclaim_hands_every_descriptor_back", 660);
  run_test(test_release_of_a_free_or_already_released_row_is_refused, "test_release_of_a_free_or_already_released_row_is_refused", 690);
  run_test(test_a_gathering_row_can_be_released, "test_a_gathering_row_can_be_released", 703);
  run_test(test_reclaim_with_nothing_waiting_is_busy, "test_reclaim_with_nothing_waiting_is_busy", 715);
  run_test(test_a_partial_datagram_times_out_at_the_lower_bound, "test_a_partial_datagram_times_out_at_the_lower_bound", 726);
  run_test(test_the_deadline_does_not_come_from_the_time_to_live, "test_the_deadline_does_not_come_from_the_time_to_live", 748);
  run_test(test_a_later_fragment_does_not_move_the_deadline, "test_a_later_fragment_does_not_move_the_deadline", 769);
  run_test(test_a_timeout_reports_the_source_and_whether_fragment_zero_arrived, "test_a_timeout_reports_the_source_and_whether_fragment_zero_arrived", 787);
  run_test(test_a_completed_row_the_caller_left_also_times_out, "test_a_completed_row_the_caller_left_also_times_out", 811);
  run_test(test_the_sweep_names_every_reached_row_one_at_a_time, "test_the_sweep_names_every_reached_row_one_at_a_time", 827);
  run_test(test_the_deadline_survives_the_clock_wrapping, "test_the_deadline_survives_the_clock_wrapping", 855);
  run_test(test_a_full_datagram_table_is_busy_and_the_retry_succeeds, "test_a_full_datagram_table_is_busy_and_the_retry_succeeds", 869);
  run_test(test_a_full_fragment_table_is_busy_and_the_retry_succeeds, "test_a_full_fragment_table_is_busy_and_the_retry_succeeds", 894);
  run_test(test_a_fragment_with_no_data_is_refused, "test_a_fragment_with_no_data_is_refused", 914);
  run_test(test_a_non_final_fragment_off_the_eight_octet_boundary_is_refused, "test_a_non_final_fragment_off_the_eight_octet_boundary_is_refused", 923);
  run_test(test_a_fragment_past_the_total_length_field_is_refused, "test_a_fragment_past_the_total_length_field_is_refused", 934);
  run_test(test_a_fragment_past_the_total_data_length_is_refused, "test_a_fragment_past_the_total_data_length_is_refused", 944);
  run_test(test_a_second_last_fragment_of_a_different_length_is_refused, "test_a_second_last_fragment_of_a_different_length_is_refused", 955);
  run_test(test_a_last_fragment_below_what_is_held_is_refused, "test_a_last_fragment_below_what_is_held_is_refused", 967);
  run_test(test_a_malformed_header_is_refused, "test_a_malformed_header_is_refused", 978);
  run_test(test_a_refused_fragment_consumes_nothing, "test_a_refused_fragment_consumes_nothing", 1001);
  run_test(test_two_borrows_reassemble_independently, "test_two_borrows_reassemble_independently", 1018);
  run_test(test_a_hold_is_a_function_of_its_borrow_alone, "test_a_hold_is_a_function_of_its_borrow_alone", 1038);
  run_test(test_clear_drops_a_reassembly_in_progress, "test_clear_drops_a_reassembly_in_progress", 1059);

  return UNITY_END();
}
