/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/core/tick.h"
#include "src/arp/arp.h"
#include "src/ip/ipv4.h"
#include "src/ip/ipv6.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_every_entry_refuses_an_uncleared_borrow(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_the_published_offsets_are_ordered_and_fit(void);
extern void test_if_bind_refuses_an_index_past_the_table(void);
extern void test_a_phase_entry_before_its_turn_is_refused(void);
extern void test_a_phase_entry_after_its_turn_is_refused(void);
extern void test_no_phase_runs_before_the_tick_is_opened(void);
extern void test_the_three_phases_run_in_order_to_done(void);
extern void test_opening_again_starts_the_order_over(void);
extern void test_the_service_phase_reports_its_units_in_dependency_order(void);
extern void test_an_empty_deadline_list_reports_forever(void);
extern void test_a_deadline_ahead_is_reported_as_the_wait(void);
extern void test_an_expired_deadline_is_reported_with_its_unit(void);
extern void test_a_deadline_across_the_wrap_is_still_ahead(void);
extern void test_an_empty_ring_drains_busy(void);
extern void test_a_frame_is_dispatched_and_its_descriptor_returned(void);
extern void test_a_tick_hands_the_random_word_it_opened_with_to_every_frame_it_drains(void);
extern void test_a_retained_frame_keeps_its_descriptor_out_of_the_ring(void);
extern void test_an_expired_datagram_returns_every_descriptor_it_pinned(void);
extern void test_the_ring_still_receives_after_a_retained_frame_is_released(void);
extern void test_a_completed_datagram_still_holds_its_descriptors(void);
extern void test_an_expired_ipv6_datagram_returns_every_descriptor_it_pinned(void);
extern void test_a_completed_ipv6_datagram_still_holds_its_descriptors(void);
extern void test_the_service_phase_runs_the_mld_report_delay_down(void);
extern void test_the_drain_takes_every_waiting_frame(void);
extern void test_the_drain_takes_a_frame_addressed_to_our_directed_broadcast(void);
extern void test_the_drain_reads_a_tagged_frame_behind_its_tag(void);
extern void test_the_drain_discards_a_wire_frame_addressed_to_the_loopback_range(void);
extern void test_a_resolved_hold_is_reported_and_unpinned_one_step_later(void);
extern void test_the_flush_phase_reports_its_units_in_order(void);
extern void test_an_expired_ipv4_datagram_is_reported_for_a_time_exceeded(void);
extern void test_an_abandoned_ipv6_datagram_is_reported_for_a_time_exceeded(void);
extern void test_an_interface_with_no_ring_is_stepped_over(void);
extern void test_a_descriptor_from_the_second_interface_goes_back_to_it(void);
extern void test_a_descriptor_handle_round_trips(void);
extern void test_an_unbound_service_is_skipped(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/core/test_tick\\test_tick.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 349);
  run_test(test_every_entry_refuses_an_uncleared_borrow, "test_every_entry_refuses_an_uncleared_borrow", 361);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 380);
  run_test(test_the_published_offsets_are_ordered_and_fit, "test_the_published_offsets_are_ordered_and_fit", 396);
  run_test(test_if_bind_refuses_an_index_past_the_table, "test_if_bind_refuses_an_index_past_the_table", 405);
  run_test(test_a_phase_entry_before_its_turn_is_refused, "test_a_phase_entry_before_its_turn_is_refused", 416);
  run_test(test_a_phase_entry_after_its_turn_is_refused, "test_a_phase_entry_after_its_turn_is_refused", 427);
  run_test(test_no_phase_runs_before_the_tick_is_opened, "test_no_phase_runs_before_the_tick_is_opened", 440);
  run_test(test_the_three_phases_run_in_order_to_done, "test_the_three_phases_run_in_order_to_done", 452);
  run_test(test_opening_again_starts_the_order_over, "test_opening_again_starts_the_order_over", 474);
  run_test(test_the_service_phase_reports_its_units_in_dependency_order, "test_the_service_phase_reports_its_units_in_dependency_order", 497);
  run_test(test_an_empty_deadline_list_reports_forever, "test_an_empty_deadline_list_reports_forever", 533);
  run_test(test_a_deadline_ahead_is_reported_as_the_wait, "test_a_deadline_ahead_is_reported_as_the_wait", 540);
  run_test(test_an_expired_deadline_is_reported_with_its_unit, "test_an_expired_deadline_is_reported_with_its_unit", 557);
  run_test(test_a_deadline_across_the_wrap_is_still_ahead, "test_a_deadline_across_the_wrap_is_still_ahead", 588);
  run_test(test_an_empty_ring_drains_busy, "test_an_empty_ring_drains_busy", 606);
  run_test(test_a_frame_is_dispatched_and_its_descriptor_returned, "test_a_frame_is_dispatched_and_its_descriptor_returned", 616);
  run_test(test_a_tick_hands_the_random_word_it_opened_with_to_every_frame_it_drains, "test_a_tick_hands_the_random_word_it_opened_with_to_every_frame_it_drains", 646);
  run_test(test_a_retained_frame_keeps_its_descriptor_out_of_the_ring, "test_a_retained_frame_keeps_its_descriptor_out_of_the_ring", 664);
  run_test(test_an_expired_datagram_returns_every_descriptor_it_pinned, "test_an_expired_datagram_returns_every_descriptor_it_pinned", 683);
  run_test(test_the_ring_still_receives_after_a_retained_frame_is_released, "test_the_ring_still_receives_after_a_retained_frame_is_released", 725);
  run_test(test_a_completed_datagram_still_holds_its_descriptors, "test_a_completed_datagram_still_holds_its_descriptors", 753);
  run_test(test_an_expired_ipv6_datagram_returns_every_descriptor_it_pinned, "test_an_expired_ipv6_datagram_returns_every_descriptor_it_pinned", 823);
  run_test(test_a_completed_ipv6_datagram_still_holds_its_descriptors, "test_a_completed_ipv6_datagram_still_holds_its_descriptors", 863);
  run_test(test_the_service_phase_runs_the_mld_report_delay_down, "test_the_service_phase_runs_the_mld_report_delay_down", 886);
  run_test(test_the_drain_takes_every_waiting_frame, "test_the_drain_takes_every_waiting_frame", 923);
  run_test(test_the_drain_takes_a_frame_addressed_to_our_directed_broadcast, "test_the_drain_takes_a_frame_addressed_to_our_directed_broadcast", 943);
  run_test(test_the_drain_reads_a_tagged_frame_behind_its_tag, "test_the_drain_reads_a_tagged_frame_behind_its_tag", 979);
  run_test(test_the_drain_discards_a_wire_frame_addressed_to_the_loopback_range, "test_the_drain_discards_a_wire_frame_addressed_to_the_loopback_range", 1033);
  run_test(test_a_resolved_hold_is_reported_and_unpinned_one_step_later, "test_a_resolved_hold_is_reported_and_unpinned_one_step_later", 1070);
  run_test(test_the_flush_phase_reports_its_units_in_order, "test_the_flush_phase_reports_its_units_in_order", 1131);
  run_test(test_an_expired_ipv4_datagram_is_reported_for_a_time_exceeded, "test_an_expired_ipv4_datagram_is_reported_for_a_time_exceeded", 1191);
  run_test(test_an_abandoned_ipv6_datagram_is_reported_for_a_time_exceeded, "test_an_abandoned_ipv6_datagram_is_reported_for_a_time_exceeded", 1246);
  run_test(test_an_interface_with_no_ring_is_stepped_over, "test_an_interface_with_no_ring_is_stepped_over", 1293);
  run_test(test_a_descriptor_from_the_second_interface_goes_back_to_it, "test_a_descriptor_from_the_second_interface_goes_back_to_it", 1321);
  run_test(test_a_descriptor_handle_round_trips, "test_a_descriptor_handle_round_trips", 1410);
  run_test(test_an_unbound_service_is_skipped, "test_an_unbound_service_is_skipped", 1427);

  return UNITY_END();
}
