/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/dhcp/dhcp6.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_every_entry_survives_a_null_borrow(void);
extern void test_the_published_offsets_are_ordered_and_do_not_overlap(void);
extern void test_the_duid_region_holds_the_longest_duid(void);
extern void test_the_io_macro_lands_on_the_published_offset(void);
extern void test_clear_zeroes_the_regions(void);
extern void test_clear_touches_one_borrow_only(void);
extern void test_two_borrows_share_no_byte(void);
extern void test_a_call_is_a_function_of_its_borrow_alone(void);
extern void test_unbound_borrow_refuses_work(void);
extern void test_clear_does_not_bind(void);
extern void test_bind_refuses_null_cfg(void);
extern void test_bind_refuses_an_unusable_cfg(void);
extern void test_bind_accepts_a_complete_cfg(void);
extern void test_the_message_types_are_as_the_rfc_prints_them(void);
extern void test_the_constants_are_as_the_rfc_prints_them(void);
extern void test_the_sec_7_6_parameters_are_as_the_rfc_prints_them(void);
extern void test_the_quantized_rand_stays_inside_the_sec_15_tenth(void);
extern void test_the_elapsed_time_reciprocal_is_exact_over_the_whole_field(void);
extern void test_the_solicit_carries_the_options_sec_18_2_1_names(void);
extern void test_the_solicit_carries_rapid_commit_when_configured(void);
extern void test_a_stateless_client_sends_an_information_request(void);
extern void test_only_the_information_request_asks_for_the_refresh_time(void);
extern void test_the_message_goes_to_the_all_agents_multicast_address(void);
extern void test_build_is_busy_until_a_tick_arms_a_message(void);
extern void test_a_buffer_too_short_for_the_message_is_refused(void);
extern void test_a_build_buffer_under_the_fixed_header_is_refused(void);
extern void test_every_buffer_under_the_whole_message_is_refused(void);
extern void test_the_first_solicit_delay_stays_inside_sol_max_delay(void);
extern void test_the_first_solicit_rt_is_strictly_greater_than_sol_timeout(void);
extern void test_each_later_rt_doubles_inside_the_sec_15_bound(void);
extern void test_the_retransmission_timeout_stops_at_mrt(void);
extern void test_the_elapsed_time_counts_from_the_first_message(void);
extern void test_the_client_discards_every_type_it_must(void);
extern void test_a_message_with_the_wrong_transaction_id_is_discarded(void);
extern void test_a_message_with_no_server_identifier_is_discarded(void);
extern void test_a_message_whose_client_identifier_is_not_ours_is_discarded(void);
extern void test_an_option_length_past_the_end_of_the_message_is_refused(void);
extern void test_an_unknown_option_does_not_discard_the_message(void);
extern void test_an_option_past_the_end_of_its_ia_na_is_refused(void);
extern void test_a_server_identifier_under_three_octets_is_refused(void);
extern void test_a_preference_of_255_requests_at_once(void);
extern void test_a_lesser_preference_waits_for_the_first_rt(void);
extern void test_the_highest_preference_advertise_wins(void);
extern void test_an_advertise_with_no_address_is_ignored(void);
extern void test_sol_max_rt_is_taken_from_a_discarded_advertise(void);
extern void test_a_sol_max_rt_outside_its_range_is_ignored(void);
extern void test_two_advertises_that_disagree_on_sol_max_rt_leave_the_default(void);
extern void test_an_advertise_outside_the_solicit_is_ignored(void);
extern void test_a_reply_assigns_the_lease_from_the_ia_na(void);
extern void test_an_ia_na_with_t1_past_t2_is_discarded(void);
extern void test_an_unusable_address_is_discarded(void);
extern void test_an_ia_na_with_another_iaid_is_not_taken(void);
extern void test_a_no_addrs_avail_status_inside_the_ia_na_stops_the_lease(void);
extern void test_a_reply_with_no_ia_na_assigns_nothing(void);
extern void test_a_zero_t1_and_t2_are_chosen_by_the_client(void);
extern void test_an_infinite_preferred_lifetime_makes_t1_and_t2_infinite(void);
extern void test_a_client_picked_t1_or_t2_never_lands_on_zero(void);
extern void test_a_bound_lease_that_reaches_its_valid_lifetime_starts_over(void);
extern void test_the_request_names_the_server_and_the_offered_address(void);
extern void test_the_transaction_id_holds_across_retransmissions(void);
extern void test_the_request_gives_up_after_req_max_rc_transmissions(void);
extern void test_use_multicast_resends_the_original_message(void);
extern void test_not_on_link_restarts_the_discovery_process(void);
extern void test_a_rapid_commit_reply_binds_straight_from_soliciting(void);
extern void test_a_client_without_rapid_commit_discards_the_reply(void);
extern void test_a_rapid_commit_reply_with_no_lease_binds_nothing(void);
extern void test_t1_starts_the_renew_and_t2_the_rebind(void);
extern void test_a_no_binding_reply_to_a_renew_sends_a_request(void);
extern void test_a_no_binding_reply_to_a_rebind_sends_a_request(void);
extern void test_the_rebind_ends_when_the_valid_lifetime_expires(void);
extern void test_a_reply_to_the_renew_extends_the_lease(void);
extern void test_the_renew_retransmits_under_ren_max_rt(void);
extern void test_the_rebind_retransmits_under_reb_max_rt(void);
extern void test_a_rebind_reply_that_names_no_server_is_refused(void);
extern void test_the_confirm_zeroes_its_times_and_ends_at_cnf_max_rd(void);
extern void test_a_not_on_link_confirm_reply_restarts_discovery(void);
extern void test_the_release_names_the_server_and_the_lease(void);
extern void test_release_and_decline_stop_at_their_retry_counts(void);
extern void test_confirm_release_and_decline_refuse_without_a_lease(void);
extern void test_a_confirm_reply_without_not_on_link_keeps_the_lease(void);
extern void test_the_first_confirm_waits_out_its_random_delay(void);
extern void test_a_reply_to_the_decline_completes_it(void);
extern void test_the_confirm_retransmits_up_to_cnf_max_rt(void);
extern void test_the_dns_servers_option_is_read_out_of_the_message(void);
extern void test_a_dns_servers_option_of_a_ragged_length_is_ignored(void);
extern void test_the_information_refresh_time_schedules_the_next_request(void);
extern void test_inf_max_rt_is_taken_only_inside_its_range(void);
extern void test_an_infinite_information_refresh_time_never_asks_again(void);
extern void test_two_clients_run_independent_exchanges(void);
extern void test_stop_ends_the_exchange_and_drops_the_lease(void);
extern void test_start_refuses_a_running_client(void);
extern void test_a_short_or_absent_message_is_refused(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/dhcp/test_dhcp6\\test_dhcp6.c");
  run_test(test_every_entry_survives_a_null_borrow, "test_every_entry_survives_a_null_borrow", 82);
  run_test(test_the_published_offsets_are_ordered_and_do_not_overlap, "test_the_published_offsets_are_ordered_and_do_not_overlap", 98);
  run_test(test_the_duid_region_holds_the_longest_duid, "test_the_duid_region_holds_the_longest_duid", 111);
  run_test(test_the_io_macro_lands_on_the_published_offset, "test_the_io_macro_lands_on_the_published_offset", 117);
  run_test(test_clear_zeroes_the_regions, "test_clear_zeroes_the_regions", 124);
  run_test(test_clear_touches_one_borrow_only, "test_clear_touches_one_borrow_only", 146);
  run_test(test_two_borrows_share_no_byte, "test_two_borrows_share_no_byte", 159);
  run_test(test_a_call_is_a_function_of_its_borrow_alone, "test_a_call_is_a_function_of_its_borrow_alone", 182);
  run_test(test_unbound_borrow_refuses_work, "test_unbound_borrow_refuses_work", 197);
  run_test(test_clear_does_not_bind, "test_clear_does_not_bind", 217);
  run_test(test_bind_refuses_null_cfg, "test_bind_refuses_null_cfg", 227);
  run_test(test_bind_refuses_an_unusable_cfg, "test_bind_refuses_an_unusable_cfg", 236);
  run_test(test_bind_accepts_a_complete_cfg, "test_bind_accepts_a_complete_cfg", 262);
  run_test(test_the_message_types_are_as_the_rfc_prints_them, "test_the_message_types_are_as_the_rfc_prints_them", 272);
  run_test(test_the_constants_are_as_the_rfc_prints_them, "test_the_constants_are_as_the_rfc_prints_them", 291);
  run_test(test_the_sec_7_6_parameters_are_as_the_rfc_prints_them, "test_the_sec_7_6_parameters_are_as_the_rfc_prints_them", 576);
  run_test(test_the_quantized_rand_stays_inside_the_sec_15_tenth, "test_the_quantized_rand_stays_inside_the_sec_15_tenth", 606);
  run_test(test_the_elapsed_time_reciprocal_is_exact_over_the_whole_field, "test_the_elapsed_time_reciprocal_is_exact_over_the_whole_field", 617);
  run_test(test_the_solicit_carries_the_options_sec_18_2_1_names, "test_the_solicit_carries_the_options_sec_18_2_1_names", 641);
  run_test(test_the_solicit_carries_rapid_commit_when_configured, "test_the_solicit_carries_rapid_commit_when_configured", 686);
  run_test(test_a_stateless_client_sends_an_information_request, "test_a_stateless_client_sends_an_information_request", 697);
  run_test(test_only_the_information_request_asks_for_the_refresh_time, "test_only_the_information_request_asks_for_the_refresh_time", 721);
  run_test(test_the_message_goes_to_the_all_agents_multicast_address, "test_the_message_goes_to_the_all_agents_multicast_address", 736);
  run_test(test_build_is_busy_until_a_tick_arms_a_message, "test_build_is_busy_until_a_tick_arms_a_message", 748);
  run_test(test_a_buffer_too_short_for_the_message_is_refused, "test_a_buffer_too_short_for_the_message_is_refused", 765);
  run_test(test_a_build_buffer_under_the_fixed_header_is_refused, "test_a_build_buffer_under_the_fixed_header_is_refused", 776);
  run_test(test_every_buffer_under_the_whole_message_is_refused, "test_every_buffer_under_the_whole_message_is_refused", 794);
  run_test(test_the_first_solicit_delay_stays_inside_sol_max_delay, "test_the_first_solicit_delay_stays_inside_sol_max_delay", 816);
  run_test(test_the_first_solicit_rt_is_strictly_greater_than_sol_timeout, "test_the_first_solicit_rt_is_strictly_greater_than_sol_timeout", 835);
  run_test(test_each_later_rt_doubles_inside_the_sec_15_bound, "test_each_later_rt_doubles_inside_the_sec_15_bound", 851);
  run_test(test_the_retransmission_timeout_stops_at_mrt, "test_the_retransmission_timeout_stops_at_mrt", 870);
  run_test(test_the_elapsed_time_counts_from_the_first_message, "test_the_elapsed_time_counts_from_the_first_message", 890);
  run_test(test_the_client_discards_every_type_it_must, "test_the_client_discards_every_type_it_must", 912);
  run_test(test_a_message_with_the_wrong_transaction_id_is_discarded, "test_a_message_with_the_wrong_transaction_id_is_discarded", 941);
  run_test(test_a_message_with_no_server_identifier_is_discarded, "test_a_message_with_no_server_identifier_is_discarded", 954);
  run_test(test_a_message_whose_client_identifier_is_not_ours_is_discarded, "test_a_message_whose_client_identifier_is_not_ours_is_discarded", 966);
  run_test(test_an_option_length_past_the_end_of_the_message_is_refused, "test_an_option_length_past_the_end_of_the_message_is_refused", 984);
  run_test(test_an_unknown_option_does_not_discard_the_message, "test_an_unknown_option_does_not_discard_the_message", 1004);
  run_test(test_an_option_past_the_end_of_its_ia_na_is_refused, "test_an_option_past_the_end_of_its_ia_na_is_refused", 1020);
  run_test(test_a_server_identifier_under_three_octets_is_refused, "test_a_server_identifier_under_three_octets_is_refused", 1042);
  run_test(test_a_preference_of_255_requests_at_once, "test_a_preference_of_255_requests_at_once", 1060);
  run_test(test_a_lesser_preference_waits_for_the_first_rt, "test_a_lesser_preference_waits_for_the_first_rt", 1075);
  run_test(test_the_highest_preference_advertise_wins, "test_the_highest_preference_advertise_wins", 1094);
  run_test(test_an_advertise_with_no_address_is_ignored, "test_an_advertise_with_no_address_is_ignored", 1138);
  run_test(test_sol_max_rt_is_taken_from_a_discarded_advertise, "test_sol_max_rt_is_taken_from_a_discarded_advertise", 1160);
  run_test(test_a_sol_max_rt_outside_its_range_is_ignored, "test_a_sol_max_rt_outside_its_range_is_ignored", 1185);
  run_test(test_two_advertises_that_disagree_on_sol_max_rt_leave_the_default, "test_two_advertises_that_disagree_on_sol_max_rt_leave_the_default", 1212);
  run_test(test_an_advertise_outside_the_solicit_is_ignored, "test_an_advertise_outside_the_solicit_is_ignored", 1243);
  run_test(test_a_reply_assigns_the_lease_from_the_ia_na, "test_a_reply_assigns_the_lease_from_the_ia_na", 1271);
  run_test(test_an_ia_na_with_t1_past_t2_is_discarded, "test_an_ia_na_with_t1_past_t2_is_discarded", 1284);
  run_test(test_an_unusable_address_is_discarded, "test_an_unusable_address_is_discarded", 1299);
  run_test(test_an_ia_na_with_another_iaid_is_not_taken, "test_an_ia_na_with_another_iaid_is_not_taken", 1322);
  run_test(test_a_no_addrs_avail_status_inside_the_ia_na_stops_the_lease, "test_a_no_addrs_avail_status_inside_the_ia_na_stops_the_lease", 1337);
  run_test(test_a_reply_with_no_ia_na_assigns_nothing, "test_a_reply_with_no_ia_na_assigns_nothing", 1353);
  run_test(test_a_zero_t1_and_t2_are_chosen_by_the_client, "test_a_zero_t1_and_t2_are_chosen_by_the_client", 1381);
  run_test(test_an_infinite_preferred_lifetime_makes_t1_and_t2_infinite, "test_an_infinite_preferred_lifetime_makes_t1_and_t2_infinite", 1393);
  run_test(test_a_client_picked_t1_or_t2_never_lands_on_zero, "test_a_client_picked_t1_or_t2_never_lands_on_zero", 1405);
  run_test(test_a_bound_lease_that_reaches_its_valid_lifetime_starts_over, "test_a_bound_lease_that_reaches_its_valid_lifetime_starts_over", 1419);
  run_test(test_the_request_names_the_server_and_the_offered_address, "test_the_request_names_the_server_and_the_offered_address", 1437);
  run_test(test_the_transaction_id_holds_across_retransmissions, "test_the_transaction_id_holds_across_retransmissions", 1479);
  run_test(test_the_request_gives_up_after_req_max_rc_transmissions, "test_the_request_gives_up_after_req_max_rc_transmissions", 1503);
  run_test(test_use_multicast_resends_the_original_message, "test_use_multicast_resends_the_original_message", 1539);
  run_test(test_not_on_link_restarts_the_discovery_process, "test_not_on_link_restarts_the_discovery_process", 1567);
  run_test(test_a_rapid_commit_reply_binds_straight_from_soliciting, "test_a_rapid_commit_reply_binds_straight_from_soliciting", 1594);
  run_test(test_a_client_without_rapid_commit_discards_the_reply, "test_a_client_without_rapid_commit_discards_the_reply", 1620);
  run_test(test_a_rapid_commit_reply_with_no_lease_binds_nothing, "test_a_rapid_commit_reply_with_no_lease_binds_nothing", 1635);
  run_test(test_t1_starts_the_renew_and_t2_the_rebind, "test_t1_starts_the_renew_and_t2_the_rebind", 1657);
  run_test(test_a_no_binding_reply_to_a_renew_sends_a_request, "test_a_no_binding_reply_to_a_renew_sends_a_request", 1685);
  run_test(test_a_no_binding_reply_to_a_rebind_sends_a_request, "test_a_no_binding_reply_to_a_rebind_sends_a_request", 1709);
  run_test(test_the_rebind_ends_when_the_valid_lifetime_expires, "test_the_rebind_ends_when_the_valid_lifetime_expires", 1739);
  run_test(test_a_reply_to_the_renew_extends_the_lease, "test_a_reply_to_the_renew_extends_the_lease", 1754);
  run_test(test_the_renew_retransmits_under_ren_max_rt, "test_the_renew_retransmits_under_ren_max_rt", 1776);
  run_test(test_the_rebind_retransmits_under_reb_max_rt, "test_the_rebind_retransmits_under_reb_max_rt", 1801);
  run_test(test_a_rebind_reply_that_names_no_server_is_refused, "test_a_rebind_reply_that_names_no_server_is_refused", 1826);
  run_test(test_the_confirm_zeroes_its_times_and_ends_at_cnf_max_rd, "test_the_confirm_zeroes_its_times_and_ends_at_cnf_max_rd", 1851);
  run_test(test_a_not_on_link_confirm_reply_restarts_discovery, "test_a_not_on_link_confirm_reply_restarts_discovery", 1881);
  run_test(test_the_release_names_the_server_and_the_lease, "test_the_release_names_the_server_and_the_lease", 1897);
  run_test(test_release_and_decline_stop_at_their_retry_counts, "test_release_and_decline_stop_at_their_retry_counts", 1929);
  run_test(test_confirm_release_and_decline_refuse_without_a_lease, "test_confirm_release_and_decline_refuse_without_a_lease", 1974);
  run_test(test_a_confirm_reply_without_not_on_link_keeps_the_lease, "test_a_confirm_reply_without_not_on_link_keeps_the_lease", 1995);
  run_test(test_the_first_confirm_waits_out_its_random_delay, "test_the_first_confirm_waits_out_its_random_delay", 2015);
  run_test(test_a_reply_to_the_decline_completes_it, "test_a_reply_to_the_decline_completes_it", 2033);
  run_test(test_the_confirm_retransmits_up_to_cnf_max_rt, "test_the_confirm_retransmits_up_to_cnf_max_rt", 2059);
  run_test(test_the_dns_servers_option_is_read_out_of_the_message, "test_the_dns_servers_option_is_read_out_of_the_message", 2086);
  run_test(test_a_dns_servers_option_of_a_ragged_length_is_ignored, "test_a_dns_servers_option_of_a_ragged_length_is_ignored", 2105);
  run_test(test_the_information_refresh_time_schedules_the_next_request, "test_the_information_refresh_time_schedules_the_next_request", 2120);
  run_test(test_inf_max_rt_is_taken_only_inside_its_range, "test_inf_max_rt_is_taken_only_inside_its_range", 2151);
  run_test(test_an_infinite_information_refresh_time_never_asks_again, "test_an_infinite_information_refresh_time_never_asks_again", 2177);
  run_test(test_two_clients_run_independent_exchanges, "test_two_clients_run_independent_exchanges", 2196);
  run_test(test_stop_ends_the_exchange_and_drops_the_lease, "test_stop_ends_the_exchange_and_drops_the_lease", 2221);
  run_test(test_start_refuses_a_running_client, "test_start_refuses_a_running_client", 2241);
  run_test(test_a_short_or_absent_message_is_refused, "test_a_short_or_absent_message_is_refused", 2255);

  return UNITY_END();
}
