/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "src/common.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_a_zeroed_span_reads_zero_at_every_length_and_alignment(void);
extern void test_one_set_octet_anywhere_makes_a_span_not_zero(void);
extern void test_equality_matches_the_definition_at_every_length_and_alignment(void);
extern void test_an_empty_span_is_zero_and_equal(void);
extern void test_the_address_widths_the_call_sites_use(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("C:/Users/Douglas/Desktop/git_project/work/idemIP/test/unit/base/test_span\\test_span.c");
  run_test(test_a_zeroed_span_reads_zero_at_every_length_and_alignment, "test_a_zeroed_span_reads_zero_at_every_length_and_alignment", 75);
  run_test(test_one_set_octet_anywhere_makes_a_span_not_zero, "test_one_set_octet_anywhere_makes_a_span_not_zero", 88);
  run_test(test_equality_matches_the_definition_at_every_length_and_alignment, "test_equality_matches_the_definition_at_every_length_and_alignment", 111);
  run_test(test_an_empty_span_is_zero_and_equal, "test_an_empty_span_is_zero_and_equal", 142);
  run_test(test_the_address_widths_the_call_sites_use, "test_the_address_widths_the_call_sites_use", 152);

  return UNITY_END();
}
